//! Executable evidence for Documentation Projection v1 (`semaprax doc`).
//!
//! Proves the Markdown and JSON renderings are deterministic, that the CLI
//! prints exactly the library's bytes and fails closed on invalid source or a
//! malformed grammar, and that every documented identity is a declaration of
//! the module's semantic graph at the same revision: the documentation and
//! the graph cannot describe different programs.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicUsize, Ordering};

use semaprax::{doc, graph, verify};

static COUNTER: AtomicUsize = AtomicUsize::new(0);

const COMMENTED: &str = "module demo.commented;\n\n// A counter that only grows.\n// Two lines of description.\n@id(\"demo.counter\")\nclass Counter {\n    // The stored value.\n    @id(\"demo.counter.value\")\n    value: i64,\n\n    // Read the value.\n    @id(\"demo.counter.get\")\n    fn get(self: Counter) -> i64\n    {\n        self.value\n    }\n}\n\n// Entry point.\n@id(\"demo.main\")\nfn main() -> i64\n{\n    Counter { value: 3 }.get()\n}\n";

const EFFECTS_MARKDOWN: &str = "# Module `examples.effects`\n\nGenerated by `semaprax doc` from the checked module. Signatures, identities,\neffects, and contracts are the graph's own facts; descriptions are the leading\ncomments of each declaration.\n\n- Graph revision: `sha256:db7c2f8f5f6c17fd9becd6b4b5dd3ada1789fa3987ec409cc752ad2feb44c936`\n- Permits: `clock.read`\n\n## Functions\n\n### `logical_tick`\n\n```spx\n@id(\"clock.logical_tick\")\nfn logical_tick(value: i64) -> i64\n    uses { clock.read }\n    ensures result == value + 1\n```\n\n- Identity: `clock.logical_tick` (persistent)\n- Parameters: `value: i64`\n- Returns: `i64`\n- Effects: `clock.read`\n- Ensures: `result == value + 1`\n\n### `main`\n\n```spx\n@id(\"app.main\")\nfn main() -> i64\n    uses { clock.read }\n```\n\n- Identity: `app.main` (persistent)\n- Returns: `i64`\n- Effects: `clock.read`\n\n";

/// Documentation kinds that the module graph also carries, mapped onto the
/// graph's node kinds. Protocols and implementations are documented from
/// source but stay out of the program graph (Protocol Projection v1).
const GRAPH_KINDS: &[(&str, &str)] = &[
    ("function", "function"),
    ("method", "function"),
    ("record", "record"),
    ("field", "field"),
    ("variant", "variant"),
    ("case", "variant_case"),
    ("case_field", "case_field"),
    ("class", "class"),
    ("resource", "resource"),
    ("drop", "resource_drop"),
    ("interface", "interface"),
    ("import", "import"),
];

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn fixture_dir() -> PathBuf {
    let path = std::env::temp_dir().join(format!(
        "semaprax-doc-projection-{}-{}",
        std::process::id(),
        COUNTER.fetch_add(1, Ordering::Relaxed)
    ));
    std::fs::create_dir_all(&path).unwrap();
    path
}

fn cli(arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_semaprax"))
        .arg("doc")
        .args(arguments)
        .current_dir(root())
        .output()
        .unwrap()
}

fn checked(path: &Path) -> (semaprax::ast::Program, semaprax::lexer::Comments) {
    let source = std::fs::read_to_string(path).unwrap();
    let (program, comments) = semaprax::parse_with_comments(&source, path).unwrap();
    let diagnostics = verify::verify(&program);
    assert!(
        !diagnostics.iter().any(|item| item.severity.is_error()),
        "{}: {diagnostics:?}",
        path.display()
    );
    (program, comments)
}

fn examples() -> Vec<PathBuf> {
    let mut paths: Vec<_> = std::fs::read_dir(root().join("examples"))
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "spx"))
        .collect();
    paths.sort();
    assert!(paths.len() >= 20, "{}", paths.len());
    paths
}

#[test]
fn markdown_is_the_pinned_deterministic_projection() {
    let path = root().join("examples/effects.spx");
    let (program, comments) = checked(&path);
    let markdown = doc::markdown(&program, &comments);
    assert_eq!(markdown, EFFECTS_MARKDOWN);
    assert_eq!(doc::markdown(&program, &comments), markdown);
    assert!(markdown.contains(&graph::revision(&program)));

    let output = cli(&["examples/effects.spx"]);
    assert!(output.status.success());
    assert!(output.stderr.is_empty());
    assert_eq!(String::from_utf8(output.stdout).unwrap(), markdown);
}

#[test]
fn json_is_one_line_of_the_same_facts() {
    let path = root().join("examples/records.spx");
    let (program, comments) = checked(&path);
    let json = doc::json(&program, &comments);
    assert!(json.ends_with('\n'));
    assert_eq!(json.matches('\n').count(), 1);
    let value: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert_eq!(value["schema"], doc::SCHEMA_V1);
    assert_eq!(value["module"], "examples.records");
    assert_eq!(value["revision"], graph::revision(&program));
    let model = doc::document(&program, &comments);
    let declarations = value["declarations"].as_array().unwrap();
    assert_eq!(declarations.len(), model.entries.len());
    for (declaration, entry) in declarations.iter().zip(&model.entries) {
        assert_eq!(declaration["id"], entry.id);
        assert_eq!(declaration["kind"], entry.kind);
        assert_eq!(declaration["signature"], entry.signature);
        assert_eq!(
            declaration["members"].as_array().unwrap().len(),
            entry.members.len()
        );
    }
    let markdown = doc::markdown(&program, &comments);
    for entry in &model.entries {
        assert!(markdown.contains(&format!("- Identity: `{}`", entry.id)));
        assert!(markdown.contains(&entry.signature));
    }

    for arguments in [
        &["examples/records.spx", "--json"][..],
        &["--json", "examples/records.spx"][..],
    ] {
        let output = cli(arguments);
        assert!(output.status.success(), "{arguments:?}");
        assert!(output.stderr.is_empty());
        assert_eq!(String::from_utf8(output.stdout).unwrap(), json);
    }
}

#[test]
fn leading_comments_become_descriptions() {
    let directory = fixture_dir();
    let path = directory.join("commented.spx");
    std::fs::write(&path, COMMENTED).unwrap();
    let (program, comments) = checked(&path);
    let model = doc::document(&program, &comments);
    let descriptions: BTreeMap<_, _> = model
        .entries
        .iter()
        .map(|entry| (entry.id.as_str(), entry.description.clone()))
        .collect();
    assert_eq!(
        descriptions["demo.counter"],
        vec!["A counter that only grows.", "Two lines of description."]
    );
    assert_eq!(descriptions["demo.counter.get"], vec!["Read the value."]);
    assert_eq!(descriptions["demo.main"], vec!["Entry point."]);
    let markdown = doc::markdown(&program, &comments);
    assert!(markdown.contains(
        "### `Counter`\n\nA counter that only grows.\nTwo lines of description.\n\n```spx\n"
    ));
    assert!(markdown.contains("## Methods\n\n### `get`\n\nRead the value.\n"));
    assert!(markdown.contains("- Owner: `demo.counter`\n"));
    assert!(markdown.contains("- Fields:\n  - `value: i64` — `demo.counter.value`\n"));
    std::fs::remove_dir_all(directory).unwrap();
}

/// Every documented identity of a graph-carried kind is a node of the module
/// graph with the same kind and persistence, every explicit graph declaration
/// of those kinds is documented, and both projections name one revision.
#[test]
fn documentation_and_graph_agree_on_every_example() {
    for path in examples() {
        let (program, comments) = checked(&path);
        let model = doc::document(&program, &comments);
        let graph_json = graph::to_json(&program).unwrap();
        let value: serde_json::Value = serde_json::from_str(&graph_json).unwrap();
        assert_eq!(value["revision"], model.revision, "{}", path.display());
        assert_eq!(value["module"], model.module, "{}", path.display());
        assert_eq!(
            value["permits"],
            serde_json::Value::Array(
                model
                    .permits
                    .iter()
                    .map(|permit| serde_json::Value::String(permit.clone()))
                    .collect()
            ),
            "{}",
            path.display()
        );

        let mut graph_nodes: BTreeMap<String, (String, bool)> = BTreeMap::new();
        let mut explicit: BTreeSet<String> = BTreeSet::new();
        let mapped_graph_kinds: BTreeSet<&str> = GRAPH_KINDS
            .iter()
            .map(|(_, graph_kind)| *graph_kind)
            .collect();
        for node in value["nodes"].as_array().unwrap() {
            let kind = node["kind"].as_str().unwrap();
            if !mapped_graph_kinds.contains(kind) {
                continue;
            }
            let id = node["id"].as_str().unwrap().to_owned();
            let persistent = node["persistent"].as_bool().unwrap();
            if node["identity_origin"] == "explicit" {
                explicit.insert(id.clone());
            }
            if let Some((previous_kind, previous_persistent)) =
                graph_nodes.insert(id.clone(), (kind.to_owned(), persistent))
            {
                assert_eq!(
                    (previous_kind, previous_persistent),
                    (kind.to_owned(), persistent),
                    "{id}"
                );
            }
        }

        let mut documented: BTreeSet<String> = BTreeSet::new();
        let mut check = |kind: &str, id: &str, persistent: bool| {
            let Some((_, graph_kind)) = GRAPH_KINDS.iter().find(|(doc_kind, _)| *doc_kind == kind)
            else {
                return;
            };
            if id.is_empty() {
                assert!(!persistent);
                return;
            }
            let node = graph_nodes.get(id).unwrap_or_else(|| {
                panic!("{}: `{id}` ({kind}) is not a graph node", path.display())
            });
            assert_eq!(node.0, *graph_kind, "{}: {id}", path.display());
            assert_eq!(node.1, persistent, "{}: {id}", path.display());
            documented.insert(id.to_owned());
        };
        for entry in &model.entries {
            check(entry.kind, &entry.id, entry.persistent);
            for member in &entry.members {
                check(member.kind, &member.id, member.persistent);
            }
        }
        let undocumented: Vec<_> = explicit.difference(&documented).collect();
        assert!(
            undocumented.is_empty(),
            "{}: {undocumented:?}",
            path.display()
        );
    }
}

#[test]
fn cli_fails_closed() {
    let directory = fixture_dir();
    let invalid = directory.join("invalid.spx");
    std::fs::write(
        &invalid,
        "module demo.invalid;\n\n@id(\"demo.main\")\nfn main() -> i64\n{\n    true\n}\n",
    )
    .unwrap();
    let output = cli(&[invalid.to_str().unwrap()]);
    assert_eq!(output.status.code(), Some(1));
    assert!(output.stdout.is_empty());
    assert!(String::from_utf8(output.stderr).unwrap().contains("SPX-"));

    let missing = cli(&[directory.join("missing.spx").to_str().unwrap()]);
    assert_eq!(missing.status.code(), Some(1));
    assert!(missing.stdout.is_empty());
    assert!(String::from_utf8(missing.stderr)
        .unwrap()
        .contains("SPX-I001"));

    for arguments in [
        &[][..],
        &["--json"][..],
        &["examples/effects.spx", "extra"][..],
        &["examples/effects.spx", "--unknown"][..],
        &["examples/effects.spx", "--json", "--json"][..],
    ] {
        let output = cli(arguments);
        assert_eq!(output.status.code(), Some(2), "{arguments:?}");
        assert!(output.stdout.is_empty(), "{arguments:?}");
        assert!(!output.stderr.is_empty(), "{arguments:?}");
    }
    std::fs::remove_dir_all(directory).unwrap();
}
