//! Native C11 `-O0`/`-O2` differential column (issue #292): compiles the
//! compiler-derived `semaprax.authenticated-native-moves-nested.v1` provider,
//! generated by `render_authenticated_nested_moves_provider` from real
//! checked HIR (never a hand-authored reimplementation of a checked body),
//! and drives it through the generated C11 calling consumer
//! (`semaprax::public_generic_consumer::c_calling::generate_authenticated_nested_moves_calling_consumer_v1`).
//!
//! **Same endpoint as every other column.** [`super`]'s interpreter/
//! Core-provider/Component columns bind the checked-in parity fixtures'
//! actual `provider.transform` endpoint, whose parameter is the nested
//! `Envelope<LeafPair>` (a record wrapping a record). This module binds the
//! identical retained `endpoint`/`descriptor` [`super::acquire`] already
//! derived for those columns -- passed in by the caller, never re-derived
//! from a separate fixture -- so all four columns execute the SAME checked
//! body over the SAME descriptor bytes.
//!
//! `authenticated-native-moves.v1`
//! (`src/codegen/native_emit/public_generic_bridge.rs::admit`) only ever
//! accepted a *flat* one-level owned-Bytes record body and still does: driving
//! it directly against this endpoint's own descriptor is still refused with
//! `SPX-B103` ("requires a flat Bytes movement body"), because its top-level
//! `input_facts().fields` is one record-typed `payload` field, not two Bytes
//! leaves. `authenticated-native-moves-nested.v1` is a distinct, separately
//! versioned physical profile (issue #292) that additionally admits a nested
//! owned record (to a bounded depth) through its own admission and C
//! field-access codegen, without changing `moves-v1`'s own frozen contract or
//! byte output for any program it already admitted -- see
//! `tests/public_generic_native_adapter_v1/authenticated_handoff/checked_nested_moves.rs`
//! for that regression pin plus a standalone compiled proof of the nested
//! profile.
//!
//! `checked_moves.rs` and its `caller_hostility::run` remain the read-only
//! reference this module's calling convention and `clang` invocation follow;
//! neither is imported (a deliberately isolated Cargo workspace cannot reach
//! the root crate's `tests/` binaries), so the compile-and-run helper below
//! is a fresh, self-contained reimplementation of that same pattern.

use std::{
    env,
    fmt::Write as _,
    fs,
    io::Write as _,
    path::PathBuf,
    process::{Command, Stdio},
    sync::atomic::{AtomicU64, Ordering},
};

use semaprax::hir::ResolvedProgram;
use semaprax::public_generic_abi::descriptor::verify::VerifiedPublicGenericDescriptor;
use semaprax::public_generic_abi::native::authenticated::render_authenticated_nested_moves_provider;
use semaprax::public_generic_consumer::c_calling::generate_authenticated_nested_moves_calling_consumer_v1;

use super::{HostResult, Outcome, failure};

const DRIVER_TEMPLATE: &str = include_str!("native/driver.c");
const OPT_LEVELS: [&str; 2] = ["-O0", "-O2"];

static UNIQUE: AtomicU64 = AtomicU64::new(0);

/// One compiled `-O0`/`-O2` pair of the compiler-derived native moves
/// provider for one checked endpoint, driven as a subprocess per call. Its
/// temporary directory (sources and binaries) is removed on drop.
pub(super) struct NativeSubject {
    dir: PathBuf,
    binaries: Vec<(&'static str, PathBuf)>,
    descriptor_bytes: Vec<u8>,
}

impl NativeSubject {
    /// The exact descriptor bytes the compiled native provider embeds --
    /// [`super::acquire`] asserts this equals the interpreter/Core/Component
    /// columns' own descriptor bytes, so all four columns are proven to
    /// execute the SAME checked endpoint, not merely four checked endpoints
    /// that happen to behave alike.
    pub(super) fn descriptor_bytes(&self) -> &[u8] {
        &self.descriptor_bytes
    }

    /// Run one checked call through the `-O0` or `-O2` binary (an entry of
    /// [`OPT_LEVELS`]) and decode its reported outcome.
    pub(super) fn call(&self, opt: &str, left: &[u8], right: &[u8]) -> HostResult<Outcome> {
        if left.len() > 65_536 || right.len() > 65_536 {
            return Err(failure("native probe input exceeds one bounded leaf"));
        }
        let binary = self
            .binaries
            .iter()
            .find(|(label, _)| *label == opt)
            .map(|(_, path)| path)
            .ok_or_else(|| failure(format!("no compiled native probe for {opt}")))?;
        let mut child = Command::new(binary)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|error| failure(format!("native probe {opt} failed to run: {error}")))?;
        let write_result = (|| -> std::io::Result<()> {
            let stdin = child.stdin.as_mut().expect("piped native probe stdin");
            for leaf in [left, right] {
                stdin.write_all(&(leaf.len() as u32).to_le_bytes())?;
                stdin.write_all(leaf)?;
            }
            Ok(())
        })();
        drop(child.stdin.take());
        if let Err(error) = write_result {
            let _ = child.kill();
            let _ = child.wait();
            return Err(failure(format!("native probe {opt} input failed: {error}")));
        }
        let output = child
            .wait_with_output()
            .map_err(|error| failure(format!("native probe {opt} failed to complete: {error}")))?;
        if !output.status.success() {
            return Err(failure(format!(
                "native probe {opt} exited with {:?}: {}",
                output.status.code(),
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        parse_outcome(&output.stdout)
    }
}

impl Drop for NativeSubject {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.dir);
    }
}

/// Render, generate and compile (both `-O0` and `-O2`) the nested-moves
/// native provider for the caller's own already-admitted `program`/
/// `source_revision`/`descriptor` -- the SAME retained endpoint
/// [`super::acquire`] derived once for the interpreter, Core-provider and
/// Component columns, never a separately re-checked or narrower fixture.
/// Never accepts a caller-selected body or bypasses
/// [`render_authenticated_nested_moves_provider`]'s own admission.
pub(super) fn build(
    program: &ResolvedProgram,
    source_revision: &str,
    descriptor: &VerifiedPublicGenericDescriptor,
) -> HostResult<NativeSubject> {
    let input = &descriptor.input_facts().owned_leaves;
    let result = &descriptor.result_facts().owned_leaves;
    let (Some(input_left), Some(input_right)) = (input.first(), input.get(1)) else {
        return Err(failure(
            "native parity subject needs exactly two input leaves",
        ));
    };
    let (Some(result_left), Some(result_right)) = (result.first(), result.get(1)) else {
        return Err(failure(
            "native parity subject needs exactly two result leaves",
        ));
    };

    let artifact = render_authenticated_nested_moves_provider(program, source_revision, descriptor)
        .map_err(|error| failure(format!("native nested-moves admission failed: {error:?}")))?;
    let descriptor_bytes = artifact.descriptor_bytes().to_vec();
    let consumer = generate_authenticated_nested_moves_calling_consumer_v1(descriptor, &artifact)
        .map_err(|error| {
        failure(format!(
            "native nested-moves consumer generation failed: {error:?}"
        ))
    })?;

    let id = UNIQUE.fetch_add(1, Ordering::Relaxed);
    let dir = env::temp_dir().join(format!("semaprax-r14-native-{}-{id}", std::process::id()));
    fs::create_dir_all(&dir).map_err(|error| failure(format!("native temp dir: {error}")))?;
    for (name, contents) in consumer.files() {
        fs::write(dir.join(name), contents)
            .map_err(|error| failure(format!("native temp file {name}: {error}")))?;
    }
    fs::write(dir.join("provider.c"), artifact.source())
        .map_err(|error| failure(format!("native provider.c: {error}")))?;
    fs::write(
        dir.join("driver.c"),
        driver_source(input_left, input_right, result_left, result_right),
    )
    .map_err(|error| failure(format!("native driver.c: {error}")))?;

    let clang = env::var_os("CLANG").unwrap_or_else(|| "clang".into());
    let mut binaries = Vec::with_capacity(OPT_LEVELS.len());
    for opt in OPT_LEVELS {
        let exe = dir.join(format!("probe{opt}{}", env::consts::EXE_SUFFIX));
        let compiled = Command::new(&clang)
            .args(["-std=c11", opt, "-Wall", "-Wextra", "-Werror"])
            .arg(dir.join("provider.c"))
            .arg(dir.join("driver.c"))
            .arg("-o")
            .arg(&exe)
            .output()
            .map_err(|error| failure(format!("clang unavailable for {opt}: {error}")))?;
        if !compiled.status.success() {
            return Err(failure(format!(
                "native provider compile ({opt}) failed: {}",
                String::from_utf8_lossy(&compiled.stderr)
            )));
        }
        binaries.push((opt, exe));
    }
    Ok(NativeSubject {
        dir,
        binaries,
        descriptor_bytes,
    })
}

fn field_macro(path: &str) -> String {
    let mut name = String::with_capacity(6 + path.len() * 2);
    name.push_str("field_");
    for byte in path.bytes() {
        write!(name, "{byte:02x}").unwrap();
    }
    name
}

fn driver_source(
    input_left: &str,
    input_right: &str,
    result_left: &str,
    result_right: &str,
) -> String {
    format!(
        "#define INPUT0 {}\n#define INPUT1 {}\n#define OUTPUT0 {}\n#define OUTPUT1 {}\n{}",
        field_macro(input_left),
        field_macro(input_right),
        field_macro(result_left),
        field_macro(result_right),
        DRIVER_TEMPLATE,
    )
}

fn decode_hex(text: &str) -> HostResult<Vec<u8>> {
    if !text.len().is_multiple_of(2) {
        return Err(failure("native probe hex leaf had odd length"));
    }
    let bytes = text.as_bytes();
    let mut out = Vec::with_capacity(bytes.len() / 2);
    for chunk in bytes.as_chunks::<2>().0 {
        let pair = std::str::from_utf8(chunk)
            .map_err(|error| failure(format!("native probe hex leaf malformed: {error}")))?;
        out.push(
            u8::from_str_radix(pair, 16)
                .map_err(|error| failure(format!("native probe hex leaf malformed: {error}")))?,
        );
    }
    Ok(out)
}

fn parse_outcome(stdout: &[u8]) -> HostResult<Outcome> {
    let text = String::from_utf8(stdout.to_vec())
        .map_err(|error| failure(format!("native probe stdout was not UTF-8: {error}")))?;
    let line = text
        .lines()
        .next()
        .ok_or_else(|| failure("native probe produced no output"))?;
    let mut parts = line.split(' ');
    match parts.next() {
        Some("OK") => {
            let first = parts
                .next()
                .ok_or_else(|| failure("native probe OK line missing first leaf"))?;
            let second = parts
                .next()
                .ok_or_else(|| failure("native probe OK line missing second leaf"))?;
            Ok(Outcome::Leaves(decode_hex(first)?, decode_hex(second)?))
        }
        Some("CONTRACT_VIOLATION") => Ok(Outcome::ContractViolation),
        Some("REFUSAL") => Ok(Outcome::ProviderRefusal),
        other => Err(failure(format!(
            "native probe produced an unrecognized outcome line: {other:?}"
        ))),
    }
}
