//! Native C11 `-O0`/`-O2` differential column (issue #292): compiles the
//! compiler-derived `semaprax.authenticated-native-moves.v1` provider,
//! generated by `render_authenticated_moves_provider` from real checked HIR
//! (never a hand-authored reimplementation of a checked body), and drives it
//! through the generated C11 calling consumer
//! (`semaprax::public_generic_consumer::c_calling::generate_authenticated_moves_calling_consumer_v1`).
//!
//! **Scope, stated once.** [`super`]'s interpreter/Core-provider/Component
//! columns bind the checked-in parity fixtures' actual `provider.transform`
//! endpoint, whose parameter is the nested `Envelope<LeafPair>` (a record
//! wrapping a record). The native `authenticated-native-moves.v1` profile
//! (`src/codegen/native_emit/public_generic_bridge.rs::admit`) only accepts a
//! *flat* one-level owned-Bytes record body -- confirmed empirically: driving
//! it directly against that endpoint's own descriptor is refused with
//! `SPX-B103` ("requires a flat Bytes movement body"), because its top-level
//! `input_facts().fields` is one record-typed `payload` field, not two Bytes
//! leaves. Widening that profile to admit nested records is a real compiler
//! change to `native_emit`'s admission and C field-access codegen together,
//! out of this bounded increment's scope. This module therefore checks the
//! SAME two behavior families against the SAME left/right byte vectors and
//! expected outcomes as the other three columns (swap of two owned-Bytes
//! leaves; a checked `requires false` contract failure) over a small inline
//! *flat* two-field record fixture the moves-v1 profile does admit, built
//! the same way (`semaprax::check` + `hir::resolve`, no checked-in Project)
//! as the read-only reference
//! `tests/public_generic_native_adapter_v1/authenticated_handoff/checked_moves.rs`.
//! It is real, compiled, executed native evidence for the claimed behavior,
//! not a claim of byte-identical descriptor/endpoint bytes with the other
//! three columns.
//!
//! `checked_moves.rs` and its `caller_hostility::run` are the read-only
//! reference this module's calling convention and `clang` invocation follow;
//! neither is imported (a deliberately isolated Cargo workspace cannot reach
//! the root crate's `tests/` binaries), so the compile-and-run helper below
//! is a fresh, self-contained reimplementation of that same pattern.

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::atomic::{AtomicU64, Ordering},
};

use semaprax::public_generic_abi::compiler_endpoint::derive_admitted_public_generic_endpoint_v1;
use semaprax::public_generic_abi::native::authenticated::render_authenticated_moves_provider;
use semaprax::public_generic_consumer::c_calling::generate_authenticated_moves_calling_consumer_v1;

use super::{HostResult, Outcome, failure};

/// The flat, moves-v1-admissible fixture: one owned-Bytes-only record. The
/// non-identity (swap) subject uses this body with no `requires`/`ensures`
/// clause; the requires-false subject inserts a literal `requires false`
/// before the same body (never reached, so its swap/identity choice does not
/// matter -- see [`super`]'s own `provider.transform` parity-failure fixture,
/// which is refused before body evaluation the same way).
const SOURCE: &str = r#"module native.parity;

@id("native.pair")
record Pair {
    @id("native.pair.left")
    left: Bytes,
    @id("native.pair.right")
    right: Bytes,
}

@id("native.transform")
fn transform(value: own Pair) -> Pair
{
    Pair { left: value.right, right: value.left }
}

@id("native.main")
fn main() -> i64 { 0 }
"#;
const TRANSFORM_HEADER: &str = "fn transform(value: own Pair) -> Pair\n{";
const EXPORT_ID: &str = "native.transform";

const DRIVER_TEMPLATE: &str = include_str!("native/driver.c");
const OPT_LEVELS: [&str; 2] = ["-O0", "-O2"];

static UNIQUE: AtomicU64 = AtomicU64::new(0);

/// One compiled `-O0`/`-O2` pair of the compiler-derived native moves
/// provider for one checked endpoint, driven as a subprocess per call. Its
/// temporary directory (sources and binaries) is removed on drop.
pub(super) struct NativeSubject {
    dir: PathBuf,
    binaries: Vec<(&'static str, PathBuf)>,
}

impl NativeSubject {
    /// Run one checked call through the `-O0` or `-O2` binary (an entry of
    /// [`OPT_LEVELS`]) and decode its reported outcome.
    pub(super) fn call(&self, opt: &str, left: &[u8], right: &[u8]) -> HostResult<Outcome> {
        let binary = self
            .binaries
            .iter()
            .find(|(label, _)| *label == opt)
            .map(|(_, path)| path)
            .ok_or_else(|| failure(format!("no compiled native probe for {opt}")))?;
        let output = Command::new(binary)
            .arg(hex(left))
            .arg(hex(right))
            .output()
            .map_err(|error| failure(format!("native probe {opt} failed to run: {error}")))?;
        if !output.status.success() {
            return Err(failure(format!(
                "native probe {opt} exited with {:?}: {}",
                output.status.code(),
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        parse_outcome(&output.stdout)
    }
}

impl Drop for NativeSubject {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.dir);
    }
}

/// Check, resolve, admit, render, generate and compile (both `-O0` and
/// `-O2`) the flat native moves fixture for one of the two behavior
/// families this module documents: `requires_false = false` is the
/// non-identity (swap) subject, `true` is the checked contract-failure
/// subject. Never accepts a caller-selected body or bypasses
/// [`render_authenticated_moves_provider`]'s own admission.
pub(super) fn build(requires_false: bool) -> HostResult<NativeSubject> {
    let source = if requires_false {
        if SOURCE.matches(TRANSFORM_HEADER).count() != 1 {
            return Err(failure("native parity fixture template drifted"));
        }
        SOURCE.replacen(
            TRANSFORM_HEADER,
            "fn transform(value: own Pair) -> Pair\n    requires false\n{",
            1,
        )
    } else {
        SOURCE.to_owned()
    };
    let parsed = semaprax::check(&source, Path::new("r14-native-parity.spx"))
        .map_err(|error| failure(format!("native parity fixture failed to check: {error:?}")))?;
    let revision = semaprax::format::canonical(&parsed);
    let program = semaprax::hir::resolve(&parsed).map_err(|error| {
        failure(format!(
            "native parity fixture failed to resolve: {error:?}"
        ))
    })?;
    let endpoint = derive_admitted_public_generic_endpoint_v1(&program, &revision, EXPORT_ID)
        .map_err(|error| {
            failure(format!(
                "native parity endpoint admission failed: {error:?}"
            ))
        })?;
    let descriptor = endpoint.descriptor();

    let input = &descriptor.input_facts().owned_leaves;
    let result = &descriptor.result_facts().owned_leaves;
    let (Some(input_left), Some(input_right)) = (input.first(), input.get(1)) else {
        return Err(failure(
            "native parity subject needs exactly two input leaves",
        ));
    };
    let (Some(result_left), Some(result_right)) = (result.first(), result.get(1)) else {
        return Err(failure(
            "native parity subject needs exactly two result leaves",
        ));
    };

    let artifact = render_authenticated_moves_provider(&program, &revision, descriptor)
        .map_err(|error| failure(format!("native moves admission failed: {error:?}")))?;
    let consumer = generate_authenticated_moves_calling_consumer_v1(descriptor, &artifact)
        .map_err(|error| {
            failure(format!(
                "native moves consumer generation failed: {error:?}"
            ))
        })?;

    let id = UNIQUE.fetch_add(1, Ordering::Relaxed);
    let dir = env::temp_dir().join(format!("semaprax-r14-native-{}-{id}", std::process::id()));
    fs::create_dir_all(&dir).map_err(|error| failure(format!("native temp dir: {error}")))?;
    for (name, contents) in consumer.files() {
        fs::write(dir.join(name), contents)
            .map_err(|error| failure(format!("native temp file {name}: {error}")))?;
    }
    fs::write(dir.join("provider.c"), artifact.source())
        .map_err(|error| failure(format!("native provider.c: {error}")))?;
    fs::write(
        dir.join("driver.c"),
        driver_source(input_left, input_right, result_left, result_right),
    )
    .map_err(|error| failure(format!("native driver.c: {error}")))?;

    let clang = env::var_os("CLANG").unwrap_or_else(|| "clang".into());
    let mut binaries = Vec::with_capacity(OPT_LEVELS.len());
    for opt in OPT_LEVELS {
        let exe = dir.join(format!("probe{opt}{}", env::consts::EXE_SUFFIX));
        let compiled = Command::new(&clang)
            .args(["-std=c11", opt, "-Wall", "-Wextra", "-Werror"])
            .arg(dir.join("provider.c"))
            .arg(dir.join("driver.c"))
            .arg("-o")
            .arg(&exe)
            .output()
            .map_err(|error| failure(format!("clang unavailable for {opt}: {error}")))?;
        if !compiled.status.success() {
            return Err(failure(format!(
                "native provider compile ({opt}) failed: {}",
                String::from_utf8_lossy(&compiled.stderr)
            )));
        }
        binaries.push((opt, exe));
    }
    Ok(NativeSubject { dir, binaries })
}

fn field_macro(path: &str) -> String {
    let mut name = String::with_capacity(6 + path.len() * 2);
    name.push_str("field_");
    for byte in path.bytes() {
        write!(name, "{byte:02x}").unwrap();
    }
    name
}

fn driver_source(
    input_left: &str,
    input_right: &str,
    result_left: &str,
    result_right: &str,
) -> String {
    format!(
        "#define INPUT0 {}\n#define INPUT1 {}\n#define OUTPUT0 {}\n#define OUTPUT1 {}\n{}",
        field_macro(input_left),
        field_macro(input_right),
        field_macro(result_left),
        field_macro(result_right),
        DRIVER_TEMPLATE,
    )
}

fn hex(bytes: &[u8]) -> String {
    let mut text = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(text, "{byte:02x}").unwrap();
    }
    text
}

fn decode_hex(text: &str) -> HostResult<Vec<u8>> {
    if text.len() % 2 != 0 {
        return Err(failure("native probe hex leaf had odd length"));
    }
    let bytes = text.as_bytes();
    let mut out = Vec::with_capacity(bytes.len() / 2);
    for chunk in bytes.chunks_exact(2) {
        let pair = std::str::from_utf8(chunk)
            .map_err(|error| failure(format!("native probe hex leaf malformed: {error}")))?;
        out.push(
            u8::from_str_radix(pair, 16)
                .map_err(|error| failure(format!("native probe hex leaf malformed: {error}")))?,
        );
    }
    Ok(out)
}

fn parse_outcome(stdout: &[u8]) -> HostResult<Outcome> {
    let text = String::from_utf8(stdout.to_vec())
        .map_err(|error| failure(format!("native probe stdout was not UTF-8: {error}")))?;
    let line = text
        .lines()
        .next()
        .ok_or_else(|| failure("native probe produced no output"))?;
    let mut parts = line.split(' ');
    match parts.next() {
        Some("OK") => {
            let first = parts
                .next()
                .ok_or_else(|| failure("native probe OK line missing first leaf"))?;
            let second = parts
                .next()
                .ok_or_else(|| failure("native probe OK line missing second leaf"))?;
            Ok(Outcome::Leaves(decode_hex(first)?, decode_hex(second)?))
        }
        Some("CONTRACT_VIOLATION") => Ok(Outcome::ContractViolation),
        Some("REFUSAL") => Ok(Outcome::ProviderRefusal),
        other => Err(failure(format!(
            "native probe produced an unrecognized outcome line: {other:?}"
        ))),
    }
}
