//! The deterministic string templates [`super::generate_cxx_calling_consumer`]
//! composes. Split from `cxx_calling.rs` itself only to keep that file's own
//! generator-contract logic short, mirroring
//! [`super::super::c_calling::render`]'s own split.
//!
//! Every function below states, in its own doc comment, which part of its
//! output is a **fixed template** (the RAII/move-only mechanics, the closed
//! `ErrorKind`/`Result<T>` vocabulary, the hostile-pairing and
//! failure-injection test bodies) and which part is **descriptor-derived**
//! (the `Input`/`Output` field lists and accessors, and the per-field
//! transform plumbing that has to scale with field count).
//!
//! Every generated identifier that must not collide is derived from
//! [`field_name`] — the same `field_<hex-identity>` scheme
//! [`super::super::c_calling`] and [`super::super::rust_calling`] use — so a
//! display-name collision or a C++ keyword can never reach a generated
//! identifier: the prefix `field_` followed only by lowercase hex digits is
//! never a C++ keyword and is injective in the field's declaration-identity
//! bytes, never its display name.

use std::fmt::Write as _;

use super::{field_name, RecordShape};

/// Generate `include/semaprax_public_generic_v1.hpp`: the move-only RAII
/// wrapper around the generated C11 calling consumer.
///
/// **Fixed template:** the include guard, the `#include` of the C11 header,
/// the namespace, `BytesView`, `to_owned`, the closed `ErrorKind`
/// vocabulary, `Error`, `Result<T>`, the `Provider`/`Output` class
/// mechanics (move/copy/destructor, `open`, `close`, `reset`), the
/// compile-time static assertions, and `detail::make_owned_bytes`.
/// **Descriptor-derived:** the `Input` struct's field list, `Output`'s
/// per-field accessor methods, and `Provider::transform`'s per-field
/// encode/free statements (one line per leaf, in descriptor order).
pub(super) fn wrapper_header(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(HEADER_PRELUDE);
    out.push_str(&input_struct(input));
    out.push('\n');
    out.push_str(&output_class(output));
    out.push('\n');
    out.push_str(PROVIDER_CLASS_AND_ASSERTIONS);
    out.push('\n');
    out.push_str(DETAIL_MAKE_OWNED_BYTES);
    out.push('\n');
    out.push_str(PROVIDER_OPEN_DEFINITIONS);
    out.push('\n');
    out.push_str(&provider_transform_definition(input));
    out.push_str(HEADER_TRAILER);
    out
}

const HEADER_PRELUDE: &str = r#"/*
 * Generated by semaprax::public_generic_consumer::cxx_calling.
 * Compiler-generated deterministic output; do not edit.
 *
 * A move-only C++17 RAII wrapper around the generated C11 calling consumer
 * (issue #158, spx_pg_calling_consumer.h/.c). This file WRAPS that C11
 * client: it never restates its codec, its lifecycle, or its pairing check,
 * and it never names a native ABI provider handle type (that stays entirely
 * inside spx_pg_calling_consumer.c, behind the opaque consumer handle).
 * Existing C and public profiles remain unchanged: this header calls only
 * the closed C11 surface spx_pg_calling_consumer.h already declares.
 *
 * Move-only is the crux, not decoration: Provider and Output below delete
 * their copy constructor/assignment, are noexcept move-constructible and
 * move-assignable, and release their sole owned handle at most once, in a
 * noexcept destructor, via a private idempotent reset()/free helper. See
 * docs/PUBLIC-GENERIC-CONSUMERS-V1.md's C++17 calling consumer section for
 * the exact zero-leak evidence and whose counters it uses.
 */
#ifndef SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP
#define SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP

#include "spx_pg_calling_consumer.h"

#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>

namespace semaprax::public_generic::v1 {

/* A non-owning, C++17-only view (deliberately not the C++20 span facility).
 * Valid only while the Output that produced it remains live and unmoved --
 * restated once here rather than on every accessor. */
struct BytesView {
    const std::uint8_t *data = nullptr;
    std::size_t size = 0;
};

/* An explicit, independent copy of a view's bytes. The returned vector
 * shares no storage with the Output the view came from and remains valid
 * after that Output is moved, released, or destroyed. */
inline std::vector<std::uint8_t> to_owned(const BytesView &view) {
    if (view.size == 0) {
        return {};
    }
    return std::vector<std::uint8_t>(view.data, view.data + view.size);
}

/* Closed error vocabulary. Every failure this wrapper can report maps to
 * exactly one of these -- restating spx_pg_calling_consumer.h's own closed
 * spx_pg_consumer_status vocabulary (see map_error_kind below) rather than
 * inventing an independent one; a new reason requires a new C11 status
 * first. AllocationFailure and NullArgument extend the illustrative set
 * this generator's owning issue sketched, so every non-OK C11 status has an
 * exact typed home. ReleaseFailed is reserved: the exposed C11 surface
 * (spx_pg_consumer_close returns void) offers no status this wrapper could
 * observe for a destructor-time release failure, only a secondary stderr
 * note printed by the C11 layer itself -- see Provider's destructor doc
 * comment below for how that is (not) surfaced here. */
enum class ErrorKind : std::uint32_t {
    DescriptorRejected,
    ProviderMismatch,
    CarrierRejected,
    CapacityExceeded,
    ExecutionFailed,
    ResultRejected,
    ReleaseFailed,
    AllocationFailure,
    NullArgument,
};

/* A closed, typed failure: the mapped ErrorKind plus the raw native
 * spx_pg_status_v1 an ExecutionFailed restates (0 for every other kind, or
 * for a native status this wrapper's own checks caught locally) -- restating
 * spx_pg_consumer_transform's own out_native_status parameter. Never a
 * string: no reason here is ever parsed from prose. */
class Error final {
public:
    Error(ErrorKind kind, int native_status) noexcept : kind_(kind), native_status_(native_status) {}

    ErrorKind kind() const noexcept { return kind_; }
    int native_status() const noexcept { return native_status_; }

private:
    ErrorKind kind_;
    int native_status_;
};

/* Restates spx_pg_calling_consumer.h's own closed spx_pg_consumer_status
 * vocabulary exhaustively: every non-OK status maps to exactly one
 * ErrorKind. SPX_PG_CONSUMER_OK and any status this header does not define
 * fall back to ExecutionFailed rather than undefined behavior -- a status
 * this consumer's own header does not declare cannot occur from a real
 * call, but this function never assumes that by omission. */
inline ErrorKind map_error_kind(::spx_pg_consumer_status status) noexcept {
    switch (status) {
    case SPX_PG_CONSUMER_DESCRIPTOR_REJECTED:
        return ErrorKind::DescriptorRejected;
    case SPX_PG_CONSUMER_PROVIDER_MISMATCH:
        return ErrorKind::ProviderMismatch;
    case SPX_PG_CONSUMER_CARRIER_REJECTED:
        return ErrorKind::CarrierRejected;
    case SPX_PG_CONSUMER_CAPACITY_EXCEEDED:
        return ErrorKind::CapacityExceeded;
    case SPX_PG_CONSUMER_EXECUTION_FAILED:
        return ErrorKind::ExecutionFailed;
    case SPX_PG_CONSUMER_RESULT_REJECTED:
        return ErrorKind::ResultRejected;
    case SPX_PG_CONSUMER_ALLOCATION_FAILURE:
        return ErrorKind::AllocationFailure;
    case SPX_PG_CONSUMER_NULL_ARGUMENT:
        return ErrorKind::NullArgument;
    case SPX_PG_CONSUMER_OK:
    default:
        return ErrorKind::ExecutionFailed;
    }
}

/* C++17 has no std::expected. A closed, typed, exception-free result: either
 * a value of T or an Error, never both, never neither. No public method
 * exposes the discriminant as anything but has_value()/operator bool -- a
 * caller cannot forge a value out of an error state or vice versa. */
template <typename T>
class Result final {
public:
    Result(T value) noexcept : storage_(std::move(value)) {}
    Result(Error error) noexcept : storage_(std::move(error)) {}

    bool has_value() const noexcept { return std::holds_alternative<T>(storage_); }
    explicit operator bool() const noexcept { return has_value(); }

    T &value() & noexcept { return std::get<T>(storage_); }
    const T &value() const & noexcept { return std::get<T>(storage_); }
    T &&value() && noexcept { return std::get<T>(std::move(storage_)); }

    const Error &error() const noexcept { return std::get<Error>(storage_); }

private:
    std::variant<T, Error> storage_;
};

"#;

fn input_struct(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "/* Concrete owned input record: one std::vector<std::uint8_t> leaf per\n\
         \x20* descriptor field, in descriptor order. Consumed by value/rvalue by\n\
         \x20* Provider::transform so the semantic ownership transfer is visible at\n\
         \x20* the call site -- an ordinary aggregate, never RAII-critical on its\n\
         \x20* own (its vectors own their own bytes independently of the native\n\
         \x20* provider until transform() converts them). */\n",
    );
    out.push_str("struct Input {\n");
    for field in &input.fields {
        let _ = writeln!(out, "    // Field identity: {:?}", field.identity);
        let _ = writeln!(out, "    std::vector<std::uint8_t> {};", field_name(field));
    }
    out.push_str("};\n");
    out
}

fn output_class(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "/* Move-only RAII owner of one generated C11 spx_pg_output value. Every\n\
         \x20* leaf is released at most once, via spx_pg_output_free -- idempotent\n\
         \x20* and safe on an already-zeroed value, so a moved-from Output's\n\
         \x20* destructor is a safe no-op. Raw handle access stays private; no\n\
         \x20* public constructor accepts an arbitrary spx_pg_output. A returned\n\
         \x20* BytesView is valid only while this Output remains live and\n\
         \x20* unmoved. */\n",
    );
    out.push_str("class Output final {\n");
    out.push_str("public:\n");
    out.push_str("    Output() noexcept : raw_{} {}\n");
    out.push_str("    Output(Output &&other) noexcept : raw_(other.raw_) { other.raw_ = ::spx_pg_output{}; }\n");
    out.push_str("    Output &operator=(Output &&other) noexcept {\n");
    out.push_str("        if (this != &other) {\n");
    out.push_str("            ::spx_pg_output_free(&raw_);\n");
    out.push_str("            raw_ = other.raw_;\n");
    out.push_str("            other.raw_ = ::spx_pg_output{};\n");
    out.push_str("        }\n");
    out.push_str("        return *this;\n");
    out.push_str("    }\n");
    out.push_str("    Output(const Output &) = delete;\n");
    out.push_str("    Output &operator=(const Output &) = delete;\n");
    out.push_str("    ~Output() noexcept { ::spx_pg_output_free(&raw_); }\n");
    out.push('\n');
    for field in &output.fields {
        let name = field_name(field);
        let _ = writeln!(out, "    // Field identity: {:?}", field.identity);
        let _ = writeln!(
            out,
            "    BytesView {name}() const noexcept {{ return BytesView{{raw_.{name}.data, raw_.{name}.len}}; }}"
        );
    }
    out.push('\n');
    out.push_str("private:\n");
    out.push_str("    friend class Provider;\n");
    out.push_str("    explicit Output(::spx_pg_output raw) noexcept : raw_(raw) {}\n\n");
    out.push_str("    ::spx_pg_output raw_;\n");
    out.push_str("};\n");
    out
}

const PROVIDER_CLASS_AND_ASSERTIONS: &str = r#"/* Move-only RAII owner of one opened spx_pg_calling_consumer handle.
 * Provider::open independently invokes the generated C11 client's exact
 * pairing checks -- this wrapper offers no constructor that skips them, and
 * no public constructor accepts an arbitrary raw handle. */
class Provider final {
public:
    Provider() noexcept = default;
    Provider(Provider &&other) noexcept : raw_(other.raw_) { other.raw_ = nullptr; }
    Provider &operator=(Provider &&other) noexcept {
        if (this != &other) {
            reset();
            raw_ = other.raw_;
            other.raw_ = nullptr;
        }
        return *this;
    }
    Provider(const Provider &) = delete;
    Provider &operator=(const Provider &) = delete;
    ~Provider() noexcept { reset(); }

    /* Verifies descriptor_bytes/provider_binding_bytes against this
     * package's own embedded trusted values via the generated C11 client's
     * spx_pg_consumer_open -- the same independent pairing check the C11
     * harness itself exercises, never a C++-side shortcut around it. */
    static Result<Provider> open(const std::uint8_t *descriptor_bytes, std::size_t descriptor_len,
                                  const std::uint8_t *provider_binding_bytes,
                                  std::size_t provider_binding_len) noexcept;
    /* Convenience overload: opens against this package's own embedded
     * trusted descriptor/binding bytes. */
    static Result<Provider> open() noexcept;

    /* Consumes `input` by value. A default-constructed or moved-from
     * Provider safely returns ErrorKind::NullArgument without touching
     * `input`'s vectors at all (they are destroyed normally when `input`
     * goes out of scope) -- this call never hands a native call a consumer
     * it knows is not open. */
    Result<Output> transform(Input input) noexcept;

    bool valid() const noexcept { return raw_ != nullptr; }

    /* Releases the owned handle now, idempotently. A caller may close
     * explicitly and still let the destructor run afterward: reset() is
     * safe to call any number of times. A destructor-time release failure
     * (there is currently no such observable case: the exposed C11 surface
     * only ever prints a secondary stderr note, matching
     * spx_pg_calling_consumer.c's own SPX_PG_CCC_SECONDARY_RELEASE_NOTE, and
     * never returns a status this wrapper could surface as
     * ErrorKind::ReleaseFailed) never changes an already-settled primary
     * outcome and never throws. */
    void close() noexcept { reset(); }

private:
    explicit Provider(::spx_pg_calling_consumer *raw) noexcept : raw_(raw) {}

    /* Idempotent: a null raw_ is always a safe no-op, matching
     * spx_pg_consumer_close's own "closing an already-null provider is a
     * no-op success." */
    void reset() noexcept {
        if (raw_ != nullptr) {
            ::spx_pg_consumer_close(&raw_);
        }
    }

    ::spx_pg_calling_consumer *raw_ = nullptr;
};

static_assert(!std::is_copy_constructible_v<Provider>);
static_assert(!std::is_copy_assignable_v<Provider>);
static_assert(std::is_nothrow_move_constructible_v<Provider>);
static_assert(std::is_nothrow_move_assignable_v<Provider>);

static_assert(!std::is_copy_constructible_v<Output>);
static_assert(!std::is_copy_assignable_v<Output>);
static_assert(std::is_nothrow_move_constructible_v<Output>);
static_assert(std::is_nothrow_move_assignable_v<Output>);
"#;

const DETAIL_MAKE_OWNED_BYTES: &str = r#"namespace detail {

/* Copies `value` into a freshly malloc'd spx_pg_owned_bytes leaf -- the
 * generated C11 consumer takes ownership of exactly this allocation once
 * handed to spx_pg_consumer_transform, and frees it internally regardless
 * of outcome (see spx_pg_calling_consumer.h's own transform doc comment).
 * Returns false, leaving `out` untouched, on allocation failure; the caller
 * must not treat `out` as initialized in that case. */
inline bool make_owned_bytes(const std::vector<std::uint8_t> &value, ::spx_pg_owned_bytes &out) noexcept {
    if (value.empty()) {
        out.data = nullptr;
        out.len = 0;
        return true;
    }
    auto *buffer = static_cast<std::uint8_t *>(std::malloc(value.size()));
    if (buffer == nullptr) {
        return false;
    }
    std::memcpy(buffer, value.data(), value.size());
    out.data = buffer;
    out.len = value.size();
    return true;
}

} // namespace detail
"#;

const PROVIDER_OPEN_DEFINITIONS: &str = r#"inline Result<Provider> Provider::open(const std::uint8_t *descriptor_bytes, std::size_t descriptor_len,
                                        const std::uint8_t *provider_binding_bytes,
                                        std::size_t provider_binding_len) noexcept {
    ::spx_pg_calling_consumer *raw = nullptr;
    ::spx_pg_consumer_status status = ::spx_pg_consumer_open(descriptor_bytes, descriptor_len,
                                                              provider_binding_bytes, provider_binding_len, &raw);
    if (status != SPX_PG_CONSUMER_OK) {
        return Error(map_error_kind(status), 0);
    }
    return Provider(raw);
}

inline Result<Provider> Provider::open() noexcept {
    return open(::spx_pg_trusted_descriptor_bytes, ::spx_pg_trusted_descriptor_len,
                ::spx_pg_trusted_binding_bytes, ::spx_pg_trusted_binding_len);
}
"#;

/// `Provider::transform`'s out-of-line definition. **Fixed template:** the
/// null-handle guard, the zero-initialized `c_input`/`c_output`, the call
/// into `spx_pg_consumer_transform`, and the success/failure wrapping.
/// **Descriptor-derived:** the field-by-field `make_owned_bytes` staging
/// calls and their matching frees on an allocation failure -- one line per
/// leaf, in descriptor order, restating
/// [`super::super::c_calling::render::encode_input_fn`]'s own per-field
/// scaling for this generator's own conversion step.
fn provider_transform_definition(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "inline Result<Output> Provider::transform(Input input) noexcept {\n\
         \x20   if (raw_ == nullptr) {\n\
         \x20       return Error(ErrorKind::NullArgument, 0);\n\
         \x20   }\n\
         \x20   ::spx_pg_input c_input{};\n\
         \x20   bool prepared = true;\n",
    );
    for field in &input.fields {
        let name = field_name(field);
        let _ = writeln!(
            out,
            "    prepared = prepared && detail::make_owned_bytes(input.{name}, c_input.{name});"
        );
    }
    out.push_str("    if (!prepared) {\n");
    for field in &input.fields {
        let _ = writeln!(
            out,
            "        ::spx_pg_owned_bytes_free(&c_input.{});",
            field_name(field)
        );
    }
    out.push_str(
        "        return Error(ErrorKind::AllocationFailure, 0);\n\
         \x20   }\n\
         \n\
         \x20   ::spx_pg_output c_output{};\n\
         \x20   int native_status = 0;\n\
         \x20   ::spx_pg_consumer_status status =\n\
         \x20       ::spx_pg_consumer_transform(raw_, &c_input, &c_output, &native_status);\n\
         \x20   if (status != SPX_PG_CONSUMER_OK) {\n\
         \x20       ::spx_pg_output_free(&c_output);\n\
         \x20       return Error(map_error_kind(status), native_status);\n\
         \x20   }\n\
         \x20   return Output(c_output);\n\
         }\n",
    );
    out
}

const HEADER_TRAILER: &str = r#"
} // namespace semaprax::public_generic::v1

#endif // SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP
"#;

/// Generate `test/round_trip.cpp`: a real, executable test driver proving
/// the RAII/move-only contract, not a mere compile check.
///
/// **Fixed template:** the `REQUIRE` macro, `bytes_from`/`assert_reversed_field`
/// helpers, the restated compile-time static assertions, the success round
/// trip and every move/self-move/moved-from/explicit-close/early-return
/// test, the hostile-pairing tests, the full ordinal `0..=13`
/// failure-injection matrix, and `main`. **Descriptor-derived:** the sample
/// input builder, the per-field `assert_reversed` comparisons, and which
/// field the per-leaf-bound tests target (the first one, matching
/// [`super::super::c_calling::render::round_trip_c`]'s own convention).
pub(super) fn round_trip_cpp(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(ROUND_TRIP_PRELUDE);
    out.push_str(&sample_input_fn(input));
    out.push('\n');
    out.push_str(&assert_reversed_fn(input, output));
    out.push('\n');
    out.push_str(&first_leaf_fn(output));
    out.push('\n');
    out.push_str(&zero_bytes_input_fn(input));
    out.push('\n');
    out.push_str(ROUND_TRIP_BODY);
    out.push('\n');
    out.push_str(&per_leaf_bound_tests_fn(input, output));
    out.push('\n');
    out.push_str(&main_fn());
    out
}

const ROUND_TRIP_PRELUDE: &str = r#"/*
 * Generated by semaprax::public_generic_consumer::cxx_calling.
 * Compiler-generated deterministic output; do not edit.
 *
 * Real, executed evidence for issue #159: opens the real native provider
 * through the generated C++17 wrapper (which itself wraps the generated
 * C11 calling consumer from issue #158), transfers one owned input record
 * exactly once, decodes an independently validated result, and proves the
 * move-only RAII contract -- deleted copy operations, nothrow move,
 * exactly-once release, self-move safety, move-assign-over-live cleanup,
 * moved-from destruction, explicit close then destructor, and early
 * return -- using the native provider's OWN test-only counters
 * (spx_pg_consumer_test_live_allocations/_live_handles, reached only
 * through the wrapped C11 consumer's own accessors), exactly like
 * tests/public_generic_native_adapter_v1/c_calling_consumer.rs's own
 * generated round_trip.c for the same provider.
 */
#include "../include/semaprax_public_generic_v1.hpp"

#include <cstdio>
#include <cstdlib>
#include <type_traits>
#include <utility>
#include <vector>

using namespace semaprax::public_generic::v1;

#define MAX_BYTES_PER_LEAF (64u * 1024u)

static void spx_pg_cxx_require(bool condition, const char *message, unsigned line) {
    if (!condition) {
        std::fprintf(stderr, "round_trip.cpp line %u: %s\n", line, message);
        std::exit(1);
    }
}
#define REQUIRE(condition) spx_pg_cxx_require((condition), #condition, __LINE__)

/* Restates the header's own static assertions here too: RAII correctness is
 * never inferred merely because a round trip succeeds below. */
static_assert(!std::is_copy_constructible_v<Provider>);
static_assert(!std::is_copy_assignable_v<Provider>);
static_assert(std::is_nothrow_move_constructible_v<Provider>);
static_assert(std::is_nothrow_move_assignable_v<Provider>);
static_assert(!std::is_copy_constructible_v<Output>);
static_assert(!std::is_copy_assignable_v<Output>);
static_assert(std::is_nothrow_move_constructible_v<Output>);
static_assert(std::is_nothrow_move_assignable_v<Output>);

static std::vector<std::uint8_t> bytes_from(const char *text) {
    std::vector<std::uint8_t> result;
    for (const char *cursor = text; *cursor != '\0'; ++cursor) {
        result.push_back(static_cast<std::uint8_t>(*cursor));
    }
    return result;
}

static void assert_reversed_field(const BytesView &actual, const std::vector<std::uint8_t> &original) {
    REQUIRE(actual.size == original.size());
    for (std::size_t index = 0; index < actual.size; ++index) {
        REQUIRE(actual.data[index] == original[original.size() - 1 - index]);
    }
}
"#;

fn sample_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("\nstatic Input sample_input() {\n");
    out.push_str("    Input input;\n");
    for (index, field) in input.fields.iter().enumerate() {
        let _ = writeln!(
            out,
            "    input.{} = bytes_from(\"sample-{index}\");",
            field_name(field)
        );
    }
    out.push_str("    return input;\n");
    out.push_str("}\n");
    out
}

fn assert_reversed_fn(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("static void assert_reversed(const Output &output, const Input &original) {\n");
    for (in_field, out_field) in input.fields.iter().zip(output.fields.iter()) {
        let _ = writeln!(
            out,
            "    assert_reversed_field(output.{}(), original.{});",
            field_name(out_field),
            field_name(in_field)
        );
    }
    out.push_str("}\n");
    out
}

/// `first_leaf`: the one field every fixed-template test that needs "some
/// field, any field" probes — matching this generator's own
/// per-leaf-bound-test convention of always targeting `output.fields[0]`.
fn first_leaf_fn(output: &RecordShape) -> String {
    format!(
        "static BytesView first_leaf(const Output &output) {{\n    return output.{}();\n}}\n",
        field_name(&output.fields[0])
    )
}

/// `zero_bytes_input`: alternates an empty leaf and an embedded-zero-byte
/// leaf across descriptor order, so the fixed
/// `test_zero_length_and_embedded_zero_bytes_round_trip` body never has to
/// name a field directly. With only one field, only the zero-length case is
/// exercised by this helper; the per-leaf-bound tests below independently
/// cover a large single-field payload.
fn zero_bytes_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("static Input zero_bytes_input() {\n    Input input;\n");
    for (index, field) in input.fields.iter().enumerate() {
        let name = field_name(field);
        if index % 2 == 0 {
            let _ = writeln!(out, "    input.{name} = {{}}; // zero-length leaf");
        } else {
            let _ = writeln!(
                out,
                "    input.{name} = std::vector<std::uint8_t>{{0x00, 0x41, 0x00, 0x42, 0x00}}; // embedded-zero-byte leaf"
            );
        }
    }
    out.push_str("    return input;\n}\n");
    out
}

const ROUND_TRIP_BODY: &str = r#"static void test_success_round_trip() {
    auto opened = Provider::open();
    REQUIRE(opened.has_value());
    Provider provider = std::move(opened).value();
    REQUIRE(provider.valid());

    Input original = sample_input();
    Input to_send = sample_input();
    auto result = provider.transform(std::move(to_send));
    REQUIRE(result.has_value());
    assert_reversed(result.value(), original);

    provider.close();
    REQUIRE(!provider.valid());
    REQUIRE(::spx_pg_consumer_test_live_allocations() == 0);
}

/* "Provider::open must invoke the generated C client's exact pairing
 * checks. C++ must not offer a constructor that skips them." */
static void test_open_rejects_a_mutated_descriptor_before_any_native_allocation() {
    std::vector<std::uint8_t> mutated(::spx_pg_trusted_descriptor_bytes,
                                       ::spx_pg_trusted_descriptor_bytes + ::spx_pg_trusted_descriptor_len);
    if (!mutated.empty()) {
        mutated[0] = static_cast<std::uint8_t>(mutated[0] ^ 0xffu);
    }
    std::size_t allocations_before = ::spx_pg_consumer_test_live_allocations();
    auto opened = Provider::open(mutated.data(), mutated.size(), ::spx_pg_trusted_binding_bytes,
                                  ::spx_pg_trusted_binding_len);
    REQUIRE(!opened.has_value());
    REQUIRE(opened.error().kind() == ErrorKind::DescriptorRejected);
    REQUIRE(::spx_pg_consumer_test_live_allocations() == allocations_before);
}

static void test_open_rejects_a_mutated_binding_before_any_native_allocation() {
    REQUIRE(::spx_pg_trusted_binding_len > 0);
    std::vector<std::uint8_t> mutated(::spx_pg_trusted_binding_bytes,
                                       ::spx_pg_trusted_binding_bytes + ::spx_pg_trusted_binding_len);
    mutated.back() = static_cast<std::uint8_t>(mutated.back() ^ 0xffu);
    std::size_t allocations_before = ::spx_pg_consumer_test_live_allocations();
    auto opened =
        Provider::open(::spx_pg_trusted_descriptor_bytes, ::spx_pg_trusted_descriptor_len, mutated.data(),
                        mutated.size());
    REQUIRE(!opened.has_value());
    REQUIRE(opened.error().kind() == ErrorKind::ProviderMismatch);
    REQUIRE(::spx_pg_consumer_test_live_allocations() == allocations_before);
}

/* A well-formed binding paired against a well-formed but DIFFERENT
 * descriptor must still fail -- "a valid provider for another descriptor
 * must fail, even when the concrete C++ type names/display names are the
 * same." */
static void test_open_rejects_a_valid_binding_that_names_a_different_descriptor() {
    static const char suffix[] = "-a-different-but-well-formed-descriptor";
    std::vector<std::uint8_t> different(::spx_pg_trusted_descriptor_bytes,
                                         ::spx_pg_trusted_descriptor_bytes + ::spx_pg_trusted_descriptor_len);
    different.insert(different.end(), suffix, suffix + (sizeof(suffix) - 1));
    auto opened = Provider::open(different.data(), different.size(), ::spx_pg_trusted_binding_bytes,
                                  ::spx_pg_trusted_binding_len);
    REQUIRE(!opened.has_value());
    REQUIRE(opened.error().kind() == ErrorKind::DescriptorRejected);
}

static void test_move_provider() {
    auto opened = Provider::open();
    REQUIRE(opened.has_value());
    Provider p1 = std::move(opened).value();
    Provider p2 = std::move(p1);
    REQUIRE(!p1.valid());
    REQUIRE(p2.valid());
    auto result = p2.transform(sample_input());
    REQUIRE(result.has_value());
}

static void test_move_output() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto result = provider.transform(sample_input());
    REQUIRE(result.has_value());
    Output out1 = std::move(result).value();
    Output out2 = std::move(out1);
    Input original = sample_input();
    assert_reversed(out2, original);
}

/* "Move assignment releases any currently owned handle before taking the
 * new one" -- proven with the native provider's own allocation counter, not
 * this wrapper's own bookkeeping. */
static void test_move_assign_over_live_output() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto r1 = provider.transform(sample_input());
    auto r2 = provider.transform(sample_input());
    REQUIRE(r1.has_value() && r2.has_value());
    Output a = std::move(r1).value();
    Output b = std::move(r2).value();
    std::size_t before = ::spx_pg_consumer_test_live_allocations();
    a = std::move(b);
    /* `a`'s original leaves were released by the move-assign, `b` is now a
     * safe, empty, moved-from Output: net live allocations must not have
     * grown, and `a` must now carry `b`'s (still correct) content. */
    REQUIRE(::spx_pg_consumer_test_live_allocations() <= before);
    Input original = sample_input();
    assert_reversed(a, original);
}

/* A moved-from Provider destructs safely: no double release, no crash. */
static void test_moved_from_provider_destructs_cleanly() {
    auto opened = Provider::open();
    Provider p1 = std::move(opened).value();
    {
        Provider p2 = std::move(p1);
        (void)p2;
    }
    /* p1 (moved-from, raw_ == nullptr) destructs here too. */
}

/* A moved-from Output destructs safely and releases nothing (there is
 * nothing left to release): the wrapped leaves already transferred to the
 * move target. */
static void test_moved_from_output_releases_nothing_and_destructs_cleanly() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto result = provider.transform(sample_input());
    REQUIRE(result.has_value());
    Output out1 = std::move(result).value();
    std::size_t before = ::spx_pg_consumer_test_live_allocations();
    {
        Output out2 = std::move(out1);
        (void)out2;
    }
    /* out2 released the real leaves; nothing changes when out1 (moved-from)
     * destructs next. */
    REQUIRE(::spx_pg_consumer_test_live_allocations() == before);
}

/* Self-move-assignment must be safe. The indirection through a pointer
 * alias defeats -Wself-move (which only pattern-matches the literal
 * syntactic form `x = std::move(x)`); this is a genuine runtime self-move
 * assignment, not a syntactic no-op the compiler elided. */
static void test_self_move_provider_is_safe() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    Provider *alias = &provider;
    *alias = std::move(*alias);
    REQUIRE(provider.valid());
    auto result = provider.transform(sample_input());
    REQUIRE(result.has_value());
}

static void test_self_move_output_is_safe() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto result = provider.transform(sample_input());
    REQUIRE(result.has_value());
    Output out = std::move(result).value();
    Output *alias = &out;
    *alias = std::move(*alias);
    Input original = sample_input();
    assert_reversed(out, original);
}

static void test_explicit_close_then_destructor_is_safe() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    provider.close();
    REQUIRE(!provider.valid());
    /* provider's destructor at end of scope must be a safe no-op: reset()
     * is idempotent. */
}

static Result<Output> early_return_after_result_acquisition(Provider &provider) {
    auto result = provider.transform(sample_input());
    if (!result.has_value()) {
        return result.error();
    }
    /* Early return with a live Output already constructed: its RAII
     * destructor must still run correctly along every path out of this
     * function. */
    return std::move(result).value();
}

static void test_early_return_after_result_acquisition() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto result = early_return_after_result_acquisition(provider);
    REQUIRE(result.has_value());
    provider.close();
    REQUIRE(::spx_pg_consumer_test_live_allocations() == 0);
}

/* "container relocation": std::vector<Output> must be safe to grow past its
 * current capacity, which relocates every already-inserted element via its
 * nothrow move constructor. */
static void test_vector_of_outputs_relocates_safely() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    std::vector<Output> outputs;
    for (int i = 0; i < 8; ++i) {
        auto result = provider.transform(sample_input());
        REQUIRE(result.has_value());
        outputs.push_back(std::move(result).value());
    }
    Input original = sample_input();
    for (const Output &output : outputs) {
        assert_reversed(output, original);
    }
}

/* An explicit independent copy stays independent of the Output it was
 * copied from: mutating the copy never mutates (and is never mutated by)
 * the source. `first_leaf` is generated per shape below (the first field,
 * matching this generator's own per-leaf-bound convention). */
static void test_copied_output_bytes_remain_independent() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    auto result = provider.transform(sample_input());
    REQUIRE(result.has_value());
    Output output = std::move(result).value();
    std::vector<std::uint8_t> copy = to_owned(first_leaf(output));
    if (!copy.empty()) {
        copy[0] = static_cast<std::uint8_t>(copy[0] ^ 0xffu);
        REQUIRE(copy[0] != first_leaf(output).data[0]);
    }
}

/* Zero-length and embedded-zero-byte leaves are ordinary bytes to this
 * wrapper: std::vector<std::uint8_t> never treats a leaf as a C string.
 * `zero_bytes_input` is generated per shape below. */
static void test_zero_length_and_embedded_zero_bytes_round_trip() {
    auto opened = Provider::open();
    Provider provider = std::move(opened).value();
    Input input = zero_bytes_input();
    Input original = zero_bytes_input();
    auto result = provider.transform(std::move(input));
    REQUIRE(result.has_value());
    assert_reversed(result.value(), original);
}

/* Every logical trace ordinal 0..=13 (see spx_pg_v1.h / c_calling's own
 * matrix doc comment) settles as a failure with zero live native
 * allocations/handles afterward, exactly like
 * tests/public_generic_native_adapter_v1/c_calling_consumer.rs's own
 * matrix for the same provider -- proven through the wrapped C11 consumer's
 * own test-only accessors, never this wrapper's own bookkeeping. Ordinals
 * 0..=4 fire inside input preparation, 5..=13 fire inside the call itself,
 * so this single loop also stands in for "failure after input
 * preparation," "failure after provider transfer," and "failure during
 * result construction." */
static void test_failure_injection_matrix_settles_every_ordinal_with_zero_live_resources() {
    for (std::uint32_t ordinal = 0; ordinal <= 13; ++ordinal) {
        auto opened = Provider::open();
        REQUIRE(opened.has_value());
        Provider provider = std::move(opened).value();
        ::spx_pg_consumer_test_inject_failure(ordinal);
        auto result = provider.transform(sample_input());
        REQUIRE(!result.has_value());
        ::spx_pg_consumer_test_clear_failure_injection();
        provider.close();
        REQUIRE(::spx_pg_consumer_test_live_allocations() == 0);
    }
}
"#;

fn per_leaf_bound_tests_fn(input: &RecordShape, output: &RecordShape) -> String {
    let first_input_field = field_name(&input.fields[0]);
    let first_output_field = field_name(&output.fields[0]);
    let mut out = String::new();
    out.push_str("static void test_exactly_the_per_leaf_byte_bound_is_accepted() {\n");
    out.push_str(
        "    auto opened = Provider::open();\n\
         \x20   REQUIRE(opened.has_value());\n\
         \x20   Provider provider = std::move(opened).value();\n\
         \x20   Input input;\n",
    );
    let _ = writeln!(
        out,
        "    input.{first_input_field}.assign(MAX_BYTES_PER_LEAF, 0x5au);"
    );
    out.push_str(
        "    auto result = provider.transform(std::move(input));\n\
         \x20   REQUIRE(result.has_value());\n",
    );
    let _ = writeln!(
        out,
        "    REQUIRE(result.value().{first_output_field}().size == MAX_BYTES_PER_LEAF);"
    );
    out.push_str(
        "    provider.close();\n\
         \x20   REQUIRE(::spx_pg_consumer_test_live_allocations() == 0);\n\
         }\n\n",
    );

    out.push_str("static void test_one_byte_over_the_per_leaf_bound_is_rejected_locally() {\n");
    out.push_str(
        "    auto opened = Provider::open();\n\
         \x20   REQUIRE(opened.has_value());\n\
         \x20   Provider provider = std::move(opened).value();\n\
         \x20   Input input;\n",
    );
    let _ = writeln!(
        out,
        "    input.{first_input_field}.assign(MAX_BYTES_PER_LEAF + 1, 0x5au);"
    );
    out.push_str(
        "    auto result = provider.transform(std::move(input));\n\
         \x20   REQUIRE(!result.has_value());\n\
         \x20   REQUIRE(result.error().kind() == ErrorKind::CapacityExceeded);\n\
         \x20   provider.close();\n\
         \x20   REQUIRE(::spx_pg_consumer_test_live_allocations() == 0);\n\
         }\n",
    );
    out
}

fn main_fn() -> String {
    r#"int main() {
    test_success_round_trip();
    test_open_rejects_a_mutated_descriptor_before_any_native_allocation();
    test_open_rejects_a_mutated_binding_before_any_native_allocation();
    test_open_rejects_a_valid_binding_that_names_a_different_descriptor();
    test_move_provider();
    test_move_output();
    test_move_assign_over_live_output();
    test_moved_from_provider_destructs_cleanly();
    test_moved_from_output_releases_nothing_and_destructs_cleanly();
    test_self_move_provider_is_safe();
    test_self_move_output_is_safe();
    test_explicit_close_then_destructor_is_safe();
    test_early_return_after_result_acquisition();
    test_vector_of_outputs_relocates_safely();
    test_copied_output_bytes_remain_independent();
    test_zero_length_and_embedded_zero_bytes_round_trip();
    test_exactly_the_per_leaf_byte_bound_is_accepted();
    test_one_byte_over_the_per_leaf_bound_is_rejected_locally();
    test_failure_injection_matrix_settles_every_ordinal_with_zero_live_resources();
    (void)std::puts("cxx-calling-consumer-settled");
    return 0;
}
"#
    .to_owned()
}
