use super::*;
use crate::public_generic_abi::carrier::{CarrierBindingV1, TargetProfile};

const DESCRIPTOR_BYTES: &[u8] = b"fixture-public-generic-descriptor-bytes-issue-159";

fn binding() -> NativeProviderBindingV1 {
    NativeProviderBindingV1::new(
        CarrierBindingV1::new(
            "sha256:5555555555555555555555555555555555555555555555555555555555555555",
            TargetProfile::NativeC11,
            "runtime:native-c11-fixture-issue-159",
        ),
        "sha256:6666666666666666666666666666666666666666666666666666666666666666",
        "spx_pg_endpoint_reverse_bytes_v1",
        "semaprax-0.4.1",
    )
}

fn shapes() -> (RecordShape, RecordShape) {
    let input = RecordShape::new(vec![
        OwnedByteField::new("cxx_calling.head"),
        OwnedByteField::new("cxx_calling.tail"),
    ]);
    let output = RecordShape::new(vec![
        OwnedByteField::new("cxx_calling.head"),
        OwnedByteField::new("cxx_calling.tail"),
    ]);
    (input, output)
}

fn generate() -> CallingConsumer {
    let (input, output) = shapes();
    generate_cxx_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output)
        .expect("a well-formed shape must generate")
}

#[test]
fn regeneration_is_byte_identical() {
    let first = generate();
    let second = generate();
    assert_eq!(first.files(), second.files());
}

#[test]
fn emits_the_expected_file_set_in_a_stable_order() {
    let consumer = generate();
    let names: Vec<&str> = consumer
        .files()
        .iter()
        .map(|(name, _)| name.as_str())
        .collect();
    assert_eq!(
        names,
        vec![
            "spx_pg_v1.h",
            "spx_pg_calling_consumer.h",
            "spx_pg_calling_consumer.c",
            "round_trip.c",
            WRAPPER_HEADER_FILE_NAME,
            ROUND_TRIP_FILE_NAME,
        ]
    );
}

#[test]
fn every_file_is_lf_only_and_ends_with_a_trailing_newline() {
    for (name, contents) in generate().files() {
        assert!(!contents.contains('\r'), "{name} contains a CR byte");
        assert!(
            contents.ends_with('\n'),
            "{name} does not end with a newline"
        );
    }
}

/// The generated C11 files this generator reuses must be byte-identical to
/// what [`c_calling::generate_c_calling_consumer`] alone would produce for
/// the same arguments -- this generator never restates or drifts from that
/// generator's own templates.
#[test]
fn reuses_the_c_calling_consumer_files_byte_for_byte() {
    let (input, output) = shapes();
    let expected =
        c_calling::generate_c_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output)
            .expect("a well-formed shape must generate");
    let actual = generate();
    for (name, contents) in expected.files() {
        let found = actual
            .files()
            .iter()
            .find(|(actual_name, _)| actual_name == name)
            .unwrap_or_else(|| panic!("{name} must also be generated by cxx_calling"));
        assert_eq!(&found.1, contents, "{name} must be byte-identical");
    }
}

/// "It does not create a second provider ABI": the C++ wrapper header must
/// never name a native ABI type either, and must depend on the generated
/// C11 consumer header rather than restate its declarations.
#[test]
fn wrapper_header_names_no_native_abi_type_and_includes_the_c11_consumer_header() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .expect("the wrapper header must be generated");
    for forbidden in ["spx_pg_provider_v1", "spx_pg_value_v1", "spx_pg_result_v1"] {
        assert!(
            !header.contains(forbidden),
            "the wrapper header must not mention {forbidden}"
        );
    }
    assert!(header.contains("#include \"spx_pg_calling_consumer.h\""));
}

/// Every owning wrapper type is move-only and noncopyable, proven at
/// compile time inside the generated header itself -- not merely asserted
/// by this generator's own test suite.
#[test]
fn wrapper_header_contains_the_required_static_assertions() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    for expected in [
        "static_assert(!std::is_copy_constructible_v<Provider>);",
        "static_assert(!std::is_copy_assignable_v<Provider>);",
        "static_assert(std::is_nothrow_move_constructible_v<Provider>);",
        "static_assert(std::is_nothrow_move_assignable_v<Provider>);",
        "static_assert(!std::is_copy_constructible_v<Output>);",
        "static_assert(!std::is_copy_assignable_v<Output>);",
        "static_assert(std::is_nothrow_move_constructible_v<Output>);",
        "static_assert(std::is_nothrow_move_assignable_v<Output>);",
    ] {
        assert!(header.contains(expected), "missing {expected}");
    }
}

/// "Delete copy construction/assignment for every owning handle."
#[test]
fn wrapper_header_deletes_copy_operations_for_provider_and_output() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    assert!(header.contains("Provider(const Provider &) = delete;"));
    assert!(header.contains("Provider &operator=(const Provider &) = delete;"));
    assert!(header.contains("Output(const Output &) = delete;"));
    assert!(header.contains("Output &operator=(const Output &) = delete;"));
}

/// "Raw handles stay private": neither generated type's raw member is ever
/// declared inside a `public:` section, and no public constructor accepts
/// the raw handle type directly.
#[test]
fn raw_handle_members_are_private() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    assert!(
        header.contains("private:\n    explicit Provider(::spx_pg_calling_consumer *raw) noexcept")
    );
    assert!(header.contains("::spx_pg_calling_consumer *raw_ = nullptr;"));
    assert!(header.contains("explicit Output(::spx_pg_output raw) noexcept"));
}

/// "Use an explicit namespace containing the schema/version" and "generate
/// include guards from stable contract identity."
#[test]
fn wrapper_header_uses_a_versioned_namespace_and_a_stable_include_guard() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    assert!(header.contains("namespace semaprax::public_generic::v1 {"));
    assert!(header.contains("#ifndef SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP"));
    assert!(header.contains("#define SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP"));
    assert!(header.contains("#endif // SEMAPRAX_PUBLIC_GENERIC_CONSUMER_V1_HPP"));
}

/// No `std::span` (a C++20 facility) and no other C++20-only standard
/// library surface.
#[test]
fn wrapper_header_never_names_stdspan() {
    let consumer = generate();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    assert!(!header.contains("std::span"));
    assert!(!header.contains("<span>"));
}

/// Field names are derived from identity bytes, matching
/// [`c_calling`]/[`rust_calling`]'s own scheme exactly, never from display
/// text.
#[test]
fn field_names_are_derived_from_identity_bytes_not_display_text() {
    let field = OwnedByteField::new("some.declaration.identity");
    assert_eq!(
        field_name(&field),
        format!(
            "field_{}",
            crate::public_generic_consumer::identifier(&field.identity)
        )
    );
    let other = OwnedByteField::new("some.other.identity");
    assert_ne!(field_name(&field), field_name(&other));
}

#[test]
fn duplicate_field_identity_in_one_record_is_rejected() {
    let input = RecordShape::new(vec![
        OwnedByteField::new("same.identity"),
        OwnedByteField::new("same.identity"),
    ]);
    let output = RecordShape::new(vec![OwnedByteField::new("x"), OwnedByteField::new("y")]);
    let error =
        generate_cxx_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output).unwrap_err();
    assert_eq!(
        error,
        ShapeError::DuplicateFieldIdentity {
            record: "Input",
            identity: "same.identity".to_owned(),
        }
    );
}

#[test]
fn mismatched_leaf_counts_are_rejected() {
    let input = RecordShape::new(vec![OwnedByteField::new("only-one")]);
    let output = RecordShape::new(vec![OwnedByteField::new("a"), OwnedByteField::new("b")]);
    let error =
        generate_cxx_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output).unwrap_err();
    assert_eq!(
        error,
        ShapeError::LeafCountMismatch {
            input: 1,
            output: 2,
        }
    );
}

#[test]
fn no_host_path_or_checkout_specific_text_survives_generation() {
    for (name, contents) in generate().files() {
        assert!(
            !contents.contains("/Users/") && !contents.contains("C:\\"),
            "{name} must not embed a checkout-specific host path"
        );
        assert!(
            !contents.contains("{{") && !contents.contains("}}"),
            "{name} must not leave a surviving template placeholder"
        );
    }
}

#[test]
fn field_count_and_field_lists_scale_with_the_shape() {
    let input = RecordShape::new(vec![
        OwnedByteField::new("one"),
        OwnedByteField::new("two"),
        OwnedByteField::new("three"),
    ]);
    let output = input.clone();
    let consumer =
        generate_cxx_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output).unwrap();
    let (_, header) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == WRAPPER_HEADER_FILE_NAME)
        .unwrap();
    for field in &input.fields {
        assert!(header.contains(&field_name(field)));
    }
}

/// A single-field shape (the degenerate case `zero_bytes_input`'s doc
/// comment names) must still generate without a fixed two-field
/// assumption leaking into the templates.
#[test]
fn a_single_field_shape_generates_successfully() {
    let input = RecordShape::new(vec![OwnedByteField::new("solo")]);
    let output = input.clone();
    let consumer = generate_cxx_calling_consumer(DESCRIPTOR_BYTES, &binding(), &input, &output)
        .expect("a single-field shape must generate");
    let (_, round_trip) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == ROUND_TRIP_FILE_NAME)
        .unwrap();
    assert!(round_trip.contains("zero_bytes_input"));
    assert!(round_trip.contains("first_leaf"));
}
