const HASH=__SPX_HASH__,COMMAND=__SPX_COMMAND__,MAX=65536,URL_MAX=2048;
const encoder=new TextEncoder(),decoder=new TextDecoder('utf-8',{fatal:true}),records=new WeakMap(),fixtures=new WeakMap();
const own=(value,label)=>{if(Object.getPrototypeOf(value)!==Uint8Array.prototype)throw new TypeError(label+' must be Uint8Array');return new Uint8Array(value)};
const exactKeys=(value,keys,label)=>{if(!value||Object.getPrototypeOf(value)!==Object.prototype)throw new TypeError(label);const actual=Object.keys(value).sort();if(actual.length!==keys.length||actual.some((key,index)=>key!==keys[index]))throw new TypeError(label+' keys')};
export function createFixture(document){
  if(!document||Object.getPrototypeOf(document)!==Object.prototype)throw new TypeError('fixture');
  const keys=Object.keys(document);if(keys.some(key=>!['connections','https','listeners','schema'].includes(key)))throw new TypeError('fixture keys');
  if(document.schema!=='semaprax.network-fixture.v3'||!Array.isArray(document.connections)||document.connections.length!==0||!Array.isArray(document.https)||document.https.length>8)throw new TypeError('fixture schema');
  if(document.listeners!==undefined&&(!Array.isArray(document.listeners)||document.listeners.length!==0))throw new TypeError('fixture listeners');
  const https=document.https.map((item,index)=>{exactKeys(item,['response','url'],'fixture HTTPS '+index);if(typeof item.url!=='string'||item.url.includes('\0'))throw new TypeError('fixture URL '+index);const url=encoder.encode(item.url);if(url.length===0||url.length>URL_MAX||!item.url.startsWith('https://'))throw new TypeError('fixture URL '+index);if(typeof item.response!=='string')throw new TypeError('fixture response '+index);const response=encoder.encode(item.response);if(response.length>MAX)throw new RangeError('fixture response '+index);return{url:item.url,response}});
  const fixture=Object.freeze({});fixtures.set(fixture,https);return fixture;
}
export function createInvocation(argv,stdin,fixture){
  if(!Array.isArray(argv)||argv.length>16)throw new RangeError('argument count');
  const args=[];let used=0;for(const value of argv){if(typeof value!=='string'||value.includes('\0'))throw new TypeError('argument');const bytes=encoder.encode(value);used+=bytes.length;if(used>MAX)throw new RangeError('input capacity');args.push(bytes)}
  const input=own(stdin,'stdin');used+=input.length;if(used>MAX)throw new RangeError('input capacity');const source=fixtures.get(fixture);if(!source)throw new TypeError('fixture provider');const token=Object.freeze({});records.set(token,{args,input,https:source.map(item=>({url:item.url,response:new Uint8Array(item.response)}))});return token;
}
export async function instantiate(wasm,invocation){
  const input=records.get(invocation);if(!input||!records.delete(invocation))throw new TypeError('invocation provider');const bytes=own(wasm,'wasm');if(!globalThis.crypto?.subtle)throw new Error('Web Crypto required');const digest=new Uint8Array(await globalThis.crypto.subtle.digest('SHA-256',bytes)),actual=Array.from(digest,b=>b.toString(16).padStart(2,'0')).join('');if(actual!==HASH)throw new Error('Wasm authentication');
  let instance=null,next=1,stdinRead=false,nextHttps=0;const entries=new Map();const memory=()=>new Uint8Array(instance.exports.memory.buffer),view=()=>new DataView(instance.exports.memory.buffer);
  const decode=c=>{if(typeof c!=='bigint')throw Error('carrier');const w=BigInt.asUintN(64,c),n=Number(w&0xffffffffn),r=Number((w>>32n)&0xffffffffn);if(n>MAX)throw Error('carrier length');return{n,r,t:(r&0x80000000)!==0,k:r&0x7fffffff}};
  const read=c=>{const d=decode(c);if(d.t){const b=entries.get(d.k);if(!b||b.length!==d.n)throw Error('owned token');return b}if((d.r&0xc0000000)===0x40000000){const p=(d.r&0xffff)*8,k=(d.r>>>16)&0x1fff,v=view();if(p+32>v.byteLength||v.getUint32(p,true)!==k||v.getUint32(p+4,true)!==p||Number(v.getBigUint64(p+24,true))!==d.n)throw Error('descriptor');const root=v.getBigInt64(p+8,true),off=Number(v.getBigUint64(p+16,true)),all=read(root);if(off>all.length||d.n>all.length-off)throw Error('range');return all.slice(off,off+d.n)}if(d.r>memory().length-d.n)throw Error('fixed root');return memory().slice(d.r,d.r+d.n)};
  const alloc=b=>{if(entries.size>=16||next>0x7fffffff)throw Error('arena');const k=next++;entries.set(k,new Uint8Array(b));return BigInt.asIntN(64,((0x80000000n|BigInt(k))<<32n)|BigInt(b.length))};const out=(p,value)=>view().setBigInt64(p,BigInt(value),true);
  let offsets=[],cursor=0;for(const arg of input.args){offsets.push(cursor);cursor+=arg.length}
  const env={
    spx_add:(a,b)=>a+b,spx_sub:(a,b)=>a-b,spx_mul:(a,b)=>a*b,spx_div:(a,b)=>a/b,spx_rem:(a,b)=>a%b,spx_neg:a=>-a,spx_contract_fail:()=>{throw Error('contract')},
    spx_bytes_copy:c=>alloc(read(c)),spx_bytes_get:(c,i)=>{const b=read(c),n=Number(BigInt.asUintN(64,i));return n<b.length?b[n]:-1},spx_bytes_drop:c=>{const d=decode(c);if(!d.t||!entries.delete(d.k))throw Error('drop')},spx_bytes_as_slice:c=>{read(c);return c},
    spx_command_args_len_v1:()=>BigInt(input.args.length),spx_command_arg_utf8_v1:(i,p)=>{const n=Number(BigInt.asUintN(64,i));if(n>=input.args.length)return 1;memory().set(input.args[n],offsets[n]);out(p,BigInt.asIntN(64,(BigInt(offsets[n])<<32n)|BigInt(input.args[n].length)));return 0},spx_command_stdin_read_v1:p=>{if(stdinRead)return 3;stdinRead=true;out(p,alloc(input.input));return 0},spx_command_owned_bytes_validate_v1:c=>{try{const d=decode(c),b=entries.get(d.k);return d.t&&d.k!==0&&b&&b.length===d.n?0:1}catch{return 1}},
    spx_https_get_v1:(root,len,max,p)=>{let url;try{const n=len>>>0;if(n===0||n>URL_MAX)return 1;url=decoder.decode(read(BigInt.asIntN(64,(BigInt(root>>>0)<<32n)|BigInt(n))))}catch{return 1}if(!url.startsWith('https://'))return 2;const request=input.https[nextHttps],bound=max>>>0;if(bound===0||bound>MAX)return 4;if(!request||request.url!==url)return 3;if(request.response.length>bound)return 4;nextHttps++;out(p,alloc(request.response));return 0}
  };
  try{const result=await WebAssembly.instantiate(bytes,Object.freeze({env:Object.freeze(env)}));instance=result.instance;if(instance.exports.memory.buffer.byteLength!==393216)throw Error('memory');const raw=instance.exports[COMMAND](),status=Number(instance.exports.__spx_data_status_v1.value),httpStatus=Number(instance.exports.__spx_http_status_v1.value);if(status===0&&httpStatus!==0)throw Error('HTTP status marker');if(status!==0){const error=Object.assign(new Error(httpStatus?'HTTPS command failure':'language command failure'),{code:status});if(httpStatus)error.domain='semaprax.http.v1';throw error}if(raw!==0&&raw!==1)throw Error('bool');if(entries.size!==0)throw Error('unsettled');const sl=Number(instance.exports.__spx_stdout_length_v1.value),el=Number(instance.exports.__spx_stderr_length_v1.value);if(sl<0||el<0||sl+el>MAX)throw Error('transcript');const mem=memory(),stdout=mem.slice(131072,131072+sl),stderr=mem.slice(196608,196608+el);mem.fill(0,131072,393216);return Object.freeze({result:raw===1,stdout,stderr})}catch(error){if(instance)memory().fill(0,131072,393216);entries.clear();throw error}
}
