//! Authority-free generated Rust module for one admitted Project `yield`.
//!
//! The module pins an exact Project revision, selected source function and
//! compiler-owned suspension plan. A caller registers one Rust callback only
//! after presenting the matching admitted revision. The callback runs on the
//! first poll and never gives the generated code a runtime or network handle.

use super::super::ProjectSnapshot;
use super::ProjectRevision;
use crate::diagnostic::Diagnostic;

const MODULE_BODY: &str = r#"
use semaprax::diagnostic::Diagnostic;
use semaprax::project::ProjectRevision;
use semaprax::resumable_effects::source_local_future::{SourceLocalFuture, SourceLocalFutureFailure};
use std::cell::RefCell;
use std::future::Future;
use std::rc::Rc;
use std::sync::Arc;

/// One checked source suspension's one-shot Rust import registration.
pub struct RegisteredAsyncImport<H> {
    revision: Arc<ProjectRevision>,
    callback: H,
    local: Rc<()>,
}

#[derive(Debug)]
pub enum AsyncCallError<E> {
    Host(E),
    Source(SourceLocalFutureFailure),
}

/// Register against the exact source and Project revision compiled into this
/// module. Registration performs no host effect and starts no Future.
pub fn register<H>(
    revision: Arc<ProjectRevision>,
    callback: H,
) -> Result<RegisteredAsyncImport<H>, Vec<Diagnostic>> {
    revision.require_source_local_future_binding(
        PROJECT_REVISION,
        SOURCE_FUNCTION_ID,
        &SOURCE_PLAN_IDENTITY,
    )?;
    Ok(RegisteredAsyncImport {
        revision,
        callback,
        local: Rc::new(()),
    })
}

impl<H> RegisteredAsyncImport<H> {
    /// The source's pure prefix runs before this method returns. The host
    /// callback starts only when the returned Future is first polled.
    pub fn call<F, E>(
        self,
        seed: i64,
        max_steps: usize,
    ) -> Result<SourceLocalFuture<F, H>, Vec<Diagnostic>>
    where
        F: Future<Output = Result<i64, E>> + 'static,
        H: FnOnce(i64) -> F + 'static,
    {
        let _ = self.local;
        SourceLocalFuture::prepare_revision(
            self.revision,
            seed,
            max_steps,
            self.callback,
        )
    }


    /// Preserve a caller's typed Rust error while keeping source failures
    /// distinct. The error slot is local to this one invocation and is never
    /// serialized, published, or shared across threads.
    pub fn call_typed<F, E>(
        self,
        seed: i64,
        max_steps: usize,
    ) -> Result<impl Future<Output = Result<i64, AsyncCallError<E>>>, Vec<Diagnostic>>
    where
        F: Future<Output = Result<i64, E>> + 'static,
        H: FnOnce(i64) -> F + 'static,
        E: 'static,
    {
        let RegisteredAsyncImport { revision, callback, local: _ } = self;
        let host_error = Rc::new(RefCell::new(None));
        let handler_error = Rc::clone(&host_error);
        let wrapped = move |request| {
            let future = callback(request);
            let slot = Rc::clone(&handler_error);
            async move {
                match future.await {
                    Ok(value) => Ok(value),
                    Err(error) => {
                        *slot.borrow_mut() = Some(error);
                        Err(())
                    }
                }
            }
        };
        let source = SourceLocalFuture::prepare_revision(
            revision, seed, max_steps, wrapped,
        )?;
        Ok(async move {
            match source.await {
                Ok(value) => Ok(value),
                Err(SourceLocalFutureFailure::HandlerFailed) => {
                    match host_error.borrow_mut().take() {
                        Some(error) => Err(AsyncCallError::Host(error)),
                        None => Err(AsyncCallError::Source(SourceLocalFutureFailure::HandlerFailed)),
                    }
                }
                Err(error) => Err(AsyncCallError::Source(error)),
            }
        })
    }
}
"#;

impl ProjectRevision {
    /// Render an inert Rust module for the exact selected source suspension.
    /// The returned bytes carry no publication or effect authority. A caller
    /// can stage them in a separately authorized Rust package.
    pub fn render_source_local_future_rust_module(&self) -> Result<String, Vec<Diagnostic>> {
        let signature = self.source_local_future_signature()?;
        Ok(format!(
            "// Generated by SEMAPRAX for one Project source-local-future.v1 revision.\n\
             pub const PROJECT_REVISION: &str = {:?};\n\
             pub const SOURCE_FUNCTION_ID: &str = {:?};\n\
             pub const SOURCE_PLAN_IDENTITY: [u8; 32] = {:?};\n{}",
            self.project_revision(),
            signature.function_id(),
            signature.plan_identity(),
            MODULE_BODY
        ))
    }
}

impl ProjectSnapshot {
    /// Recheck held Project inputs before and after rendering the exact Rust
    /// module. This does not publish or compile the module.
    pub fn render_source_local_future_rust_module(&mut self) -> Result<String, Vec<Diagnostic>> {
        self.with_authenticated_request(|snapshot| {
            snapshot
                .retain_revision()
                .render_source_local_future_rust_module()
        })
    }
}
