//! Authority-free generated Rust module for one admitted Project `yield`.
//!
//! The module pins an exact Project revision, selected source function and
//! compiler-owned suspension plan. A caller registers one Rust callback only
//! after presenting the matching admitted revision. The callback runs on the
//! first poll and never gives the generated code a runtime or network handle.

use super::super::ProjectSnapshot;
use super::ProjectRevision;
use crate::diagnostic::Diagnostic;

const MODULE_BODY: &str = r#"
use semaprax::diagnostic::Diagnostic;
use semaprax::project::ProjectRevision;
use semaprax::resumable_effects::source_local_future::SourceLocalFuture;
use std::future::Future;
use std::rc::Rc;
use std::sync::Arc;

/// One checked source suspension's one-shot Rust import registration.
pub struct RegisteredAsyncImport<H> {
    revision: Arc<ProjectRevision>,
    callback: H,
    local: Rc<()>,
}

/// Register against the exact source and Project revision compiled into this
/// module. Registration performs no host effect and starts no Future.
pub fn register<H>(
    revision: Arc<ProjectRevision>,
    callback: H,
) -> Result<RegisteredAsyncImport<H>, Vec<Diagnostic>> {
    let signature = revision.source_local_future_signature()?;
    if revision.project_revision() != PROJECT_REVISION
        || signature.function_id() != SOURCE_FUNCTION_ID
        || signature.plan_identity() != &SOURCE_PLAN_IDENTITY
    {
        return Err(vec![Diagnostic::io(
            "SPX-H006",
            "generated local Future module does not match selected Project revision",
        )]);
    }
    Ok(RegisteredAsyncImport {
        revision,
        callback,
        local: Rc::new(()),
    })
}

impl<H> RegisteredAsyncImport<H> {
    /// The source's pure prefix runs before this method returns. The host
    /// callback starts only when the returned Future is first polled.
    pub fn call<F, E>(
        self,
        seed: i64,
        max_steps: usize,
    ) -> Result<SourceLocalFuture<F, H>, Vec<Diagnostic>>
    where
        F: Future<Output = Result<i64, E>> + 'static,
        H: FnOnce(i64) -> F + 'static,
    {
        let _ = self.local;
        SourceLocalFuture::prepare_revision(
            self.revision,
            seed,
            max_steps,
            self.callback,
        )
    }
}
"#;

impl ProjectRevision {
    /// Render an inert Rust module for the exact selected source suspension.
    /// The returned bytes carry no publication or effect authority. A caller
    /// can stage them in a separately authorized Rust package.
    pub fn render_source_local_future_rust_module(&self) -> Result<String, Vec<Diagnostic>> {
        let signature = self.source_local_future_signature()?;
        Ok(format!(
            "// Generated by SEMAPRAX for one Project source-local-future.v1 revision.\n\
             pub const PROJECT_REVISION: &str = {:?};\n\
             pub const SOURCE_FUNCTION_ID: &str = {:?};\n\
             pub const SOURCE_PLAN_IDENTITY: [u8; 32] = {:?};\n{}",
            self.project_revision(),
            signature.function_id(),
            signature.plan_identity(),
            MODULE_BODY
        ))
    }
}

impl ProjectSnapshot {
    /// Recheck held Project inputs before and after rendering the exact Rust
    /// module. This does not publish or compile the module.
    pub fn render_source_local_future_rust_module(&mut self) -> Result<String, Vec<Diagnostic>> {
        self.with_authenticated_request(|snapshot| {
            snapshot
                .retain_revision()
                .render_source_local_future_rust_module()
        })
    }
}
