//! Generates a real, standalone C11 *calling* consumer for the native C11
//! public-generic provider (issue #154), answering issue #158.
//!
//! This is not the metadata-only consumer generated by [`super`]: that
//! consumer never allocates, transfers, or calls anything. It is also not a
//! reimplementation of, or a wrapper around, the [`super::rust_calling`]
//! generator: this crate emits plain C11 that links against the SAME frozen
//! native ABI ([`crate::public_generic_abi::native`]) through the real C
//! symbols the header declares, never through Rust FFI declarations. This
//! generator embeds one trusted descriptor and
//! [`NativeProviderBindingV1`], independently verifies both before any
//! native allocation, encodes one concrete owned input record into
//! [Logical Carrier v1](../../docs/PUBLIC-GENERIC-CARRIER-V1.md) bytes,
//! transfers it exactly once through the native adapter, calls the bound
//! endpoint, and decodes and independently validates the result -- the C
//! calling half PG-5/PG-6 left open.
//!
//! **Scope, stated once**, restating [`super::rust_calling`]'s own module
//! note: [Public Generic Boundary Profile
//! v1](../../docs/PUBLIC-GENERIC-BOUNDARY-PROFILE-V1.md) admits exactly one
//! owned aggregate input parameter and exactly one owned aggregate result in
//! v1, so this generator emits exactly two concrete structs, `spx_pg_input`
//! and `spx_pg_output`, each a flat sequence of owned-`Bytes` leaves; a Copy
//! scalar or nested-record leaf is future work tracked by the same #119
//! prerequisite [`super::rust_calling`] names, not a limitation invented
//! here.
//!
//! **Clean surface for #159.** The generated public header
//! (`spx_pg_calling_consumer.h`) never mentions a native ABI type
//! (`spx_pg_provider_v1` and friends stay behind the opaque
//! `spx_pg_calling_consumer` handle, entirely inside the generated `.c`
//! file) and depends on nothing but `<stddef.h>`/`<stdint.h>`, so issue
//! #159's C++17 consumer can `extern "C"`-include this exact header and link
//! against the compiled `spx_pg_calling_consumer.c` rather than inventing a
//! second ABI.
//!
//! Determinism and authority: like [`super::generate`] and
//! [`super::rust_calling::generate_rust_calling_consumer`], this is a pure
//! function from already-trusted bytes to source text. It reads no file,
//! starts no process, and uses no network; the C program it emits is what
//! actually calls native code, once compiled and executed by a caller.

use crate::public_generic_abi::native::binding::NativeProviderBindingV1;
use crate::public_generic_abi::native::template::HEADER_V1;

use super::identifier;
use super::rust_calling::{OwnedByteField, RecordShape, ShapeError};

/// The generated C field name for one owned leaf, matching
/// [`super::rust_calling`]'s own `field_<hex-identity>` scheme exactly (both
/// generators derive from [`identifier`]), so the same descriptor produces
/// aligned field names across languages.
fn field_name(field: &OwnedByteField) -> String {
    format!("field_{}", identifier(&field.identity))
}

/// Restates [`RecordShape`]'s own (private-to-`rust_calling`) duplicate
/// check, since that method is not visible outside its defining module.
fn duplicate_identity(shape: &RecordShape) -> Option<&str> {
    for (index, field) in shape.fields.iter().enumerate() {
        if shape.fields[..index]
            .iter()
            .any(|earlier| earlier.identity == field.identity)
        {
            return Some(&field.identity);
        }
    }
    None
}

/// One generated file's relative path and deterministic contents, in
/// emission order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CallingConsumer {
    files: Vec<(String, String)>,
}

impl CallingConsumer {
    pub fn files(&self) -> &[(String, String)] {
        &self.files
    }
}

/// The exact frozen native ABI header, copied verbatim into every generated
/// consumer so `spx_pg_calling_consumer.c` can `#include` the real thing
/// rather than restating its declarations independently.
pub const HEADER_FILE_NAME: &str = "spx_pg_v1.h";
/// The generated clean public surface: opaque handle, owned-bytes structs,
/// concrete `spx_pg_input`/`spx_pg_output`, and the consumer API. Depends on
/// nothing but `<stddef.h>`/`<stdint.h>` -- never the native ABI header.
pub const CONSUMER_HEADER_FILE_NAME: &str = "spx_pg_calling_consumer.h";
/// The generated implementation: embeds the trusted descriptor/binding
/// bytes, verifies them, and calls the real native ABI declared in
/// [`HEADER_FILE_NAME`].
pub const CONSUMER_SOURCE_FILE_NAME: &str = "spx_pg_calling_consumer.c";
/// The generated executable test driver: real execution evidence, not a
/// mere compile check.
pub const ROUND_TRIP_FILE_NAME: &str = "round_trip.c";

/// Generate one C11 calling consumer for `descriptor_bytes` and `binding`,
/// admitting exactly `input`/`output` as the one owned input parameter and
/// one owned result [Public Generic Boundary Profile
/// v1](../../docs/PUBLIC-GENERIC-BOUNDARY-PROFILE-V1.md) admits in v1.
///
/// Deterministic: the same arguments always produce byte-identical files.
pub fn generate_c_calling_consumer(
    descriptor_bytes: &[u8],
    binding: &NativeProviderBindingV1,
    input: &RecordShape,
    output: &RecordShape,
) -> Result<CallingConsumer, ShapeError> {
    if let Some(identity) = duplicate_identity(input) {
        return Err(ShapeError::DuplicateFieldIdentity {
            record: "Input",
            identity: identity.to_owned(),
        });
    }
    if let Some(identity) = duplicate_identity(output) {
        return Err(ShapeError::DuplicateFieldIdentity {
            record: "Output",
            identity: identity.to_owned(),
        });
    }
    if input.fields.len() != output.fields.len() {
        return Err(ShapeError::LeafCountMismatch {
            input: input.fields.len(),
            output: output.fields.len(),
        });
    }

    let binding_bytes = binding.encode();
    let files = vec![
        (HEADER_FILE_NAME.to_owned(), HEADER_V1.replace("\r\n", "\n")),
        (
            CONSUMER_HEADER_FILE_NAME.to_owned(),
            render::consumer_header(input, output),
        ),
        (
            CONSUMER_SOURCE_FILE_NAME.to_owned(),
            render::consumer_source(descriptor_bytes, &binding_bytes, input, output),
        ),
        (
            ROUND_TRIP_FILE_NAME.to_owned(),
            render::round_trip_c(input, output),
        ),
    ];
    Ok(CallingConsumer { files })
}

mod render;

#[cfg(test)]
mod tests;
