//! Generates a real, standalone Rust *calling* consumer crate for the native
//! C11 public-generic provider (issue #154), answering issue #156.
//!
//! This is not the metadata-only consumer generated by [`super`]: that
//! consumer never allocates, transfers, or calls anything, and its generated
//! type declarations exist only so a human can see the substituted field
//! tree. A crate generated here does the opposite: it embeds one trusted
//! descriptor and [`NativeProviderBindingV1`], independently verifies both
//! before any native allocation, encodes one concrete owned input record into
//! [Logical Carrier v1](../../docs/PUBLIC-GENERIC-CARRIER-V1.md) bytes,
//! transfers it exactly once through the native adapter, calls the bound
//! endpoint, and decodes and independently validates the result — the calling
//! half PG-5/PG-6 left open.
//!
//! **Scope, stated once.** [Public Generic Boundary Profile
//! v1](../../docs/PUBLIC-GENERIC-BOUNDARY-PROFILE-V1.md) admits exactly one
//! owned aggregate input parameter and exactly one owned aggregate result in
//! v1 (`OWNED_INPUT_PARAMETER_COUNT`/`OWNED_RESULT_COUNT` in
//! `boundary_profile.rs`), so this generator emits exactly two concrete
//! structs, `Input` and `Output`. The bound native provider itself only
//! implements "the existing owned-Bytes shapes... a flat sequence of
//! independent owned `Bytes` leaves" until issue #119 unblocks a real checked
//! generic export (see `native/provider_body.c`'s header comment and
//! [Native C11 physical adapter](../../docs/PUBLIC-GENERIC-CARRIER-V1.md#native-c11-physical-adapter-issue-154)),
//! so every field this generator emits is an owned `Vec<u8>` leaf; a Copy
//! scalar or nested-record leaf is future work tracked by that same
//! prerequisite, not a limitation invented here.
//!
//! Determinism and authority: like [`super::generate`], this is a pure
//! function from already-trusted bytes to source text. It reads no file,
//! starts no process, and uses no network; the crate it emits is what
//! actually calls native code, once compiled and executed by a caller.

use crate::public_generic_abi::native::binding::NativeProviderBindingV1;

use super::identifier;

/// One owned `Bytes` leaf field of a concrete generic record, in descriptor
/// order. `identity` is the field's declaration-identity text (e.g. a
/// `field.id` from the descriptor) — the generated Rust field name is
/// derived from its bytes via [`identifier`], never from a separate display
/// name, so a rename never changes the generated identifier and two fields
/// with different identities can never collide.
#[derive(Clone, Debug)]
pub struct OwnedByteField {
    pub identity: String,
}

impl OwnedByteField {
    pub fn new(identity: impl Into<String>) -> Self {
        Self {
            identity: identity.into(),
        }
    }

    fn field_name(&self) -> String {
        format!("field_{}", identifier(&self.identity))
    }
}

/// One concrete owned generic record shape: an ordered, descriptor-order
/// sequence of owned `Bytes` leaves. Two distinct records in one generated
/// crate (`Input` and `Output`) may independently reuse the same leaf
/// identities; only two identical identities *within one* [`RecordShape`]
/// collide, and [`generate_rust_calling_consumer`] rejects that rather than
/// emit two Rust struct fields with the same name.
#[derive(Clone, Debug, Default)]
pub struct RecordShape {
    pub fields: Vec<OwnedByteField>,
}

impl RecordShape {
    pub fn new(fields: Vec<OwnedByteField>) -> Self {
        Self { fields }
    }

    fn duplicate_identity(&self) -> Option<&str> {
        for (index, field) in self.fields.iter().enumerate() {
            if self.fields[..index]
                .iter()
                .any(|earlier| earlier.identity == field.identity)
            {
                return Some(&field.identity);
            }
        }
        None
    }
}

/// Why [`generate_rust_calling_consumer`] refused to generate. These are
/// generator-*contract* violations on already-trusted, compiler-internal
/// shape data — never a hostile-input vocabulary reachable from wire bytes —
/// so this is deliberately not an `SPX-PG` diagnostic code; nothing here
/// allocates one.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ShapeError {
    /// `input.fields.len() != output.fields.len()`. The bound native
    /// provider's flat-leaf shape preserves leaf count end to end (see the
    /// module scope note), so a caller asking for different input/output
    /// leaf counts is asking for a shape the provider cannot execute.
    LeafCountMismatch { input: usize, output: usize },
    /// Two fields of the same [`RecordShape`] share one identity, which
    /// would generate two Rust struct fields with the same name.
    DuplicateFieldIdentity {
        record: &'static str,
        identity: String,
    },
}

impl std::fmt::Display for ShapeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::LeafCountMismatch { input, output } => write!(
                f,
                "input has {input} owned leaves but output has {output}; the bound native provider preserves leaf count"
            ),
            Self::DuplicateFieldIdentity { record, identity } => write!(
                f,
                "{record} declares the field identity {identity:?} more than once"
            ),
        }
    }
}

/// One generated file's relative path and deterministic contents, in
/// emission order.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CallingConsumer {
    files: Vec<(String, String)>,
}

impl CallingConsumer {
    pub fn files(&self) -> &[(String, String)] {
        &self.files
    }
}

/// The crate name every generated calling consumer uses, so the generated
/// `Cargo.toml` and its own doc comments never drift from what
/// `tests/round_trip.rs` imports.
pub const CRATE_NAME: &str = "spx-pg-rust-calling-consumer";
pub const LIB_NAME: &str = "spx_pg_rust_calling_consumer";

/// The declared minimum supported Rust version for every generated calling
/// consumer crate, emitted verbatim into its `Cargo.toml`'s `rust-version`
/// field. Kept as one named constant, not a literal duplicated at each call
/// site, so a harness that wants to actually build the generated crate on
/// its declared minimum toolchain (rather than merely asserting the string)
/// can select the same version rustup resolves against, and the two can
/// never silently drift apart.
pub const RUST_VERSION: &str = "1.88";

/// Generate one Rust calling consumer crate for `descriptor_bytes` and
/// `binding`, admitting exactly `input`/`output` as the one owned input
/// parameter and one owned result [Public Generic Boundary Profile
/// v1](../../docs/PUBLIC-GENERIC-BOUNDARY-PROFILE-V1.md) admits in v1.
///
/// Deterministic: the same arguments always produce byte-identical files.
pub fn generate_rust_calling_consumer(
    descriptor_bytes: &[u8],
    binding: &NativeProviderBindingV1,
    input: &RecordShape,
    output: &RecordShape,
) -> Result<CallingConsumer, ShapeError> {
    if let Some(identity) = input.duplicate_identity() {
        return Err(ShapeError::DuplicateFieldIdentity {
            record: "Input",
            identity: identity.to_owned(),
        });
    }
    if let Some(identity) = output.duplicate_identity() {
        return Err(ShapeError::DuplicateFieldIdentity {
            record: "Output",
            identity: identity.to_owned(),
        });
    }
    if input.fields.len() != output.fields.len() {
        return Err(ShapeError::LeafCountMismatch {
            input: input.fields.len(),
            output: output.fields.len(),
        });
    }

    let binding_bytes = binding.encode();
    let files = vec![
        ("Cargo.toml".to_owned(), render::cargo_toml()),
        ("build.rs".to_owned(), render::build_rs()),
        ("src/lib.rs".to_owned(), render::lib_rs()),
        ("src/error.rs".to_owned(), render::error_rs()),
        (
            "src/descriptor.rs".to_owned(),
            render::descriptor_rs(descriptor_bytes, &binding_bytes),
        ),
        ("src/types.rs".to_owned(), render::types_rs(input, output)),
        (
            "src/carrier.rs".to_owned(),
            render::carrier_rs(input, output),
        ),
        ("src/provider.rs".to_owned(), render::provider_rs()),
        (
            "tests/round_trip.rs".to_owned(),
            render::round_trip_rs(input, output),
        ),
    ];
    Ok(CallingConsumer { files })
}

mod render;

#[cfg(test)]
mod tests;
