[package]
name = "semaprax-ri13-m2-record-iterator"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
semaprax = { path = "../..", version = "=0.7.0" }
semaprax-native-rust-interop = { path = "../../crates/semaprax-native-rust-interop-builder", version = "=0.1.0" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
