//! Real, C-hosted execution evidence for issue #158: a C11 *calling*
//! consumer generated by `semaprax::public_generic_consumer::c_calling`,
//! compiled and run as a standalone external C11 program against the SAME
//! compiled native provider `fixture.rs` exercises from C -- reusing
//! `render_reference_provider` rather than reimplementing the provider
//! (issue #154 is the provider; this harness is only ever its external
//! consumer, never a second implementation of it).
//!
//! Distinct from `rust_calling_consumer.rs` (issue #156): that harness links
//! a generated Rust crate against the provider through Rust FFI
//! declarations. This harness compiles the generated C11 files directly with
//! a real C compiler and links them against the provider's own object file
//! -- no Rust FFI boundary at all, exactly what a genuinely external C
//! toolchain would do.
//!
//! Known limitation, stated once here rather than hidden in prose: like
//! `fixture.rs` and `rust_calling_consumer.rs`, the trusted descriptor bytes
//! are a FIXTURE placeholder (#119 still blocks deriving one from a real
//! checked generic export), and this harness assumes a Unix-like host with
//! `clang` (or `$CLANG`) and `ar` (or `$AR`) on `PATH` -- Windows/MSVC is
//! untried.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

use semaprax::public_generic_abi::carrier::{CarrierBindingV1, TargetProfile};
use semaprax::public_generic_abi::native::binding::NativeProviderBindingV1;
use semaprax::public_generic_abi::native::template::render_reference_provider;
use semaprax::public_generic_consumer::c_calling::{generate_c_calling_consumer, CallingConsumer};
use semaprax::public_generic_consumer::rust_calling::{OwnedByteField, RecordShape};

static NEXT: AtomicU64 = AtomicU64::new(0);

const FIXTURE_DESCRIPTOR_BYTES: &[u8] = b"fixture-public-generic-descriptor-bytes-issue-158";

fn fixture_binding() -> NativeProviderBindingV1 {
    NativeProviderBindingV1::new(
        CarrierBindingV1::new(
            "sha256:9999999999999999999999999999999999999999999999999999999999999999",
            TargetProfile::NativeC11,
            "runtime:native-c11-fixture-issue-158",
        ),
        "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "spx_pg_endpoint_reverse_bytes_v1",
        "semaprax-0.4.1",
    )
}

fn shapes() -> (RecordShape, RecordShape) {
    let input = RecordShape::new(vec![
        OwnedByteField::new("consumers.c_calling.head"),
        OwnedByteField::new("consumers.c_calling.tail"),
    ]);
    let output = input.clone();
    (input, output)
}

struct Workspace(PathBuf);

impl Workspace {
    fn new(label: &str) -> Self {
        let root = env::temp_dir().join(format!(
            "spx-pg-c-calling-consumer-{}-{}-{label}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).unwrap();
        Self(root.canonicalize().unwrap())
    }

    fn path(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Workspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn tool(variable: &str, fallback: &str) -> PathBuf {
    env::var_os(variable).map_or_else(|| PathBuf::from(fallback), PathBuf::from)
}

fn run(command: &mut Command, label: &str) -> Output {
    command
        .output()
        .unwrap_or_else(|error| panic!("run {label}: {error}"))
}

/// Compile the SAME rendered reference provider `fixture.rs` uses (never a
/// second implementation) into an object file the generated C11 consumer
/// links against directly.
fn compile_provider_object(
    root: &Path,
    descriptor_bytes: &[u8],
    binding: &NativeProviderBindingV1,
    clang: &Path,
) -> PathBuf {
    let provider_source = render_reference_provider(descriptor_bytes, binding);
    let source_path = root.join("provider.c");
    fs::write(&source_path, &provider_source).unwrap();
    let object_path = root.join("provider.o");
    let compiled = run(
        Command::new(clang)
            .current_dir(root)
            .args(["-std=c11", "-O1", "-Wall", "-Wextra", "-Werror", "-c"])
            .arg(&source_path)
            .arg("-o")
            .arg(&object_path),
        "compile provider.c",
    );
    assert!(
        compiled.status.success(),
        "compiling the native provider failed: {}",
        String::from_utf8_lossy(&compiled.stderr)
    );
    assert!(object_path.is_file());
    object_path
}

fn write_generated_files(root: &Path, consumer: &CallingConsumer) {
    for (relative, contents) in consumer.files() {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&path, contents).unwrap();
    }
}

fn build_and_run(sanitized: bool) {
    let clang = if sanitized {
        let path = PathBuf::from(
            env::var_os("SEMAPRAX_STRING_SANITIZER_CLANG")
                .expect("selected gate requires provisioned SEMAPRAX_STRING_SANITIZER_CLANG"),
        );
        assert!(path.is_absolute() && path.is_file());
        path
    } else {
        tool("CLANG", "clang")
    };

    let (input, output) = shapes();
    let binding = fixture_binding();
    let consumer = generate_c_calling_consumer(FIXTURE_DESCRIPTOR_BYTES, &binding, &input, &output)
        .expect("a well-formed shape must generate");

    let workspace = Workspace::new(if sanitized { "sanitized" } else { "plain" });
    eprintln!(
        "generated C11 calling consumer workspace: {}",
        workspace.0.display()
    );
    write_generated_files(&workspace.0, &consumer);
    let provider_object =
        compile_provider_object(&workspace.0, FIXTURE_DESCRIPTOR_BYTES, &binding, &clang);

    for optimization in ["-O0", "-O2"] {
        let executable = workspace.path(&format!(
            "consumer{optimization}{}",
            std::env::consts::EXE_SUFFIX
        ));
        let mut compile = Command::new(&clang);
        compile.current_dir(&workspace.0).args([
            "-std=c11",
            optimization,
            "-Wall",
            "-Wextra",
            "-Werror",
        ]);
        if sanitized {
            compile.args([
                "-fsanitize=address,undefined",
                "-fno-sanitize-recover=all",
                "-fno-omit-frame-pointer",
            ]);
        }
        let built = compile
            .arg("spx_pg_calling_consumer.c")
            .arg("round_trip.c")
            .arg(&provider_object)
            .arg("-o")
            .arg(&executable)
            .output()
            .unwrap();
        assert!(
            built.status.success(),
            "{}: {}",
            workspace.0.display(),
            String::from_utf8_lossy(&built.stderr)
        );
        assert!(
            built.stderr.is_empty(),
            "warning-free build required: {}",
            String::from_utf8_lossy(&built.stderr)
        );

        let mut execute = Command::new(&executable);
        execute.current_dir(&workspace.0);
        if sanitized {
            execute
                .env("ASAN_OPTIONS", "halt_on_error=1")
                .env("UBSAN_OPTIONS", "halt_on_error=1:print_stacktrace=1");
        }
        let result = execute.output().unwrap();
        assert!(
            result.status.success(),
            "{}: stdout={} stderr={}",
            workspace.0.display(),
            String::from_utf8_lossy(&result.stdout),
            String::from_utf8_lossy(&result.stderr)
        );
        assert_eq!(result.stdout, b"c-calling-consumer-settled\n");
        assert!(result.stderr.is_empty());
    }
}

/// The executable half of issue #158: generates the C11 calling consumer,
/// compiles the *same* rendered reference provider `fixture.rs` exercises
/// into an object file, builds the generated consumer warning-free with
/// `-Wall -Wextra -Werror` at both `-O0` and `-O2`, and runs its own
/// generated `round_trip.c` against the real provider -- a full success
/// round trip with exact reversed-byte assertions, a mutated descriptor, a
/// mutated binding, a well-formed descriptor extended to name a different
/// (still well-formed) document, the per-leaf byte bound accepted exactly at
/// 64 KiB and rejected one byte over, and the full ordinal `0..=13`
/// failure-injection matrix -- each asserting zero live native
/// allocations/handles afterward via the provider's own test-only counters,
/// exactly like `probe.c`'s own C-hosted matrix for the same provider.
#[test]
fn generated_c_calling_consumer_executes_against_the_real_native_provider() {
    build_and_run(false);
}

#[test]
#[ignore = "requires explicitly provisioned Clang ASan/UBSan runtime and external process bounds"]
fn provisioned_c_calling_consumer_asan_ubsan() {
    build_and_run(true);
}

/// The generated public header depends on nothing but two standard C
/// headers and compiles alone as C11 -- a required "keep the surface clean
/// enough to wrap" check for issue #159's future C++17 consumer.
#[test]
fn consumer_header_compiles_standalone_as_c11() {
    let clang = tool("CLANG", "clang");
    let (input, output) = shapes();
    let consumer = generate_c_calling_consumer(
        FIXTURE_DESCRIPTOR_BYTES,
        &fixture_binding(),
        &input,
        &output,
    )
    .expect("a well-formed shape must generate");

    let workspace = Workspace::new("header-only");
    write_generated_files(&workspace.0, &consumer);
    let source = workspace.path("header_only.c");
    fs::write(
        &source,
        "#include \"spx_pg_calling_consumer.h\"\nint main(void) { return SPX_PG_CONSUMER_OK; }\n",
    )
    .unwrap();
    let object = workspace.path("header_only.o");
    let built = Command::new(&clang)
        .current_dir(&workspace.0)
        .args(["-std=c11", "-Wall", "-Wextra", "-Werror", "-c"])
        .arg(&source)
        .arg("-o")
        .arg(&object)
        .output()
        .unwrap();
    assert!(
        built.status.success(),
        "{}: {}",
        workspace.0.display(),
        String::from_utf8_lossy(&built.stderr)
    );
}
