//! Real, C++17-hosted execution evidence for issue #159: a C++17 *calling*
//! consumer generated by `semaprax::public_generic_consumer::cxx_calling`,
//! compiled and run as a standalone external C++17 program against the SAME
//! compiled native provider `fixture.rs` and `c_calling_consumer.rs`
//! exercise -- reusing `render_reference_provider` rather than
//! reimplementing the provider, and reusing the generated C11 calling
//! consumer (issue #158) rather than reimplementing its codec, lifecycle, or
//! pairing check.
//!
//! Distinct from `c_calling_consumer.rs`: this harness additionally compiles
//! `include/semaprax_public_generic_v1.hpp`'s generated `test/round_trip.cpp`
//! with a real C++17 compiler and links it against the SAME
//! `spx_pg_calling_consumer.c` object `c_calling_consumer.rs` builds and the
//! SAME provider object `fixture.rs` builds -- proving the move-only RAII
//! wrapper actually wraps the generated C11 client rather than duplicating
//! it, and proving zero leaked native resources through the *native
//! provider's own* test-only counters, exactly like the C11 harness for the
//! same provider.
//!
//! Known limitation, stated once here rather than hidden in prose: like
//! `fixture.rs` and `c_calling_consumer.rs`, the trusted descriptor bytes
//! are a FIXTURE placeholder (#119 still blocks deriving one from a real
//! checked generic export), and this harness assumes a Unix-like host with
//! `clang`/`clang++` (or `$CLANG`/`$CLANGXX`) on `PATH` -- Windows/MSVC is
//! untried, matching every other native-adapter harness in this module.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

use semaprax::public_generic_abi::carrier::{CarrierBindingV1, TargetProfile};
use semaprax::public_generic_abi::native::binding::NativeProviderBindingV1;
use semaprax::public_generic_abi::native::template::render_reference_provider;
use semaprax::public_generic_consumer::cxx_calling::{
    generate_cxx_calling_consumer, CallingConsumer,
};
use semaprax::public_generic_consumer::rust_calling::{OwnedByteField, RecordShape};

static NEXT: AtomicU64 = AtomicU64::new(0);

const FIXTURE_DESCRIPTOR_BYTES: &[u8] = b"fixture-public-generic-descriptor-bytes-issue-159";

fn fixture_binding() -> NativeProviderBindingV1 {
    NativeProviderBindingV1::new(
        CarrierBindingV1::new(
            "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            TargetProfile::NativeC11,
            "runtime:native-c11-fixture-issue-159",
        ),
        "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        "spx_pg_endpoint_reverse_bytes_v1",
        "semaprax-0.4.1",
    )
}

fn shapes() -> (RecordShape, RecordShape) {
    let input = RecordShape::new(vec![
        OwnedByteField::new("consumers.cxx_calling.head"),
        OwnedByteField::new("consumers.cxx_calling.tail"),
    ]);
    let output = input.clone();
    (input, output)
}

struct Workspace(PathBuf);

impl Workspace {
    fn new(label: &str) -> Self {
        let root = env::temp_dir().join(format!(
            "spx-pg-cxx-calling-consumer-{}-{}-{label}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).unwrap();
        // Avoid `\\?\` verbatim prefix on Windows (see rust_calling_consumer).
        Self(root)
    }

    fn path(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Workspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn tool(variable: &str, fallback: &str) -> PathBuf {
    env::var_os(variable).map_or_else(|| PathBuf::from(fallback), PathBuf::from)
}

fn run(command: &mut Command, label: &str) -> Output {
    command
        .output()
        .unwrap_or_else(|error| panic!("run {label}: {error}"))
}

/// Compile the SAME rendered reference provider `fixture.rs` and
/// `c_calling_consumer.rs` use (never a second implementation) into an
/// object file the generated C++17 consumer links against directly.
fn compile_provider_object(
    root: &Path,
    descriptor_bytes: &[u8],
    binding: &NativeProviderBindingV1,
    clang: &Path,
) -> PathBuf {
    let provider_source = render_reference_provider(descriptor_bytes, binding);
    let source_path = root.join("provider.c");
    fs::write(&source_path, &provider_source).unwrap();
    let object_path = root.join("provider.o");
    let compiled = run(
        Command::new(clang)
            .current_dir(root)
            .args(["-std=c11", "-O1", "-Wall", "-Wextra", "-Werror", "-c"])
            .arg(&source_path)
            .arg("-o")
            .arg(&object_path),
        "compile provider.c",
    );
    assert!(
        compiled.status.success(),
        "compiling the native provider failed: {}",
        String::from_utf8_lossy(&compiled.stderr)
    );
    assert!(object_path.is_file());
    object_path
}

fn write_generated_files(root: &Path, consumer: &CallingConsumer) {
    for (relative, contents) in consumer.files() {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&path, contents).unwrap();
    }
}

fn build_and_run(sanitized: bool) {
    let clang = if sanitized {
        let path = PathBuf::from(
            env::var_os("SEMAPRAX_STRING_SANITIZER_CLANG")
                .expect("selected gate requires provisioned SEMAPRAX_STRING_SANITIZER_CLANG"),
        );
        assert!(path.is_absolute() && path.is_file());
        path
    } else {
        tool("CLANG", "clang")
    };
    let clangxx = if sanitized {
        let path = PathBuf::from(
            env::var_os("SEMAPRAX_STRING_SANITIZER_CLANGXX")
                .unwrap_or_else(|| env::var_os("SEMAPRAX_STRING_SANITIZER_CLANG").unwrap()),
        );
        assert!(path.is_absolute() && path.is_file());
        path
    } else {
        tool("CLANGXX", "clang++")
    };

    let (input, output) = shapes();
    let binding = fixture_binding();
    let consumer =
        generate_cxx_calling_consumer(FIXTURE_DESCRIPTOR_BYTES, &binding, &input, &output)
            .expect("a well-formed shape must generate");

    let workspace = Workspace::new(if sanitized { "sanitized" } else { "plain" });
    eprintln!(
        "generated C++17 calling consumer workspace: {}",
        workspace.0.display()
    );
    write_generated_files(&workspace.0, &consumer);
    let provider_object =
        compile_provider_object(&workspace.0, FIXTURE_DESCRIPTOR_BYTES, &binding, &clang);

    for optimization in ["-O0", "-O2"] {
        let consumer_object = workspace.path(&format!("spx_pg_calling_consumer{optimization}.o"));
        let mut compile_c = Command::new(&clang);
        compile_c.current_dir(&workspace.0).args([
            "-std=c11",
            optimization,
            "-Wall",
            "-Wextra",
            "-Werror",
            "-c",
        ]);
        if sanitized {
            compile_c.args([
                "-fsanitize=address,undefined",
                "-fno-sanitize-recover=all",
                "-fno-omit-frame-pointer",
            ]);
        }
        let built_c = compile_c
            .arg("spx_pg_calling_consumer.c")
            .arg("-o")
            .arg(&consumer_object)
            .output()
            .unwrap();
        assert!(
            built_c.status.success(),
            "{}: {}",
            workspace.0.display(),
            String::from_utf8_lossy(&built_c.stderr)
        );
        assert!(
            built_c.stderr.is_empty(),
            "warning-free C build required: {}",
            String::from_utf8_lossy(&built_c.stderr)
        );

        let executable = workspace.path(&format!(
            "cxx_consumer{optimization}{}",
            std::env::consts::EXE_SUFFIX
        ));
        let mut compile_cxx = Command::new(&clangxx);
        compile_cxx.current_dir(&workspace.0).args([
            "-std=c++17",
            optimization,
            "-Wall",
            "-Wextra",
            "-Werror",
            "-Iinclude",
            "-I.",
        ]);
        if sanitized {
            compile_cxx.args([
                "-fsanitize=address,undefined",
                "-fno-sanitize-recover=all",
                "-fno-omit-frame-pointer",
            ]);
        }
        let built = compile_cxx
            .arg("test/round_trip.cpp")
            .arg(&consumer_object)
            .arg(&provider_object)
            .arg("-o")
            .arg(&executable)
            .output()
            .unwrap();
        assert!(
            built.status.success(),
            "{}: {}",
            workspace.0.display(),
            String::from_utf8_lossy(&built.stderr)
        );
        assert!(
            built.stderr.is_empty(),
            "warning-free C++17 build required: {}",
            String::from_utf8_lossy(&built.stderr)
        );

        let mut execute = Command::new(&executable);
        execute.current_dir(&workspace.0);
        if sanitized {
            execute
                .env("ASAN_OPTIONS", "halt_on_error=1")
                .env("UBSAN_OPTIONS", "halt_on_error=1:print_stacktrace=1");
        }
        let result = execute.output().unwrap();
        assert!(
            result.status.success(),
            "{}: stdout={} stderr={}",
            workspace.0.display(),
            String::from_utf8_lossy(&result.stdout),
            String::from_utf8_lossy(&result.stderr)
        );
        // Normalize CRLF to LF so the same "settled" contract passes on
        // Windows (which emits `\r\n`) and Unix (which emits `\n`).
        let normalized_stdout = if result.stdout.ends_with(b"\r\n") {
            let mut owned = result.stdout.clone();
            owned.pop();
            owned.pop();
            owned.push(b'\n');
            owned
        } else {
            result.stdout.clone()
        };
        assert_eq!(normalized_stdout, b"cxx-calling-consumer-settled\n");
        assert!(result.stderr.is_empty());
    }
}

/// The executable half of issue #159: generates the C++17 calling consumer
/// (which internally reuses the C11 calling consumer's exact generated
/// files), compiles the *same* rendered reference provider `fixture.rs` and
/// `c_calling_consumer.rs` exercise into an object file, compiles
/// `spx_pg_calling_consumer.c` into an object file with the same C11 flags
/// `c_calling_consumer.rs` uses, builds the generated `test/round_trip.cpp`
/// warning-free with `-std=c++17 -Wall -Wextra -Werror` at both `-O0` and
/// `-O2`, links all three objects, and runs the executable -- a full success
/// round trip, every move/self-move/moved-from/explicit-close/early-return
/// case, hostile pairing (mutated descriptor, mutated binding, a
/// differently-named but well-formed descriptor), zero-length and
/// embedded-zero-byte leaves, the exact per-leaf byte bound accepted and
/// rejected one byte over, container relocation, an independent output
/// copy, and the full ordinal `0..=13` failure-injection matrix -- each
/// asserting zero live native allocations/handles afterward via the wrapped
/// C11 consumer's own accessors to the provider's OWN test-only counters,
/// exactly like `c_calling_consumer.rs`'s own matrix for the same provider.
#[test]
fn generated_cxx_calling_consumer_executes_against_the_real_native_provider() {
    build_and_run(false);
}

#[test]
#[ignore = "requires explicitly provisioned Clang ASan/UBSan runtime and external process bounds"]
fn provisioned_cxx_calling_consumer_asan_ubsan() {
    build_and_run(true);
}

/// "Header self-contained" and "header can be included multiple times":
/// the generated wrapper header depends only on the generated C11 consumer
/// header (already proven standalone-C11-compilable by
/// `c_calling_consumer.rs::consumer_header_compiles_standalone_as_c11`) and
/// a fixed set of C++17 standard headers, and including it twice in one
/// translation unit must not violate the One Definition Rule (every free
/// function is `inline`; every class is defined once per translation unit
/// behind its own include guard).
#[test]
fn wrapper_header_compiles_standalone_as_cxx17_and_tolerates_double_inclusion() {
    let clangxx = tool("CLANGXX", "clang++");
    let (input, output) = shapes();
    let consumer = generate_cxx_calling_consumer(
        FIXTURE_DESCRIPTOR_BYTES,
        &fixture_binding(),
        &input,
        &output,
    )
    .expect("a well-formed shape must generate");

    let workspace = Workspace::new("header-only");
    write_generated_files(&workspace.0, &consumer);
    let source = workspace.path("header_only.cpp");
    fs::write(
        &source,
        "#include \"include/semaprax_public_generic_v1.hpp\"\n\
         #include \"include/semaprax_public_generic_v1.hpp\"\n\
         int main() { return 0; }\n",
    )
    .unwrap();
    let object = workspace.path("header_only.o");
    let built = Command::new(&clangxx)
        .current_dir(&workspace.0)
        .args(["-std=c++17", "-Wall", "-Wextra", "-Werror", "-I.", "-c"])
        .arg(&source)
        .arg("-o")
        .arg(&object)
        .output()
        .unwrap();
    assert!(
        built.status.success(),
        "{}: {}",
        workspace.0.display(),
        String::from_utf8_lossy(&built.stderr)
    );
    assert!(built.stderr.is_empty());
}
