//! Real, executed evidence for issue #156: a Rust *calling* consumer
//! generated by `semaprax::public_generic_consumer::rust_calling`, built as a
//! standalone external crate (its own `Cargo.toml`/`Cargo.lock`, no
//! dependency on the `semaprax` workspace crate), and run against the SAME
//! compiled native provider `tests/public_generic_native_adapter_v1/fixture.rs`
//! exercises from C -- reusing `render_reference_provider` rather than
//! reimplementing the provider (issue #154 is the provider; this harness is
//! only ever its external consumer).
//!
//! Known limitation, stated once here: like `fixture.rs`, the trusted
//! descriptor bytes are a fixture placeholder (`#119` still blocks deriving
//! one from a real checked generic export), and this harness runs on the one
//! Unix-like host this round ran on -- Linux/macOS with `clang`, `ar`, and
//! `cargo` on `PATH` -- not cross-platform hosted evidence. The generated
//! crate's `rust-version = "1.88"` field states the minimum toolchain claim;
//! this harness builds and runs it with whatever `rustc`/`cargo` the host
//! provides (1.98 locally), not a provisioned 1.88 toolchain -- it does not
//! itself prove the 1.88 minimum, only that a real, generated, external,
//! non-workspace crate compiles and executes against the real provider.
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};
use std::sync::atomic::{AtomicU64, Ordering};

use semaprax::public_generic_abi::carrier::{CarrierBindingV1, TargetProfile};
use semaprax::public_generic_abi::native::binding::NativeProviderBindingV1;
use semaprax::public_generic_abi::native::template::render_reference_provider;
use semaprax::public_generic_consumer::rust_calling::{
    generate_rust_calling_consumer, CallingConsumer, OwnedByteField, RecordShape,
};

static NEXT: AtomicU64 = AtomicU64::new(0);

const FIXTURE_DESCRIPTOR_BYTES: &[u8] = b"fixture-public-generic-descriptor-bytes-issue-156";

fn fixture_binding() -> NativeProviderBindingV1 {
    NativeProviderBindingV1::new(
        CarrierBindingV1::new(
            "sha256:5555555555555555555555555555555555555555555555555555555555555555",
            TargetProfile::NativeC11,
            "runtime:native-c11-fixture-issue-156",
        ),
        "sha256:6666666666666666666666666666666666666666666666666666666666666666",
        "spx_pg_endpoint_reverse_bytes_v1",
        "semaprax-0.4.1",
    )
}

fn shapes() -> (RecordShape, RecordShape) {
    let input = RecordShape::new(vec![
        OwnedByteField::new("consumers.calling.head"),
        OwnedByteField::new("consumers.calling.tail"),
    ]);
    let output = input.clone();
    (input, output)
}

struct Workspace(PathBuf);

impl Workspace {
    fn new(label: &str) -> Self {
        let root = env::temp_dir().join(format!(
            "spx-pg-rust-calling-consumer-{}-{}-{label}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).unwrap();
        Self(root.canonicalize().unwrap())
    }

    fn path(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }
}

impl Drop for Workspace {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn tool(variable: &str, fallback: &str) -> PathBuf {
    env::var_os(variable).map_or_else(|| PathBuf::from(fallback), PathBuf::from)
}

/// Compile the SAME rendered reference provider `fixture.rs` uses (never a
/// second implementation) into a static library the generated crate's
/// `build.rs` links against.
fn compile_provider_static_lib(
    root: &Path,
    descriptor_bytes: &[u8],
    binding: &NativeProviderBindingV1,
) -> PathBuf {
    let provider_source = render_reference_provider(descriptor_bytes, binding);
    let lib_dir = root.join("provider-lib");
    fs::create_dir_all(&lib_dir).unwrap();
    let source_path = lib_dir.join("provider.c");
    fs::write(&source_path, &provider_source).unwrap();

    let object_path = lib_dir.join("provider.o");
    let clang = tool("CLANG", "clang");
    let compiled = Command::new(&clang)
        .args(["-std=c11", "-O1", "-Wall", "-Wextra", "-Werror", "-c"])
        .arg(&source_path)
        .arg("-o")
        .arg(&object_path)
        .output()
        .expect("run the C compiler");
    assert!(
        compiled.status.success(),
        "compiling the native provider failed: {}",
        String::from_utf8_lossy(&compiled.stderr)
    );

    let archive_path = lib_dir.join("libspx_pg_reference_provider.a");
    let archiver = tool("AR", "ar");
    let archived = Command::new(&archiver)
        .arg("rcs")
        .arg(&archive_path)
        .arg(&object_path)
        .output()
        .expect("run the archiver");
    assert!(
        archived.status.success(),
        "archiving the native provider failed: {}",
        String::from_utf8_lossy(&archived.stderr)
    );
    assert!(archive_path.is_file());
    lib_dir
}

fn write_generated_crate(root: &Path, consumer: &CallingConsumer) {
    for (relative, contents) in consumer.files() {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::write(&path, contents).unwrap();
    }
}

fn cargo_command(crate_root: &Path, target_dir: &Path, lib_dir: &Path) -> Command {
    let mut command = Command::new(tool("CARGO", "cargo"));
    command
        .current_dir(crate_root)
        .env("CARGO_TARGET_DIR", target_dir)
        .env("SPX_PG_PROVIDER_LIB_DIR", lib_dir)
        .env("SPX_PG_PROVIDER_LIB_NAME", "spx_pg_reference_provider")
        // This generated crate is a standalone, external, non-workspace
        // crate; make sure it never inherits this repository's own
        // `.cargo/config.toml` (e.g. `build.jobs = 1`) by running from a
        // directory outside the checkout (`Workspace::new` already
        // guarantees that) and never pointing it back at this checkout's own
        // target directory.
        .env_remove("RUSTC_WRAPPER");
    command
}

struct TestSummary {
    passed: usize,
    failed: usize,
    ignored: usize,
}

/// Sum every `libtest` summary line's counts, e.g.
/// `test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s`.
/// `cargo test` runs one such binary per target (lib unit tests, the
/// `round_trip` integration test, doctests); summing rather than taking the
/// first line means this does not depend on which binary cargo happens to
/// run first.
fn parse_test_result_line(stdout: &str) -> Option<TestSummary> {
    let mut totals = TestSummary {
        passed: 0,
        failed: 0,
        ignored: 0,
    };
    let mut saw_a_line = false;
    for line in stdout
        .lines()
        .filter(|line| line.starts_with("test result:"))
    {
        saw_a_line = true;
        for field in line.split(';') {
            let field = field.trim();
            if let Some(count) = field.strip_suffix(" passed") {
                totals.passed += count.rsplit(' ').next()?.parse::<usize>().ok()?;
            } else if let Some(count) = field.strip_suffix(" failed") {
                totals.failed += count.rsplit(' ').next()?.parse::<usize>().ok()?;
            } else if let Some(count) = field.strip_suffix(" ignored") {
                totals.ignored += count.rsplit(' ').next()?.parse::<usize>().ok()?;
            }
        }
    }
    saw_a_line.then_some(totals)
}

fn run(command: &mut Command, label: &str) -> Output {
    command
        .output()
        .unwrap_or_else(|error| panic!("run {label}: {error}"))
}

/// Generate the Rust calling consumer, compile the real native provider it
/// links against, build it clippy-clean and warning-free as a standalone
/// external crate, and run its own `tests/round_trip.rs` against the real
/// provider -- a real success round trip, hostile descriptor/binding
/// pairing, a per-leaf byte bound, and the full ordinal 0..=13
/// failure-injection matrix, each asserting zero live native
/// allocations/handles afterward. This is the executable half of issue
/// #156: nothing here merely parses metadata or type-checks generated
/// source.
#[test]
fn generated_rust_calling_consumer_executes_against_the_real_native_provider() {
    let (input, output) = shapes();
    let binding = fixture_binding();
    let consumer =
        generate_rust_calling_consumer(FIXTURE_DESCRIPTOR_BYTES, &binding, &input, &output)
            .expect("a well-formed shape must generate");

    let workspace = Workspace::new("execute");
    eprintln!(
        "generated Rust calling consumer workspace: {}",
        workspace.0.display()
    );
    let lib_dir = compile_provider_static_lib(&workspace.0, FIXTURE_DESCRIPTOR_BYTES, &binding);
    let crate_root = workspace.path("generated-rust-consumer");
    write_generated_crate(&crate_root, &consumer);
    let target_dir = workspace.path("cargo-target");

    let lockfile = run(
        Command::new(tool("CARGO", "cargo"))
            .current_dir(&crate_root)
            .env("CARGO_TARGET_DIR", &target_dir)
            .arg("generate-lockfile"),
        "cargo generate-lockfile",
    );
    assert!(
        lockfile.status.success(),
        "generate-lockfile: {}",
        String::from_utf8_lossy(&lockfile.stderr)
    );
    assert!(
        crate_root.join("Cargo.lock").is_file(),
        "cargo generate-lockfile must produce Cargo.lock"
    );

    // Clippy-clean and warning-free as a standalone crate -- required tests
    // "warning-free build and clippy where applicable" -- built once here so
    // the immediately following `cargo test` reuses the same target
    // directory rather than rebuilding from scratch.
    let clippy = run(
        cargo_command(&crate_root, &target_dir, &lib_dir).args([
            "clippy",
            "--locked",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ]),
        "cargo clippy",
    );
    assert!(
        clippy.status.success(),
        "the generated crate is not clippy-clean:\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&clippy.stdout),
        String::from_utf8_lossy(&clippy.stderr)
    );

    // Single-threaded: the linked native provider is explicitly documented
    // as "single translation unit, single-threaded: no concurrency claim is
    // made anywhere in this file" (spx_pg_v1.h). Its allocator, handle
    // registry, and failure-injection state are process-global, so running
    // this crate's tests concurrently would corrupt shared native state
    // rather than exercise it.
    let tests = run(
        cargo_command(&crate_root, &target_dir, &lib_dir).args([
            "test",
            "--locked",
            "--",
            "--test-threads=1",
        ]),
        "cargo test",
    );
    let stdout = String::from_utf8_lossy(&tests.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&tests.stderr).into_owned();
    assert!(
        tests.status.success(),
        "the generated crate's own tests failed:\nstdout:\n{stdout}\nstderr:\n{stderr}"
    );
    let summary = parse_test_result_line(&stdout)
        .unwrap_or_else(|| panic!("no 'test result:' line found in:\n{stdout}"));
    assert_eq!(summary.failed, 0, "stdout:\n{stdout}");
    assert_eq!(summary.ignored, 0, "stdout:\n{stdout}");
    assert_eq!(
        summary.passed, 7,
        "expected exactly 7 selected tests in the generated crate; stdout:\n{stdout}"
    );
}

/// The generated crate depends on nothing but the Rust standard library --
/// no path dependency on the `semaprax` workspace crate, no crates.io
/// dependency at all -- so it builds and runs from a directory this
/// checkout's own workspace never sees.
#[test]
fn generated_crate_declares_no_workspace_or_external_dependency() {
    let (input, output) = shapes();
    let binding = fixture_binding();
    let consumer =
        generate_rust_calling_consumer(FIXTURE_DESCRIPTOR_BYTES, &binding, &input, &output)
            .expect("a well-formed shape must generate");
    let (_, cargo_toml) = consumer
        .files()
        .iter()
        .find(|(name, _)| name == "Cargo.toml")
        .expect("Cargo.toml must be generated");
    assert!(
        !cargo_toml.contains("[dependencies]") && !cargo_toml.contains("semaprax"),
        "the generated crate must declare no dependency at all:\n{cargo_toml}"
    );
}
