import assert from "node:assert/strict";
import { security } from "./security.mjs";
import { loadState, stateSchema, constraintErrors } from "./state.mjs";
let now = 0;
const guard = security({ now: () => now });
const anonymous = { headers: {} }, issued = guard.issue(anonymous);
const request = { headers: { cookie: issued.cookie.split(";")[0], "x-csrf-token": issued.token } };
assert.equal(guard.valid(request), true);
assert.equal(guard.valid({ headers: { cookie: request.headers.cookie } }), false);
assert.equal(guard.valid({ headers: { ...request.headers, "x-csrf-token": "0".repeat(64) } }), false);
const signed = { headers: { ...request.headers, cookie: request.headers.cookie + "; sid=" + "a".repeat(64) } };
assert.equal(guard.valid(signed), false, "anonymous token cannot authorize a signed-in session");
signed.headers["x-csrf-token"] = guard.issue(signed).token;
assert.equal(guard.valid(signed), true);
assert.equal(guard.valid({ headers: { ...signed.headers, cookie: request.headers.cookie + "; sid=" + "b".repeat(64) } }), false);
for (let n = 0; n < 5; n++) assert.equal(guard.attempt("one", "alice"), true);
assert.equal(guard.attempt("two", "alice"), false, "login limit survives changing IP");
for (let n = 0; n < 15; n++) assert.equal(guard.attempt("one", "user" + n), true);
assert.equal(guard.attempt("one", "fresh"), false, "IP limit survives changing login");
now = 60000; assert.equal(guard.attempt("one", "alice"), true);
const field = (name) => ({ name, type: "int" });
const booking = { name: "Booking", path: "booking", fields: [field("room"), field("start"), field("end")], constraints: [{ name: "no_overlap", other: "booking", fields: ["start"], test: (r, o) => r.room !== o.room || r.end <= o.start || r.start >= o.end }] };
const tables = new Map([["booking", { ent: booking, rows: new Map([[1n, { id: 1n, room: 1n, start: 0n, end: 10n }]]), next: 2n }]]);
assert.deepEqual(constraintErrors(tables), []);
assert.equal(constraintErrors(tables, { path: "booking", id: 2n, row: { id: 2n, room: 1n, start: 9n, end: 12n } }).length, 1);
assert.deepEqual(constraintErrors(tables, { path: "booking", id: 2n, row: { id: 2n, room: 1n, start: 10n, end: 12n } }), []);
assert.equal(tables.get("booking").rows.size, 1, "candidate checks cannot publish rows");
const child = { name: "Child", path: "child", fields: [field("value")], constraints: [{ name: "limit", other: "booking", fields: ["value"], test: (r, o) => r.value <= o.end }] };
tables.set("child", { ent: child, rows: new Map([[1n, { id: 1n, value: 8n }]]), next: 2n });
assert.equal(constraintErrors(tables, { path: "booking", id: 1n, row: { id: 1n, room: 1n, start: 0n, end: 7n } }).length, 1, "incoming row changes recheck dependent entities");
const oldEntity = { name: "Item", path: "item", fields: [field("begin")] };
const entity = { name: "Item", path: "item", fields: [field("start"), { name: "label", type: "string" }], migrations: [{ field: "start", inputs: [field("begin")], value: (o) => o.begin + 1n }, { field: "label", inputs: [], value: () => "new" }] };
const bytes = JSON.stringify({ version: 2, schema: stateSchema([oldEntity], {}), next: { item: "100" }, rows: { item: [{ id: "3", begin: "41" }] } });
const state = () => new Map([["item", { ent: entity, rows: new Map(), next: 1n }]]);
assert.throws(() => loadState(bytes, state(), {}, null, false), /schema changed/);
const target = state(); assert.equal(loadState(bytes, target, {}, null, true), true);
assert.deepEqual(target.get("item").rows.get(3n), Object.assign(Object.create(null), { id: 3n, start: 42n, label: "new" }));
assert.equal(target.get("item").next, 100n);
const failing = state(); failing.get("item").ent = { ...entity, rules: [{ fields: ["start"], text: "limit", test: (r) => r.start < 1n }] };
assert.throws(() => loadState(bytes, failing, {}, null, true), /constraints fail/);
assert.equal(failing.get("item").rows.size, 0, "failed migration publishes no state");
const missing = state(); missing.get("item").ent = { ...entity, migrations: [] };
assert.throws(() => loadState(bytes, missing, {}, null, true), /explicit migration/);
const trap = state(); trap.get("item").ent = { ...entity, migrations: [{ field: "start", inputs: [field("begin")], value: () => { throw new Error("overflow"); } }, entity.migrations[1]] };
assert.throws(() => loadState(bytes, trap, {}, null, true), /migration failed/);
const badId = JSON.stringify({ version: 1, next: { item: "4" }, rows: { item: [{ id: "3", start: "1", label: "x" }, { id: "3", start: "2", label: "y" }] } });
assert.throws(() => loadState(badId, state(), {}, null, false), /invalid stored row/);
const protoField = { name: "__proto__", type: "string" };
const protoBefore = { name: "Proto", path: "proto", fields: [protoField] };
const protoAfter = { ...protoBefore, fields: [protoField, { name: "marker", type: "string" }], migrations: [{ field: "__proto__", inputs: [protoField], value: (o) => o.__proto__ + "!" }, { field: "marker", inputs: [], value: () => "new" }] };
const protoBytes = JSON.stringify({ version: 2, schema: stateSchema([protoBefore], {}), next: { proto: "2" }, rows: { proto: [JSON.parse('{"id":"1","__proto__":"text"}')] } });
const protoTarget = new Map([["proto", { ent: protoAfter, rows: new Map(), next: 1n }]]);
assert.equal(loadState(protoBytes, protoTarget, {}, null, true), true);
assert.deepEqual(protoTarget.get("proto").rows.get(1n), Object.assign(Object.create(null), JSON.parse('{"__proto__":"text!","marker":"new"}'), { id: 1n }));
console.log("v3 runtime contracts passed");
