//! Adapter files shipped inside the binary (HN-07). The list is generated by
//! `scripts/gen_harness_assets.sh` from `packages/semaprax-harness-adapters`
//! (tests, evidence, research, fixtures and caches are excluded) and embedded
//! with `include_bytes!`, so a distribution works when no checkout exists.
//! Setup materializes the bundle into the content-addressed artifact store
//! (`<home>/artifacts/<hex>`, the same store skills use) and adopts from there.

mod list {
    include!("assets_list.rs");
}

use crate::diag::{HarnessDiagnostic, HarnessResult};
use crate::skills::inventory::{Bounds, FileKind, Inventory, InventoryEntry, ScanRules};
use crate::skills::snapshot::{self, Snapshot};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};

static SERIAL: AtomicUsize = AtomicUsize::new(0);

/// Shipped repository providers: (short name, bundle directory).
pub const PROVIDERS: &[(&str, &str)] =
    &[("graft", "graft"), ("graphify", "graphify"), ("rtk", "rtk")];

/// (relative path, exact bytes) of every embedded adapter file, path-sorted.
pub fn files() -> &'static [(&'static str, &'static [u8])] {
    list::FILES
}

fn inventory() -> HarnessResult<Inventory> {
    Inventory::new(
        files()
            .iter()
            .map(|(p, b)| InventoryEntry {
                path: (*p).to_string(),
                kind: FileKind::AdapterCode,
                bytes: b.len() as u64,
                sha256: format!(
                    "sha256:{}",
                    Sha256::digest(b)
                        .iter()
                        .map(|x| format!("{x:02x}"))
                        .collect::<String>()
                ),
            })
            .collect(),
    )
}

/// Artifact-v2 digest the bundle is addressed by in the store.
pub fn bundle_digest() -> HarnessResult<String> {
    Ok(inventory()?.digest())
}

fn bad(msg: impl Into<String>) -> HarnessDiagnostic {
    HarnessDiagnostic::new("SPX-HPB063", msg)
}

/// The `files/` directory the bundle is (or would be) published at, without writing.
pub fn expected_files_dir(home: &Path) -> HarnessResult<PathBuf> {
    Ok(snapshot::snapshot_dir(&home.join("artifacts"), &bundle_digest()?)?.join("files"))
}

/// Materialize the bundle (idempotent; a valid existing snapshot is reused).
pub fn materialize(home: &Path) -> HarnessResult<Snapshot> {
    let store = home.join("artifacts");
    let want = bundle_digest()?;
    if let Ok(snap) = snapshot::open(&store, &want) {
        return Ok(snap);
    }
    let scratch = home.join("tmp");
    let tmp = scratch.join(format!(
        "assets-{}-{}",
        std::process::id(),
        SERIAL.fetch_add(1, Ordering::SeqCst)
    ));
    let io = |e: std::io::Error| bad(format!("cannot stage the bundled adapters: {e}"));
    let _ = std::fs::remove_dir_all(&tmp);
    let result = (|| {
        for (rel, bytes) in files() {
            let to = tmp.join(rel);
            std::fs::create_dir_all(to.parent().unwrap_or(&tmp)).map_err(io)?;
            std::fs::write(&to, bytes).map_err(io)?;
        }
        snapshot::publish(
            &store,
            &tmp,
            &ScanRules::adapter(Vec::new()),
            &Bounds::ADAPTER,
        )
    })();
    let _ = std::fs::remove_dir_all(&tmp);
    let snap = result?;
    if snap.digest != want {
        return Err(bad(format!(
            "bundled adapters materialized as {} but the binary records {want}",
            snap.digest
        )));
    }
    Ok(snap)
}

/// Descriptor path of a shipped provider inside a materialized (or expected) bundle dir.
pub fn descriptor_in(files_dir: &Path, short: &str) -> Option<PathBuf> {
    let (_, dir) = PROVIDERS.iter().find(|(n, _)| *n == short)?;
    Some(files_dir.join(dir).join("harness-provider.json"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn list_is_sorted_and_excludes_non_runtime_files() {
        let f = files();
        assert!(f.windows(2).all(|w| w[0].0 < w[1].0));
        for (p, _) in f {
            assert!(
                !p.contains("/test") && !p.contains("EVIDENCE") && !p.contains("RESEARCH"),
                "{p}"
            );
        }
        assert!(f.iter().any(|(p, _)| *p == "graft/adapter.mjs"));
        assert!(f
            .iter()
            .any(|(p, _)| *p == "sdk/python/semaprax_harness_adapter.py"));
    }

    /// The checked-in list matches the checkout: no shipped adapter file is missing or stale.
    #[test]
    fn list_matches_the_checkout() {
        let root =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/semaprax-harness-adapters");
        if !root.is_dir() {
            return;
        }
        for (p, bytes) in files() {
            assert_eq!(
                std::fs::read(root.join(p)).unwrap(),
                *bytes,
                "{p} drifted; run scripts/gen_harness_assets.sh"
            );
        }
        fn walk(dir: &Path, rel: &str, out: &mut Vec<String>) {
            for e in std::fs::read_dir(dir).unwrap().flatten() {
                let name = e.file_name().to_string_lossy().into_owned();
                let r = format!("{rel}/{name}");
                if e.path().is_dir() {
                    if ![
                        "test",
                        "tests",
                        "tools",
                        "fixtures",
                        "__pycache__",
                        "node_modules",
                    ]
                    .contains(&name.as_str())
                    {
                        walk(&e.path(), &r, out);
                    }
                } else if !(name.starts_with("EVIDENCE")
                    || name.starts_with("RESEARCH")
                    || name.starts_with("test_")
                    || name.ends_with(".pyc")
                    || name == ".DS_Store")
                {
                    out.push(r.trim_start_matches('/').to_string());
                }
            }
        }
        let mut found = Vec::new();
        for r in [
            "graft",
            "graphify",
            "rtk",
            "systemone",
            "examples/source-index-python",
            "sdk/python",
            "sdk/node",
        ] {
            walk(&root.join(r), r, &mut found);
        }
        found.sort();
        let listed: Vec<String> = files().iter().map(|(p, _)| (*p).to_string()).collect();
        assert_eq!(found, listed, "run scripts/gen_harness_assets.sh");
    }

    #[test]
    fn digest_is_stable_and_descriptors_parse() {
        assert_eq!(bundle_digest().unwrap(), bundle_digest().unwrap());
        for (short, dir) in PROVIDERS {
            let (_, b) = files()
                .iter()
                .find(|(p, _)| *p == format!("{dir}/harness-provider.json"))
                .unwrap();
            let d = crate::contract::Descriptor::parse(b).unwrap();
            assert!(!d.provider_id.is_empty(), "{short}");
        }
    }
}
