//! Continued Intent production descendants included by every authority scan.

pub(super) const SOURCES: &[(&str, &str)] = &[
    (
        "interpreter/resumable/owned_frame/registered_stage/live_run/wait/continued/model/authorize/effect/prepared/intent.rs",
        include_str!("../../../interpreter/resumable/owned_frame/registered_stage/live_run/wait/continued/model/authorize/effect/prepared/intent.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/continued_intent.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/continued_intent.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/continued_intent/funnel.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/continued_intent/funnel.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/owned_effect/consumed/reduce_hold/turn_effect/intent.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/owned_effect/consumed/reduce_hold/turn_effect/intent.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/candidate/continued_intent.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/candidate/continued_intent.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent.rs"),
    ),
    (
        "interpreter/resumable/owned_frame/registered_stage/live_run/wait/continued/model/authorize/effect/prepared/intent/dispatch.rs",
        include_str!("../../../interpreter/resumable/owned_frame/registered_stage/live_run/wait/continued/model/authorize/effect/prepared/intent/dispatch.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/continued_settlement.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/continued_settlement.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/continued_settlement/funnel.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/continued_settlement/funnel.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/append/owned_effect/consumed/reduce_hold/turn_effect/intent/settlement.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/append/owned_effect/consumed/reduce_hold/turn_effect/intent/settlement.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/candidate/continued_settlement.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/candidate/continued_settlement.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch/settlement.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch/settlement.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch/settlement.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch/settlement.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch/settlement/cleanup.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/observe/settlement/carry/start/prepared/model/authorize/effect/prepared/intent/dispatch/settlement/cleanup.rs"),
    ),
    (
        "interpreter/resumable/owned_frame/registered_stage/effect/live_append/settlement/cleanup/continued_guard.rs",
        include_str!("../../../interpreter/resumable/owned_frame/registered_stage/effect/live_append/settlement/cleanup/continued_guard.rs"),
    ),
    (
        "live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch/settlement/cleanup.rs",
        include_str!("../../../live_invocation/source_journal/owned_wait_v8/live_upstream/effect/authorization/prepared/intent/dispatch/settlement/cleanup/reduce/step/continue/settlement/start/model/authorize/effect/prepared/intent/dispatch/settlement/cleanup.rs"),
    ),
];
