//! Authored, unrun standalone SDK evidence. This explicit gate requires installed tools.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use std::fs;
use std::path::PathBuf;

use semaprax_native_rust_owned_data_package::{
    build_and_publish, provider_sha256, PackageMode, PackagePlan,
};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/native_owned_data_string_settlement_v1/subject.rs"]
mod subject;

const MANIFEST: &str = r#"[package]
name = "standalone-string-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;

// The generated SDK has no dependencies. This literal lock cannot acquire
// repository source crates or registry packages through lock regeneration.
const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"

[[package]]
name = "standalone-string-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]
"#;

fn required_tool(name: &str) {
    let value = PathBuf::from(
        std::env::var_os(name)
            .unwrap_or_else(|| panic!("selected SDK gate requires provisioned absolute {name}")),
    );
    assert!(value.is_absolute(), "{name} must be absolute");
    assert!(value.is_file(), "{name} must name an installed file");
    // The real builder independently acquires its held tool authority.
}

#[test]
#[ignore = "requires provisioned absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo toolchain; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_standalone_owned_data_string_sdk_consumer() {
    required_tool("CLANG");
    required_tool("SEMAPRAX_ARCHIVER");
    let root = std::env::temp_dir().join(format!(
        "semaprax-owned-data-string-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained SDK evidence fixture: {}", root.display());
    let artifact = subject::artifact(false);
    let hash = provider_sha256(artifact.provider.as_bytes());
    let expected_descriptor = artifact.descriptor.clone();
    let expected_digest = artifact.digest.clone();
    let plan = PackagePlan::new(
        artifact.descriptor,
        artifact.digest,
        artifact.selected,
        artifact.provider.into_bytes(),
        hash,
        PackageMode::StandaloneEvidence,
    );
    let sdk = root.join("sdk");
    let bundle = build_and_publish(plan, &sdk).expect("real held-tool SDK build and publication");
    assert_eq!(bundle.output_directory(), sdk);
    assert_eq!(bundle.descriptor_digest(), expected_digest);
    assert_eq!(
        fs::read(sdk.join("descriptor.json")).unwrap(),
        expected_descriptor
    );
    assert_eq!(
        bundle.crate_name(),
        "semaprax-generated-native-rust-owned-data-sdk"
    );

    let consumer = root.join("consumer");
    fs::create_dir(&consumer).unwrap();
    fs::create_dir(consumer.join("src")).unwrap();
    fs::write(consumer.join("Cargo.toml"), MANIFEST).unwrap();
    fs::write(consumer.join("Cargo.lock"), LOCK).unwrap();
    fs::write(
        consumer.join("src/main.rs"),
        include_str!("native_owned_data_string_sdk_v1/consumer.rs"),
    )
    .unwrap();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(consumer.join("Cargo.toml"))
        .current_dir(&consumer)
        .output()
        .expect("provisioned Cargo must execute the external consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(output.stdout, b"standalone-owned-data-string-sdk-ok\n");
    assert_eq!(
        fs::read(consumer.join("Cargo.lock")).unwrap(),
        LOCK.as_bytes()
    );
    // Retain both successful and failed fixtures for explicit host inspection;
    // this gate has no recursive cleanup authority over a generated Cargo tree.
}
