//! Authored external mixed-arity SDK consumer; not a native-context lifetime proof.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
#![forbid(unsafe_code)]

use semaprax::project::{with_authenticated_project, PublicApiSubject};
use semaprax_native_rust_owned_data_package::{provider_sha256, HostTarget};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "../../../tests/support/owned_mixed_arity_product.rs"]
mod subject;

const MANIFEST: &str = "semaprax.native-rust-owned-data-sdk.json";
const CONSUMER_MANIFEST: &str = r#"[package]
name = "mixed-arity-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;
const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "mixed-arity-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn read_package(path: &Path) -> BTreeMap<String, Vec<u8>> {
    let archive = HostTarget::current()
        .expect("supported SDK host")
        .archive_name();
    let mut expected = vec![
        "Cargo.toml",
        "build.rs",
        "descriptor.json",
        "lib.rs",
        "owned_data_ffi.rs",
        MANIFEST,
        archive,
    ];
    expected.sort_unstable();
    let mut names = fs::read_dir(path)
        .unwrap()
        .map(|row| row.unwrap().file_name().into_string().unwrap())
        .collect::<Vec<_>>();
    names.sort();
    assert_eq!(names, expected);
    expected
        .into_iter()
        .map(|name| {
            let file = path.join(name);
            let metadata = fs::symlink_metadata(&file).unwrap();
            assert!(metadata.is_file() && !metadata.file_type().is_symlink());
            #[cfg(windows)]
            {
                use std::os::windows::fs::MetadataExt as _;
                assert_eq!(metadata.file_attributes() & 0x400, 0);
            }
            assert!(metadata.len() <= 16 * 1024 * 1024);
            (name.to_owned(), fs::read(file).unwrap())
        })
        .collect()
}

fn identities(bytes: &[u8]) {
    let descriptor: serde_json::Value = serde_json::from_slice(bytes).unwrap();
    assert_eq!(descriptor["schema"], "semaprax.public-owned-data-api.v1");
    let exports = descriptor["exports"].as_array().unwrap();
    assert_eq!(exports.len(), 9);
    let types = [
        "i64",
        "bool",
        "borrow-str",
        "borrow-slice-u8",
        "i64",
        "bool",
        "borrow-str",
        "borrow-slice-u8",
    ];
    for (arity, export) in exports.iter().enumerate() {
        assert_eq!(export["stable_id"], format!("mixed.arity{arity}"));
        assert_eq!(
            export["rust_method_name"],
            format!("spx_mixed_dot_arity{arity}")
        );
        assert_eq!(export["result"], "owned-bytes");
        let parameters = export["parameters"].as_array().unwrap();
        assert_eq!(parameters.len(), arity);
        for (ordinal, parameter) in parameters.iter().enumerate() {
            assert_eq!(parameter["ordinal"], ordinal);
            assert_eq!(parameter["source_name"], format!("p{ordinal}"));
            assert_eq!(parameter["type"], types[ordinal]);
        }
    }
    assert_eq!(descriptor["limits"]["max_parameters"], 8);
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).unwrap()
}

fn verify_package(path: &Path, descriptor: &[u8], digest: &str, provider: &[u8]) {
    let target = HostTarget::current().unwrap();
    let archive = target.archive_name();
    let files = read_package(path);
    assert_eq!(files["descriptor.json"], descriptor);
    assert!(!files[archive].is_empty());
    let rows = files
        .iter()
        .filter(|(name, _)| name.as_str() != MANIFEST)
        .map(|(name, bytes)| {
            format!(
                "{{\"path\":{},\"bytes\":{},\"sha256\":{}}}",
                quote(name),
                bytes.len(),
                quote(&provider_sha256(bytes))
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    // Exact canonical manifest/file binding to retained Project HIR. This is
    // not an independent proof that the archive implements that HIR.
    let expected = format!("{{\"schema\":\"semaprax.native-rust-owned-data-sdk.v1\",\"crate\":{{\"name\":\"semaprax-generated-native-rust-owned-data-sdk\",\"version\":\"0.1.0\"}},\"target\":{},\"descriptor\":{{\"schema\":\"semaprax.public-owned-data-api.v1\",\"bytes\":{},\"digest\":{}}},\"provider\":{{\"abi\":\"opaque-handle.v1\",\"archive\":{},\"descriptor_digest\":{},\"source_sha256\":{},\"operations\":[\"len\",\"copy\",\"drop\"]}},\"files\":[{rows}],\"limits\":{{\"max_borrowed_input_bytes\":65536,\"max_owned_output_bytes\":65536,\"max_handles\":4096,\"exact_package_files\":7}},\"nonclaims\":[\"no_raw_handle_or_context_public_api\",\"no_allocator_transfer\",\"no_allocator_oom_abort_or_panic_recovery_proof\",\"no_send_sync\"]}}\n",
        quote(target.triple()), descriptor.len(), quote(digest), quote(archive),
        quote(digest), quote(&provider_sha256(provider)));
    assert_eq!(files[MANIFEST], expected.as_bytes());
}

fn consumer(root: &Path) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    let source = include_str!("project_owned_mixed_arity_sdk_v1/consumer.rs");
    let inputs = [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ];
    for (name, text) in inputs {
        fs::write(directory.join(name), text).unwrap();
    }
    let target = native_rust_target::CargoTarget::new();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path())
        .output()
        .expect("provisioned external mixed-arity consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(output.stdout, b"mixed-arity-sdk-ok\n");
    for (name, text) in inputs {
        assert_eq!(fs::read(directory.join(name)).unwrap(), text.as_bytes());
    }
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_mixed_arity_publish_and_run() {
    for name in ["CLANG", "SEMAPRAX_ARCHIVER"] {
        let path = PathBuf::from(
            std::env::var_os(name)
                .unwrap_or_else(|| panic!("selected mixed-arity SDK gate requires {name}")),
        );
        assert!(path.is_absolute() && path.is_file(), "invalid {name}");
    }
    let root = std::env::temp_dir().join(format!(
        "semaprax-mixed-arity-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained mixed-arity SDK fixture: {}", root.display());
    let project = root.join("project");
    fs::create_dir(&project).unwrap();
    let manifest = subject::write_project(&project, 8);
    let sources = ["semaprax.toml", "src/app.spx", "src/tests.spx"]
        .map(|name| (name, fs::read(project.join(name)).unwrap()));
    let sdk = root.join("sdk");
    with_authenticated_project(&manifest, |snapshot| {
        snapshot.check()?;
        let revision = snapshot.retain_revision();
        let descriptor = revision.public_api_descriptor()?;
        let bytes = descriptor.canonical_bytes();
        let digest = descriptor.digest();
        identities(&bytes);
        let provider = semaprax::codegen::emit_project_v8_native_owned_data_provider(
            revision.entry_program(),
            revision.manifest().web_exports(),
            PublicApiSubject {
                project_schema: revision.manifest().schema(),
                project_revision: revision.project_revision(),
                workspace_revision: revision.workspace_revision(),
                project_graph_digest: revision.semantic_graph_digest(),
            },
            &bytes,
            &digest,
        )
        .map_err(|error| vec![error])?;
        assert_eq!(provider.descriptor(), bytes);
        assert_eq!(provider.descriptor_digest(), digest);
        semaprax_toolchain::build_rust(snapshot, &sdk)?;
        verify_package(&sdk, &bytes, &digest, provider.source().as_bytes());
        Ok(())
    })
    .unwrap();
    let published = read_package(&sdk);
    consumer(&root);
    assert_eq!(read_package(&sdk), published);
    for (name, bytes) in sources {
        assert_eq!(fs::read(project.join(name)).unwrap(), bytes);
    }
    // Retain evidence. Two reused safe SDK objects do not prove persistence of
    // one native context or exact physical allocation/free; the C gate owns that.
}
