//! Authored, unrun provisioned Project-v9 publication and external Rust evidence.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use std::fs;
use std::path::{Path, PathBuf};

use semaprax::project::{with_authenticated_project, PublicApiSubject};

#[path = "../../../tests/support/flat_record_product.rs"]
mod flat_record_product;
#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "project_flat_record_sdk_v1/package.rs"]
mod package;

const CONSUMER_MANIFEST: &str = r#"[package]
name = "flat-record-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "flat-record-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn required_tool(name: &str) {
    let path = PathBuf::from(std::env::var_os(name).unwrap_or_else(|| {
        panic!("selected Project-v9 SDK gate requires provisioned absolute {name}")
    }));
    assert!(path.is_absolute() && path.is_file(), "invalid {name}");
    // The actual publisher independently acquires the installed-tool authority.
}

fn source_snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
    [
        "semaprax.toml",
        "src/app.spx",
        "src/left.spx",
        "src/right.spx",
        "src/tests.spx",
    ]
    .into_iter()
    .map(|name| {
        let path = root.join(name);
        let bytes = fs::read(&path).unwrap();
        (path, bytes)
    })
    .collect()
}

fn consumer(root: &Path) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    fs::write(directory.join("Cargo.toml"), CONSUMER_MANIFEST).unwrap();
    fs::write(directory.join("Cargo.lock"), LOCK).unwrap();
    fs::write(
        directory.join("src/main.rs"),
        include_str!("project_flat_record_sdk_v1/consumer.rs"),
    )
    .unwrap();
    let target = native_rust_target::CargoTarget::new();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path())
        .output()
        .expect("run provisioned external safe Rust consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(output.stdout, b"project-flat-record-sdk-ok\n");
    assert_eq!(
        fs::read(directory.join("Cargo.lock")).unwrap(),
        LOCK.as_bytes()
    );
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_project_flat_records_publish_and_run_unchanged_consumer() {
    required_tool("CLANG");
    required_tool("SEMAPRAX_ARCHIVER");
    let root = std::env::temp_dir().join(format!(
        "semaprax-flat-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained Project-v9 SDK fixture: {}", root.display());
    let mut original = None;
    for renamed in [false, true] {
        let case = root.join(if renamed { "renamed" } else { "original" });
        fs::create_dir(&case).unwrap();
        let project = case.join("project");
        fs::create_dir(&project).unwrap();
        let manifest = flat_record_product::write_project(&project, renamed);
        let before = source_snapshot(&project);
        let sdk = case.join("sdk");
        let descriptor = with_authenticated_project(&manifest, |snapshot| {
            snapshot.check()?;
            let revision = snapshot.retain_revision();
            let descriptor = revision.flat_owned_record_api_descriptor()?;
            let provider = semaprax::codegen::emit_project_v9_native_flat_owned_record_provider(
                revision.entry_program(),
                revision.manifest().web_exports(),
                PublicApiSubject {
                    project_schema: revision.manifest().schema(),
                    project_revision: revision.project_revision(),
                    workspace_revision: revision.workspace_revision(),
                    project_graph_digest: revision.semantic_graph_digest(),
                },
                &descriptor.canonical_bytes(),
                &descriptor.digest(),
            )
            .map_err(|error| vec![error])?;
            // This is the real private host, not an injected rejecting publisher.
            semaprax_toolchain::build_rust(snapshot, &sdk)?;
            package::verify(&sdk, &descriptor, provider.source().as_bytes());
            Ok(descriptor)
        })
        .unwrap();
        package::identities(&descriptor, renamed);
        if let Some(previous) = &original {
            package::rename_preserves_ids(previous, &descriptor);
        } else {
            original = Some(descriptor.clone());
        }
        let published = package::read(&sdk);
        let siblings = package::names(&case);
        let errors = with_authenticated_project(&manifest, |snapshot| {
            semaprax_toolchain::build_rust(snapshot, &sdk)
        })
        .unwrap_err();
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].code, "SPX-I234");
        assert_eq!(
            package::read(&sdk),
            published,
            "no-clobber publication changed SDK"
        );
        assert_eq!(
            package::names(&case),
            siblings,
            "collision left a new stage"
        );
        consumer(&case);
        assert_eq!(
            package::read(&sdk),
            published,
            "consumer changed SDK inputs"
        );
        assert_eq!(
            source_snapshot(&project),
            before,
            "source changed during build/consumer"
        );
    }
    // Keep source, packages and consumers for inspection. The only Cargo-tree
    // cleanup belongs to the existing fresh short-target guard above.
}
