//! Mixed-borrow published v8/v9 safe Rust consumer evidence.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use semaprax::project::{with_authenticated_project, PublicApiSubject};
use std::fs;
use std::path::{Path, PathBuf};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "project_owned_tuple_sdk_v1/package.rs"]
mod package;
#[path = "../../../tests/support/owned_tuple_product.rs"]
mod subject;

const CONSUMER_MANIFEST: &str = r#"[package]
name = "owned-tuple-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[features]
flat = []

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;
const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "owned-tuple-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn required_tool(name: &str) {
    let path = PathBuf::from(std::env::var_os(name).unwrap_or_else(|| {
        panic!("selected mixed-borrow SDK gate requires provisioned absolute {name}")
    }));
    assert!(path.is_absolute() && path.is_file(), "invalid {name}");
}

fn source_snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
    ["semaprax.toml", "src/app.spx", "src/tests.spx"]
        .into_iter()
        .map(|name| {
            let path = root.join(name);
            let bytes = fs::read(&path).unwrap();
            (path, bytes)
        })
        .collect()
}

fn consumer(root: &Path, flat: bool) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    let source = include_str!("project_owned_tuple_sdk_v1/consumer.rs");
    for (name, bytes) in [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ] {
        fs::write(directory.join(name), bytes).unwrap();
    }
    let target = native_rust_target::CargoTarget::new();
    let mut command = native_rust_cargo::cargo_command();
    command
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path());
    if flat {
        command.args(["--features", "flat"]);
    }
    let output = command
        .output()
        .expect("run provisioned external mixed-borrow consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        output.stdout,
        format!(
            "project-owned-tuple-sdk-ok:{}\n",
            if flat { "v9" } else { "v8" }
        )
        .as_bytes()
    );
    for (name, bytes) in [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ] {
        assert_eq!(fs::read(directory.join(name)).unwrap(), bytes.as_bytes());
    }
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_v8_v9_mixed_borrow_tuples_publish_and_run() {
    required_tool("CLANG");
    required_tool("SEMAPRAX_ARCHIVER");
    let root = std::env::temp_dir().join(format!(
        "semaprax-tuple-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained mixed-borrow SDK fixture: {}", root.display());
    for flat in [false, true] {
        let case = root.join(if flat { "v9" } else { "v8" });
        fs::create_dir(&case).unwrap();
        let project = case.join("project");
        fs::create_dir(&project).unwrap();
        let manifest = subject::write_project(&project, flat);
        let before = source_snapshot(&project);
        let sdk = case.join("sdk");
        with_authenticated_project(&manifest, |snapshot| {
            snapshot.check()?;
            let revision = snapshot.retain_revision();
            let subject = PublicApiSubject {
                project_schema: revision.manifest().schema(),
                project_revision: revision.project_revision(),
                workspace_revision: revision.workspace_revision(),
                project_graph_digest: revision.semantic_graph_digest(),
            };
            let (bytes, digest, provider) = if flat {
                let descriptor = revision.flat_owned_record_api_descriptor()?;
                let bytes = descriptor.canonical_bytes();
                let digest = descriptor.digest();
                let provider =
                    semaprax::codegen::emit_project_v9_native_flat_owned_record_provider(
                        revision.entry_program(),
                        revision.manifest().web_exports(),
                        subject,
                        &bytes,
                        &digest,
                    )
                    .map_err(|error| vec![error])?;
                (bytes, digest, provider)
            } else {
                let descriptor = revision.public_api_descriptor()?;
                let bytes = descriptor.canonical_bytes();
                let digest = descriptor.digest();
                let provider = semaprax::codegen::emit_project_v8_native_owned_data_provider(
                    revision.entry_program(),
                    revision.manifest().web_exports(),
                    subject,
                    &bytes,
                    &digest,
                )
                .map_err(|error| vec![error])?;
                (bytes, digest, provider)
            };
            assert_eq!(provider.descriptor(), bytes);
            assert_eq!(provider.descriptor_digest(), digest);
            package::identities(&bytes, flat);
            // Actual source-authenticated private host; no synthetic PackagePlan.
            semaprax_toolchain::build_rust(snapshot, &sdk)?;
            package::verify(&sdk, &bytes, &digest, provider.source().as_bytes(), flat);
            Ok(())
        })
        .unwrap();
        let published = package::read(&sdk);
        consumer(&case, flat);
        assert_eq!(
            package::read(&sdk),
            published,
            "consumer changed SDK inputs"
        );
        assert_eq!(source_snapshot(&project), before, "source changed");
    }
    // Retain all inputs/packages/consumers. Existing CargoTarget owns only its
    // short build tree. Consumer results are not pre-entry/allocation traces or
    // evidence of native-context persistence across safe calls.
}
