//! Authored, unrun provisioned safe-Rust exact String result-capacity evidence.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use std::fs;
use std::path::{Path, PathBuf};

use semaprax::project::{with_authenticated_project, PublicApiResultType, PublicApiSubject};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "../../../tests/support/owned_utf8_capacity.rs"]
mod owned_utf8_capacity;
#[path = "support/owned_utf8_package.rs"]
mod package;

const CONSUMER_MANIFEST: &str = r#"[package]
name = "owned-utf8-capacity-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "owned-utf8-capacity-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn required_tool(name: &str) {
    let path = PathBuf::from(std::env::var_os(name).unwrap_or_else(|| {
        panic!("selected Project-v10 String-capacity gate requires provisioned absolute {name}")
    }));
    assert!(path.is_absolute() && path.is_file(), "invalid {name}");
}

fn source_snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
    ["semaprax.toml", "src/app.spx", "src/tests.spx"]
        .into_iter()
        .map(|name| {
            let path = root.join(name);
            let bytes = fs::read(&path).unwrap();
            (path, bytes)
        })
        .collect()
}

fn consumer(root: &Path, byte_len: usize) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    let source = include_str!("project_owned_utf8_capacity_v1/consumer.rs");
    for (name, bytes) in [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ] {
        fs::write(directory.join(name), bytes).unwrap();
    }
    let target = native_rust_target::CargoTarget::new();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .arg("--")
        .arg(byte_len.to_string())
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path())
        .output()
        .expect("run provisioned external safe Rust capacity consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        output.stdout,
        format!("project-owned-utf8-capacity-ok:{byte_len}\n").as_bytes()
    );
    for (name, bytes) in [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ] {
        assert_eq!(fs::read(directory.join(name)).unwrap(), bytes.as_bytes());
    }
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_project_owned_utf8_exact_capacity_publishes_and_runs() {
    required_tool("CLANG");
    required_tool("SEMAPRAX_ARCHIVER");
    let root = std::env::temp_dir().join(format!(
        "semaprax-utf8-capacity-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!(
        "retained Project-v10 capacity SDK fixture: {}",
        root.display()
    );
    for byte_len in [65_535, 65_536] {
        let case = root.join(byte_len.to_string());
        fs::create_dir(&case).unwrap();
        let project = case.join("project");
        fs::create_dir(&project).unwrap();
        let manifest = owned_utf8_capacity::write_project(&project, byte_len);
        let before = source_snapshot(&project);
        let sdk = case.join("sdk");
        with_authenticated_project(&manifest, |snapshot| {
            snapshot.check()?;
            let revision = snapshot.retain_revision();
            let descriptor = revision.owned_utf8_api_descriptor()?;
            assert_eq!(descriptor.schema(), "semaprax.public-owned-utf8-api.v1");
            assert_eq!(descriptor.exports().len(), 1);
            let export = &descriptor.exports()[0];
            assert_eq!(export.stable_id().as_str(), "utf8.maximum");
            assert_eq!(export.rust_method_name(), "spx_utf8_dot_maximum");
            assert!(export.parameters().is_empty());
            assert_eq!(export.result(), PublicApiResultType::OwnedUtf8);
            assert_eq!(descriptor.limits().max_owned_output_bytes, 65_536);
            let provider = semaprax::codegen::emit_project_v10_native_owned_utf8_provider(
                revision.entry_program(),
                revision.manifest().web_exports(),
                PublicApiSubject {
                    project_schema: revision.manifest().schema(),
                    project_revision: revision.project_revision(),
                    workspace_revision: revision.workspace_revision(),
                    project_graph_digest: revision.semantic_graph_digest(),
                },
                &descriptor.canonical_bytes(),
                &descriptor.digest(),
            )
            .map_err(|error| vec![error])?;
            assert_eq!(provider.descriptor(), descriptor.canonical_bytes());
            assert_eq!(provider.descriptor_digest(), descriptor.digest());
            semaprax_toolchain::build_rust(snapshot, &sdk)?;
            package::verify(&sdk, &descriptor, provider.source().as_bytes());
            Ok(())
        })
        .unwrap();
        let published = package::read(&sdk);
        consumer(&case, byte_len);
        assert_eq!(
            package::read(&sdk),
            published,
            "consumer changed SDK inputs"
        );
        assert_eq!(source_snapshot(&project), before, "source changed");
    }
    // 65,537 bytes is an existing Project/Wasm admission rejection exercised
    // in the root capacity fixture, not an admitted native failure call.
    // Retain packages/source/consumers. Only the existing short Cargo target
    // guard cleans its own tree. Reused safe objects reinitialize closed native
    // contexts; this is not a native allocation-count or leak-trace oracle.
}
