//! Real published SDK values and recovery; not an allocator or destruction trace.
#![forbid(unsafe_code)]
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use semaprax::project::{with_authenticated_project, PublicApiSubject};
use std::fs;
use std::path::{Path, PathBuf};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "support/owned_bytes_package.rs"]
mod package;
#[path = "../../../tests/support/owned_inactive_product.rs"]
mod subject;

const CONSUMER_MANIFEST: &str = r#"[package]
name = "inactive-cleanup-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;
const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "inactive-cleanup-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn source_snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
    ["semaprax.toml", "src/app.spx", "src/tests.spx"]
        .into_iter()
        .map(|name| {
            let path = root.join(name);
            let bytes = fs::read(&path).unwrap();
            (path, bytes)
        })
        .collect()
}

fn identities(bytes: &[u8]) {
    let descriptor: serde_json::Value = serde_json::from_slice(bytes).unwrap();
    assert_eq!(descriptor["schema"], "semaprax.public-owned-data-api.v1");
    assert_eq!(descriptor["project_schema"], "semaprax.project.v8");
    let exports = descriptor["exports"].as_array().unwrap();
    assert_eq!(exports.len(), 2);
    for (export, (id, method, result)) in exports.iter().zip([
        (
            "inactive.maybe",
            "spx_inactive_dot_maybe",
            "option-owned-bytes",
        ),
        (
            "inactive.result",
            "spx_inactive_dot_result",
            "result-owned-bytes-i64",
        ),
    ]) {
        assert_eq!(export["stable_id"], id);
        assert_eq!(export["rust_method_name"], method);
        assert_eq!(export["result"], result);
        let parameters = export["parameters"].as_array().unwrap();
        assert_eq!(parameters.len(), 2);
        assert_eq!(parameters[0]["type"], "borrow-slice-u8");
        assert_eq!(parameters[1]["type"], "bool");
    }
    assert_eq!(descriptor["limits"]["max_borrowed_input_bytes"], 65_536);
    assert_eq!(descriptor["limits"]["max_owned_output_bytes"], 65_536);
}

fn consumer(root: &Path) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    let source = include_str!("project_owned_inactive_cleanup_sdk_v1/consumer.rs");
    let files = [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ];
    for (name, bytes) in files {
        use std::io::Write as _;
        fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(directory.join(name))
            .unwrap()
            .write_all(bytes.as_bytes())
            .unwrap();
    }
    let target = native_rust_target::CargoTarget::new();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path())
        .output()
        .expect("run provisioned inactive-cleanup SDK consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(output.stdout, b"inactive-cleanup-sdk-ok:192\n");
    for (name, bytes) in files {
        assert_eq!(fs::read(directory.join(name)).unwrap(), bytes.as_bytes());
    }
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_inactive_cleanup_publish_and_run() {
    for name in ["CLANG", "SEMAPRAX_ARCHIVER"] {
        let path = PathBuf::from(std::env::var_os(name).unwrap_or_else(|| {
            panic!("selected inactive-cleanup SDK gate requires absolute {name}")
        }));
        assert!(path.is_absolute() && path.is_file(), "invalid {name}");
    }
    let root = std::env::temp_dir().join(format!(
        "semaprax-inactive-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained inactive-cleanup SDK fixture: {}", root.display());
    let project = root.join("project");
    fs::create_dir(&project).unwrap();
    let manifest = subject::write_project(&project);
    let before = source_snapshot(&project);
    let sdk = root.join("sdk");
    with_authenticated_project(&manifest, |snapshot| {
        snapshot.check()?;
        let revision = snapshot.retain_revision();
        let descriptor = revision.public_api_descriptor()?;
        let bytes = descriptor.canonical_bytes();
        let digest = descriptor.digest();
        identities(&bytes);
        let provider = semaprax::codegen::emit_project_v8_native_owned_data_provider(
            revision.entry_program(),
            revision.manifest().web_exports(),
            PublicApiSubject {
                project_schema: revision.manifest().schema(),
                project_revision: revision.project_revision(),
                workspace_revision: revision.workspace_revision(),
                project_graph_digest: revision.semantic_graph_digest(),
            },
            &bytes,
            &digest,
        )
        .map_err(|error| vec![error])?;
        assert_eq!(provider.descriptor(), bytes);
        assert_eq!(provider.descriptor_digest(), digest);
        semaprax_toolchain::build_rust(snapshot, &sdk)?;
        package::verify(&sdk, &bytes, &digest, provider.source().as_bytes(), false);
        Ok(())
    })
    .unwrap();
    let published = package::read(&sdk);
    consumer(&root);
    assert_eq!(
        package::read(&sdk),
        published,
        "consumer changed SDK inputs"
    );
    assert_eq!(source_snapshot(&project), before, "source changed");
    // Retain inputs/packages/consumers; CargoTarget removes only its own build
    // tree. An external deadline owns process containment. Same SDK-object
    // recovery is not persistence of one provider context or exact-drop proof.
}
