//! Authored, unrun real Project-v10 publication and external safe Rust evidence.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use std::fs;
use std::path::{Path, PathBuf};

use semaprax::project::{with_authenticated_project, PublicApiSubject};

#[path = "../../../tests/support/native_rust_cargo.rs"]
mod native_rust_cargo;
#[path = "../../../tests/support/native_rust_target.rs"]
mod native_rust_target;
#[path = "../../../tests/support/owned_utf8_product.rs"]
mod owned_utf8_product;
#[path = "project_owned_utf8_sdk_v1/package.rs"]
mod package;

const CONSUMER_MANIFEST: &str = r#"[package]
name = "owned-utf8-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;

const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "owned-utf8-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

fn required_tool(name: &str) {
    let path = PathBuf::from(std::env::var_os(name).unwrap_or_else(|| {
        panic!("selected Project-v10 SDK gate requires provisioned absolute {name}")
    }));
    assert!(path.is_absolute() && path.is_file(), "invalid {name}");
    // The real lower publisher independently acquires installed-tool authority.
}

fn source_snapshot(root: &Path) -> Vec<(PathBuf, Vec<u8>)> {
    [
        "semaprax.toml",
        "src/app.spx",
        "src/left.spx",
        "src/right.spx",
        "src/tests.spx",
    ]
    .into_iter()
    .map(|name| {
        let path = root.join(name);
        let bytes = fs::read(&path).unwrap();
        (path, bytes)
    })
    .collect()
}

fn consumer(root: &Path) {
    let directory = root.join("consumer");
    fs::create_dir(&directory).unwrap();
    fs::create_dir(directory.join("src")).unwrap();
    fs::write(directory.join("Cargo.toml"), CONSUMER_MANIFEST).unwrap();
    fs::write(directory.join("Cargo.lock"), LOCK).unwrap();
    let source = include_str!("project_owned_utf8_sdk_v1/consumer.rs");
    fs::write(directory.join("src/main.rs"), source).unwrap();
    let target = native_rust_target::CargoTarget::new();
    let output = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(directory.join("Cargo.toml"))
        .current_dir(&directory)
        .env("CARGO_TARGET_DIR", target.path())
        .output()
        .expect("run provisioned external safe Rust UTF-8 consumer");
    assert!(
        output.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(output.stdout, b"project-owned-utf8-sdk-ok\n");
    for (name, expected) in [
        ("Cargo.toml", CONSUMER_MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/main.rs", source),
    ] {
        assert_eq!(fs::read(directory.join(name)).unwrap(), expected.as_bytes());
    }
}

#[test]
#[ignore = "requires absolute CLANG/SEMAPRAX_ARCHIVER and native Cargo; Windows also SEMAPRAX_VCTOOLS, INCLUDE, LIB, SEMAPRAX_LINKER"]
fn provisioned_project_owned_utf8_publishes_and_runs_unchanged_consumer() {
    required_tool("CLANG");
    required_tool("SEMAPRAX_ARCHIVER");
    let root = std::env::temp_dir().join(format!(
        "semaprax-utf8-sdk-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir(&root).unwrap();
    let root = root.canonicalize().unwrap();
    eprintln!("retained Project-v10 SDK fixture: {}", root.display());
    let mut original = None;
    for renamed in [false, true] {
        let case = root.join(if renamed { "renamed" } else { "original" });
        fs::create_dir(&case).unwrap();
        let project = case.join("project");
        fs::create_dir(&project).unwrap();
        let manifest = owned_utf8_product::write_project(&project, renamed);
        let before = source_snapshot(&project);
        let sdk = case.join("sdk");
        let descriptor = with_authenticated_project(&manifest, |snapshot| {
            snapshot.check()?;
            let revision = snapshot.retain_revision();
            package::helper_identities(revision.entry_program(), renamed);
            let descriptor = revision.owned_utf8_api_descriptor()?;
            let provider = semaprax::codegen::emit_project_v10_native_owned_utf8_provider(
                revision.entry_program(),
                revision.manifest().web_exports(),
                PublicApiSubject {
                    project_schema: revision.manifest().schema(),
                    project_revision: revision.project_revision(),
                    workspace_revision: revision.workspace_revision(),
                    project_graph_digest: revision.semantic_graph_digest(),
                },
                &descriptor.canonical_bytes(),
                &descriptor.digest(),
            )
            .map_err(|error| vec![error])?;
            assert_eq!(provider.descriptor(), descriptor.canonical_bytes());
            assert_eq!(provider.descriptor_digest(), descriptor.digest());
            // This invokes real Project recipe/provider replay and lower native
            // publication, not an injected plan or an intentionally failing host.
            semaprax_toolchain::build_rust(snapshot, &sdk)?;
            package::verify(&sdk, &descriptor, provider.source().as_bytes());
            Ok(descriptor)
        })
        .unwrap();
        package::identities(&descriptor);
        if let Some(previous) = &original {
            package::rename_preserves_ids(previous, &descriptor);
        } else {
            original = Some(descriptor.clone());
        }
        let published = package::read(&sdk);
        let siblings = package::names(&case);
        let errors = with_authenticated_project(&manifest, |snapshot| {
            semaprax_toolchain::build_rust(snapshot, &sdk)
        })
        .unwrap_err();
        assert_eq!(errors.len(), 1);
        assert_eq!(errors[0].code, "SPX-I234");
        assert_eq!(package::read(&sdk), published, "no-clobber changed SDK");
        assert_eq!(
            package::names(&case),
            siblings,
            "collision left a new stage"
        );
        consumer(&case);
        assert_eq!(
            package::read(&sdk),
            published,
            "consumer changed SDK inputs"
        );
        assert_eq!(source_snapshot(&project), before, "source changed");
    }
    // Source, SDK packages and consumer inputs remain for inspection. Only the
    // existing fresh short-target guard owns cleanup of its own Cargo tree.
}
