//! The deterministic string templates [`super::generate_typescript_calling_consumer`]
//! composes. Split from `typescript_calling.rs` itself only to keep that
//! file's own generator-contract logic short; every function here is a pure
//! byte-in/text-out renderer, exercised by [`super::tests`]. Mirrors
//! `rust_calling::render`'s own fixed-template/generated-per-shape split.

use std::fmt::Write as _;

use crate::public_generic_abi::wasm::binding::WasmProviderBindingV1;

use super::{field_name, RecordShape};

/// Line endings are normalized because a checkout may deliver these `.txt`
/// assets with CRLF -- `.gitattributes` pins them to LF, but a generator
/// that is only deterministic because of a checkout setting is not
/// deterministic. Matches `public_generic_consumer::template`'s own
/// convention exactly.
fn template(text: &str) -> String {
    text.replace("\r\n", "\n")
}

pub(super) fn package_json() -> String {
    template(include_str!("render/package.json.txt"))
}

pub(super) fn package_lock_json() -> String {
    template(include_str!("render/package-lock.json.txt"))
}

pub(super) fn tsconfig_json() -> String {
    template(include_str!("render/tsconfig.json.txt"))
}

pub(super) fn errors_ts() -> String {
    template(include_str!("render/errors.ts.txt"))
}

pub(super) fn index_ts() -> String {
    template(include_str!("render/index.ts.txt"))
}

pub(super) fn wasm_provider_ts() -> String {
    template(include_str!("render/wasm-provider.ts.txt"))
}

/// One numeric byte literal per generated file: twelve bytes a line, so a
/// diff of two generated consumers stays readable. Matches
/// `public_generic_consumer::byte_literal`'s and
/// `rust_calling::render::byte_array_literal`'s own convention, rendered as
/// a TypeScript `Uint8Array.from([...])` initializer.
fn uint8_array_literal(bytes: &[u8]) -> String {
    let mut out = String::from("Uint8Array.from([\n");
    for chunk in bytes.chunks(12) {
        out.push_str("  ");
        for byte in chunk {
            let _ = write!(out, "0x{byte:02x}, ");
        }
        out.push('\n');
    }
    out.push_str("])");
    out
}

/// A canonical, escaped TypeScript double-quoted string literal. Every
/// embedded string this generator emits (an export name, a digest) is
/// already-trusted, already-validated UTF-8 from
/// [`WasmProviderBindingV1`]'s own accessors, but this still escapes `\`,
/// `"`, and control characters rather than assuming they cannot occur --
/// the generator's own contract, not a fact about today's fixture values.
fn ts_string_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other if (other as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", other as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

const DESCRIPTOR_HEADER: &str = r#"/**
 * Generated by `semaprax::public_generic_consumer::typescript_calling`.
 * Embeds the exact trusted descriptor and Wasm-provider-binding bytes this
 * consumer was generated from, this consumer's OWN independent replay check
 * (byte-exact equality against these embedded constants, run BEFORE any
 * Wasm allocation), and this generator's own module-artifact-identity
 * convention for verifying that a supplied `.wasm` module's bytes are the
 * exact trusted provider artifact -- independent of, and never sharing code
 * with, `public_generic_abi::digest`'s private, crate-internal convention
 * (see `typescript_calling.rs`'s own module documentation for why a
 * separate convention is necessary here).
 *
 * Uses only the platform Web Crypto API (`globalThis.crypto.subtle`,
 * ambient from the "DOM" lib and available as a real global in current
 * Node without any import) rather than `node:crypto` -- this keeps the
 * generated package free of any Node-only ambient type dependency
 * (`@types/node`), matching "no runtime dependency beyond the platform
 * WebAssembly API and generated code" and this generator's own
 * browser/Node dual-host aspiration.
 */

import { SemapraxPublicGenericException } from "./errors.js";

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) {
    return false;
  }
  let differs = 0;
  for (let index = 0; index < a.length; index += 1) {
    differs |= (a[index] as number) ^ (b[index] as number);
  }
  return differs === 0;
}

"#;

const DESCRIPTOR_VERIFY: &str = r#"
export function verifyDescriptorAndBinding(
  descriptorBytes: Uint8Array,
  bindingBytes: Uint8Array,
): void {
  if (!bytesEqual(descriptorBytes, TRUSTED_DESCRIPTOR_BYTES)) {
    throw new SemapraxPublicGenericException({
      kind: "descriptor-rejected",
      reason:
        "submitted descriptor bytes do not replay the trusted value this consumer was generated from",
    });
  }
  if (!bytesEqual(bindingBytes, TRUSTED_BINDING_BYTES)) {
    throw new SemapraxPublicGenericException({
      kind: "provider-mismatch",
      reason:
        "submitted provider-binding bytes do not replay the trusted value this consumer was generated from",
    });
  }
}

/**
 * This generator's OWN module-artifact-identity convention: domain-separated
 * SHA-256 over `len(bytes) as u64 little-endian || bytes`, rendered as
 * `sha256:<hex>`. Async: the platform Web Crypto API's `digest` is
 * Promise-based.
 */
export async function computeModuleArtifactDigest(
  wasmBytes: Uint8Array,
): Promise<string> {
  const preimage = new Uint8Array(
    MODULE_ARTIFACT_DIGEST_DOMAIN.length + 8 + wasmBytes.length,
  );
  preimage.set(MODULE_ARTIFACT_DIGEST_DOMAIN, 0);
  new DataView(preimage.buffer).setBigUint64(
    MODULE_ARTIFACT_DIGEST_DOMAIN.length,
    BigInt(wasmBytes.length),
    true,
  );
  preimage.set(wasmBytes, MODULE_ARTIFACT_DIGEST_DOMAIN.length + 8);
  const digestBytes = new Uint8Array(
    await crypto.subtle.digest("SHA-256", preimage),
  );
  let hex = "";
  for (const byte of digestBytes) {
    hex += byte.toString(16).padStart(2, "0");
  }
  return `sha256:${hex}`;
}

export async function verifyModuleArtifactDigest(
  wasmBytes: Uint8Array,
): Promise<void> {
  const computed = await computeModuleArtifactDigest(wasmBytes);
  if (computed !== TRUSTED_PROVIDER_ARTIFACT_DIGEST) {
    throw new SemapraxPublicGenericException({
      kind: "provider-mismatch",
      reason:
        "the supplied Wasm module bytes do not replay this consumer's trusted provider-artifact digest",
    });
  }
}
"#;

pub(super) fn descriptor_ts(
    descriptor_bytes: &[u8],
    binding_bytes: &[u8],
    binding: &WasmProviderBindingV1,
) -> String {
    let mut out = String::new();
    out.push_str(DESCRIPTOR_HEADER);
    out.push_str(
        "const MODULE_ARTIFACT_DIGEST_DOMAIN = new TextEncoder().encode(\n  \"semaprax.public-generic-typescript-wasm-consumer.v1.module-artifact\\0\",\n);\n\n",
    );
    out.push_str("export const TRUSTED_DESCRIPTOR_BYTES: Uint8Array = ");
    out.push_str(&uint8_array_literal(descriptor_bytes));
    out.push_str(";\n\n");
    out.push_str("export const TRUSTED_BINDING_BYTES: Uint8Array = ");
    out.push_str(&uint8_array_literal(binding_bytes));
    out.push_str(";\n\n");
    out.push_str("export const TRUSTED_ENDPOINT_EXPORT_NAME: string = ");
    out.push_str(&ts_string_literal(binding.exported_endpoint_export_name()));
    out.push_str(";\n\n");
    out.push_str("export const TRUSTED_PROVIDER_ARTIFACT_DIGEST: string = ");
    out.push_str(&ts_string_literal(binding.provider_artifact_digest()));
    out.push_str(";\n");
    out.push_str(DESCRIPTOR_VERIFY);
    out
}

const TYPES_HEADER: &str = r#"/**
 * Generated by `semaprax::public_generic_consumer::typescript_calling`.
 * Concrete owned TypeScript types for this descriptor's one admitted input
 * parameter and one admitted result (see the module-level scope note in
 * `typescript_calling.rs`). Field order matches descriptor order; field
 * names are derived from canonical field-identity bytes via lowercase hex
 * (injective, stable under a display-name rename), never from display text.
 * Every field is `readonly`: a generated consumer never hands back a
 * mutable alias into anything it still owns.
 */

"#;

fn record_interface(name: &str, shape: &RecordShape) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "export interface {name} {{");
    for field in &shape.fields {
        let _ = writeln!(out, "  /** Field identity: {:?} */", field.identity);
        let _ = writeln!(out, "  readonly {}: Uint8Array;", field_name(field));
    }
    out.push_str("}\n");
    out
}

pub(super) fn types_ts(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(TYPES_HEADER);
    out.push_str(&record_interface("Input", input));
    out.push('\n');
    out.push_str(&record_interface("Output", output));
    out
}

const CARRIER_HEADER: &str = r#"/**
 * Generated by `semaprax::public_generic_consumer::typescript_calling`.
 * Codec for this descriptor's flat owned-`Uint8Array` leaf sequence:
 * [Logical Carrier v1](../../docs/PUBLIC-GENERIC-CARRIER-V1.md)'s wire
 * framing -- `[u64 leaf_count][per leaf: u64 len][bytes]`, little-endian --
 * restated independently here rather than trusted from any provider
 * response, matching `rust_calling::render`'s own `carrier.rs` codec
 * exactly, in TypeScript.
 *
 * EXACT INTEGERS: `leaf_count` and every per-leaf `len` are wire `u64`
 * fields. JavaScript `number` silently rounds anything past
 * `Number.MAX_SAFE_INTEGER` (2^53), so every wire integer is read and
 * compared as `bigint` BEFORE it is ever used for a length, an allocation,
 * or a bounds check -- a hostile carrier claiming a length near `u64::MAX`
 * is rejected by an exact `bigint` comparison against the per-leaf bound,
 * never by first narrowing to `Number` and hoping the result is still
 * meaningful.
 */

import { SemapraxPublicGenericException } from "./errors.js";
import type { Input, Output } from "./types.js";

/** Max bytes admitted in one owned leaf. Reused from
 * `boundary_profile.rs::MAX_BYTES_PER_LEAF`, restated here rather than
 * imported: this package depends on nothing but its own generated code and
 * the platform. */
const MAX_BYTES_PER_LEAF = 65536;

function capacityExceeded(reason: string): SemapraxPublicGenericException {
  return new SemapraxPublicGenericException({
    kind: "capacity-exceeded",
    reason,
  });
}

function resultRejected(reason: string): SemapraxPublicGenericException {
  return new SemapraxPublicGenericException({ kind: "result-rejected", reason });
}

export interface LeafSpan {
  readonly offset: number;
  readonly length: number;
}

/** Frame an already-bound-checked sequence of leaves into one canonical
 * Logical Carrier v1 byte blob, in the given order. Byte-identical for
 * equal semantic values, since it never consults object property
 * enumeration order -- the caller already supplied leaves in descriptor
 * order. */
export function encodeLeaves(leaves: readonly Uint8Array[]): Uint8Array {
  for (const leaf of leaves) {
    if (leaf.length > MAX_BYTES_PER_LEAF) {
      throw capacityExceeded("a leaf exceeds the per-leaf byte bound");
    }
  }
  let total = 8;
  for (const leaf of leaves) {
    total += 8 + leaf.length;
  }
  const out = new Uint8Array(total);
  const view = new DataView(out.buffer);
  view.setBigUint64(0, BigInt(leaves.length), true);
  let offset = 8;
  for (const leaf of leaves) {
    view.setBigUint64(offset, BigInt(leaf.length), true);
    offset += 8;
    out.set(leaf, offset);
    offset += leaf.length;
  }
  return out;
}

/** Strictly parse `bytes` as a Logical Carrier v1 blob and return each
 * leaf's exact span (offset and length within `bytes`), without copying
 * payload bytes. Rejects a leaf-count mismatch, truncation at any point,
 * an over-bound declared length, and trailing bytes -- every hostile shape
 * this format admits testing for. */
export function locateLeaves(
  bytes: Uint8Array,
  expectedCount: number,
): LeafSpan[] {
  if (bytes.length < 8) {
    throw resultRejected("truncated carrier: missing leaf count");
  }
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let offset = 0;
  const leafCount = view.getBigUint64(offset, true);
  offset += 8;
  if (leafCount !== BigInt(expectedCount)) {
    throw resultRejected(
      "carrier leaf count does not match the descriptor-declared field count",
    );
  }
  const spans: LeafSpan[] = [];
  for (let index = 0; index < expectedCount; index += 1) {
    if (bytes.length - offset < 8) {
      throw resultRejected("truncated carrier: missing leaf length");
    }
    const length = view.getBigUint64(offset, true);
    offset += 8;
    // Exact bigint comparison against the bound -- a hostile length near
    // `u64::MAX` never survives long enough to be narrowed to `Number`.
    if (length > BigInt(MAX_BYTES_PER_LEAF)) {
      throw capacityExceeded(
        "a leaf declares a length over the per-leaf byte bound",
      );
    }
    const exactLength = Number(length);
    if (bytes.length - offset < exactLength) {
      throw resultRejected("truncated carrier: missing leaf payload");
    }
    spans.push({ offset, length: exactLength });
    offset += exactLength;
  }
  if (offset !== bytes.length) {
    throw resultRejected("trailing bytes after the carrier");
  }
  return spans;
}

export function decodeLeaves(
  bytes: Uint8Array,
  expectedCount: number,
): Uint8Array[] {
  return locateLeaves(bytes, expectedCount).map((span) =>
    bytes.slice(span.offset, span.offset + span.length),
  );
}

"#;

fn input_leaves_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("function inputLeaves(value: Input): readonly Uint8Array[] {\n");
    out.push_str("  return [\n");
    for field in &input.fields {
        let _ = writeln!(out, "    value.{},", field_name(field));
    }
    out.push_str("  ];\n");
    out.push_str("}\n");
    out
}

fn output_from_leaves_fn(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("function outputFromLeaves(leaves: readonly Uint8Array[]): Output {\n");
    out.push_str("  return {\n");
    for (index, field) in output.fields.iter().enumerate() {
        let _ = writeln!(
            out,
            "    {}: leaves[{index}] as Uint8Array,",
            field_name(field)
        );
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

pub(super) fn carrier_ts(input: &RecordShape, output: &RecordShape) -> String {
    let count = input.fields.len();
    let mut out = String::new();
    out.push_str(CARRIER_HEADER);
    let _ = writeln!(out, "export const FIELD_COUNT = {count};");
    out.push('\n');
    out.push_str(&input_leaves_fn(input));
    out.push('\n');
    out.push_str(&output_from_leaves_fn(output));
    out.push('\n');
    out.push_str(
        "export function encodeInput(value: Input): Uint8Array {\n  return encodeLeaves(inputLeaves(value));\n}\n\n",
    );
    out.push_str(
        "export function decodeOutput(bytes: Uint8Array): Output {\n  return outputFromLeaves(decodeLeaves(bytes, FIELD_COUNT));\n}\n",
    );
    out
}

const ROUND_TRIP_HEADER: &str = r#"// Generated by `semaprax::public_generic_consumer::typescript_calling`.
// Real execution evidence for issue #157: instantiates a real Wasm module
// under Node, transfers one owned input record exactly once, calls the
// real endpoint export over real WebAssembly.Memory, decodes an
// independently validated result, and proves zero live allocations/handles
// after every terminal case -- success, hostile pairing, and every
// injected failure ordinal alike. Mirrors
// `rust_calling::render::round_trip_rs`'s own generated test structure.
//
// Run as: node test/round-trip.mjs <path-to-reference.wasm>

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  Provider,
  FAILURE_ORDINALS,
} from "../dist/wasm-provider.js";
import {
  TRUSTED_BINDING_BYTES,
  TRUSTED_DESCRIPTOR_BYTES,
} from "../dist/descriptor.js";
import { SemapraxPublicGenericException } from "../dist/errors.js";

const wasmPath = process.argv[2];
if (!wasmPath) {
  throw new Error("round-trip.mjs requires a path to the reference .wasm fixture");
}
const wasmBytes = readFileSync(wasmPath);

function reversed(bytes) {
  return Uint8Array.from(bytes).reverse();
}

let failed = 0;
let passed = 0;

async function test(name, fn) {
  try {
    await fn();
    passed += 1;
    console.log(`ok - ${name}`);
  } catch (error) {
    failed += 1;
    console.error(`FAIL - ${name}`);
    console.error(error);
  }
}

"#;

fn sample_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("function sampleInput() {\n");
    out.push_str("  return {\n");
    for (index, field) in input.fields.iter().enumerate() {
        let _ = writeln!(
            out,
            "    {}: new TextEncoder().encode(\"sample-{index}\"),",
            field_name(field)
        );
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

fn input_with_first_field_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("function inputWithFirstField(bytes) {\n");
    out.push_str("  return {\n");
    for (index, field) in input.fields.iter().enumerate() {
        if index == 0 {
            let _ = writeln!(out, "    {}: bytes,", field_name(field));
        } else {
            let _ = writeln!(out, "    {}: new Uint8Array(0),", field_name(field));
        }
    }
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

fn assert_reversed_fn(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("function assertReversed(output, original) {\n");
    for (in_field, out_field) in input.fields.iter().zip(output.fields.iter()) {
        let _ = writeln!(
            out,
            "  assert.deepEqual(output.{}, reversed(original.{}));",
            field_name(out_field),
            field_name(in_field)
        );
    }
    out.push_str("}\n");
    out
}

const ROUND_TRIP_BODY: &str = r#"
async function run() {
  await test("success round trip reverses every owned leaf and copies it out fresh", async () => {
    const provider = await Provider.open(wasmBytes);
    const input = sampleInput();
    const expected = sampleInput();
    const output = provider.transform(input);
    assertReversed(output, expected);
    // Mutating the original input's buffer after the call must never
    // mutate the already-returned, already-copied-out result -- proof the
    // result is a fresh JS-owned copy, not a live alias into anything.
    for (const key of Object.keys(input)) {
      input[key].fill(0xff);
    }
    assertReversed(output, expected);
    provider.close();
    assert.equal(Provider.diagnostics.liveAllocations(provider), 0);
    assert.equal(Provider.diagnostics.liveHandles(provider), 0);
  });

  await test("open rejects a mutated descriptor before any Wasm allocation", async () => {
    const mutated = Uint8Array.from(TRUSTED_DESCRIPTOR_BYTES);
    mutated[0] ^= 0xff;
    await assert.rejects(
      () => Provider.open(wasmBytes, { descriptorBytes: mutated }),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "descriptor-rejected");
        return true;
      },
    );
  });

  await test("open rejects a mutated provider binding before any Wasm allocation", async () => {
    const mutated = Uint8Array.from(TRUSTED_BINDING_BYTES);
    mutated[mutated.length - 1] ^= 0xff;
    await assert.rejects(
      () => Provider.open(wasmBytes, { bindingBytes: mutated }),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "provider-mismatch");
        return true;
      },
    );
  });

  await test("open rejects a well-formed descriptor naming a different document", async () => {
    const different = new Uint8Array(TRUSTED_DESCRIPTOR_BYTES.length + 8);
    different.set(TRUSTED_DESCRIPTOR_BYTES);
    different.set(new TextEncoder().encode("EXTENDED"), TRUSTED_DESCRIPTOR_BYTES.length);
    await assert.rejects(
      () => Provider.open(wasmBytes, { descriptorBytes: different }),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "descriptor-rejected");
        return true;
      },
    );
  });

  await test("open rejects a module whose bytes do not replay the trusted provider-artifact digest", async () => {
    const mutatedModule = Uint8Array.from(wasmBytes);
    // Flip a byte inside the code section (well past the fixed header),
    // producing a well-formed-looking but different module.
    mutatedModule[mutatedModule.length - 1] ^= 0xff;
    await assert.rejects(
      () => Provider.open(mutatedModule),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "provider-mismatch");
        return true;
      },
    );
  });

  await test("a stale/foreign handle is rejected rather than reused", async () => {
    const provider = await Provider.open(wasmBytes);
    const foreign = Provider.diagnostics.foreignHandle(0, 1);
    assert.throws(
      () => Provider.diagnostics.call(provider, foreign),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "carrier-rejected");
        return true;
      },
    );
    provider.close();
    assert.equal(Provider.diagnostics.liveAllocations(provider), 0);
  });

  await test("a released input handle cannot be reused (a cast through unknown does not help)", async () => {
    const provider = await Provider.open(wasmBytes);
    const handle = Provider.diagnostics.prepareInput(provider, sampleInput());
    Provider.diagnostics.releaseInput(provider, handle);
    const smuggled = /** @type {any} */ (handle);
    assert.throws(
      () => Provider.diagnostics.call(provider, smuggled),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "carrier-rejected");
        return true;
      },
    );
    provider.close();
    assert.equal(Provider.diagnostics.liveAllocations(provider), 0);
    assert.equal(Provider.diagnostics.liveHandles(provider), 0);
  });

  await test("call after close is rejected", async () => {
    const provider = await Provider.open(wasmBytes);
    provider.close();
    assert.throws(
      () => provider.transform(sampleInput()),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        return true;
      },
    );
  });

  await test("memory growth across a page boundary does not invalidate result decoding", async () => {
    // One page is 65536 bytes. A leaf at the exact per-leaf bound (also
    // 65536 bytes) plus this carrier's own framing overhead (leaf-count and
    // per-leaf length fields) exceeds one page, forcing a real
    // `memory.grow` during `#prepareInput`'s allocation -- the fresh view
    // this wrapper always reacquires after `alloc` must still see the
    // correct, freshly grown buffer, and the later `#call`/`#exportResult`
    // steps (each also reacquiring their own fresh view) must decode
    // correctly across that grow.
    const provider = await Provider.open(wasmBytes);
    const bigLeaf = new Uint8Array(65536).fill(0xcd);
    const output = provider.transform(inputWithFirstField(bigLeaf));
    assert.deepEqual(FIRST_OUTPUT_FIELD(output), reversed(bigLeaf));
    provider.close();
    assert.equal(Provider.diagnostics.liveAllocations(provider), 0);
  });

  await test("exact-integer carrier decoding rejects a hostile u64::MAX leaf length", async () => {
    // A hand-forged carrier: leaf_count = 1, then a leaf length field set
    // to u64::MAX. Must be rejected by an exact bigint comparison, never
    // by first narrowing the length to a JS `Number`.
    const forged = new Uint8Array(16);
    const view = new DataView(forged.buffer);
    view.setBigUint64(0, 1n, true);
    view.setBigUint64(8, 0xffffffffffffffffn, true);
    const { locateLeaves } = await import("../dist/carrier.js");
    assert.throws(
      () => locateLeaves(forged, 1),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "capacity-exceeded");
        return true;
      },
    );
  });

  await test("exact-integer carrier decoding rejects a leaf length exactly one over the per-leaf bound", async () => {
    const overBound = new Uint8Array(16 + 65537);
    const view = new DataView(overBound.buffer, 0, 16);
    view.setBigUint64(0, 1n, true);
    view.setBigUint64(8, 65537n, true);
    const { locateLeaves } = await import("../dist/carrier.js");
    assert.throws(
      () => locateLeaves(overBound, 1),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "capacity-exceeded");
        return true;
      },
    );
  });

  await test("exactly the per-leaf byte bound is accepted", async () => {
    const provider = await Provider.open(wasmBytes);
    const atBound = inputWithFirstField(new Uint8Array(65536).fill(0x5a));
    const output = provider.transform(atBound);
    assert.equal(FIRST_OUTPUT_FIELD(output).length, 65536);
    provider.close();
    assert.equal(Provider.diagnostics.liveAllocations(provider), 0);
  });

  await test("one byte over the per-leaf bound is rejected locally before any Wasm allocation", async () => {
    const provider = await Provider.open(wasmBytes);
    const overBound = inputWithFirstField(new Uint8Array(65537).fill(0x5a));
    const before = Provider.diagnostics.liveAllocations(provider);
    assert.throws(
      () => provider.transform(overBound),
      (error) => {
        assert.ok(error instanceof SemapraxPublicGenericException);
        assert.equal(error.detail.kind, "capacity-exceeded");
        return true;
      },
    );
    assert.equal(Provider.diagnostics.liveAllocations(provider), before);
    provider.close();
  });

  await test("the failure-injection matrix settles every ordinal with zero live resources", async () => {
    for (const ordinal of Object.values(FAILURE_ORDINALS)) {
      const provider = await Provider.open(wasmBytes);
      Provider.diagnostics.injectFailure(provider, ordinal);
      assert.throws(
        () => provider.transform(sampleInput()),
        `ordinal ${ordinal} must fail`,
      );
      Provider.diagnostics.clearFailureInjection(provider);
      assert.equal(
        Provider.diagnostics.liveHandles(provider),
        0,
        `ordinal ${ordinal} left a live handle`,
      );
      assert.equal(
        Provider.diagnostics.liveAllocations(provider),
        0,
        `ordinal ${ordinal} left a live allocation`,
      );
      provider.close();
    }
  });

  if (failed > 0) {
    console.error(`${failed} test(s) failed, ${passed} passed`);
    process.exitCode = 1;
  } else {
    console.log(`${passed} test(s) passed`);
  }
}

await run();
"#;

/// Generated (not part of the fixed [`ROUND_TRIP_BODY`] template) because
/// the memory-growth and per-leaf-bound assertions have to name that
/// record's actual first field.
fn first_output_field_fn(output: &RecordShape) -> String {
    format!(
        "function FIRST_OUTPUT_FIELD(output) {{\n  return output.{};\n}}\n",
        field_name(&output.fields[0])
    )
}

pub(super) fn round_trip_mjs(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(ROUND_TRIP_HEADER);
    out.push_str(&sample_input_fn(input));
    out.push('\n');
    out.push_str(&input_with_first_field_fn(input));
    out.push('\n');
    out.push_str(&assert_reversed_fn(input, output));
    out.push('\n');
    out.push_str(&first_output_field_fn(output));
    out.push_str(ROUND_TRIP_BODY);
    out
}
