#!/bin/sh
# Regenerate crates/semaprax-harness/src/assets_list.rs: the checked-in list of
# adapter files embedded in the harness binary (HN-07). Reads only repository
# files; run after changing a shipped adapter. A test fails on drift.
set -eu
cd "$(dirname "$0")/.."
base=packages/semaprax-harness-adapters
out=crates/semaprax-harness/src/assets_list.rs
{
  echo "// @generated by scripts/gen_harness_assets.sh; do not edit."
  echo "pub(super) const FILES: &[(&str, &[u8])] = &["
  (cd "$base" && LC_ALL=C find graft graphify rtk systemone examples/source-index-python sdk/python sdk/node -type f \
    -not -path '*/__pycache__/*' -not -path '*/node_modules/*' \
    -not -path '*/test/*' -not -path '*/tests/*' -not -path '*/tools/*' -not -path '*/fixtures/*' \
    -not -name 'EVIDENCE*' -not -name 'RESEARCH*' -not -name 'test_*' -not -name '*.pyc' -not -name '.DS_Store' | LC_ALL=C sort) |
  while read -r f; do
    echo "    (\"$f\", include_bytes!(\"../../../$base/$f\")),"
  done
  echo "];"
} > "$out"
echo "wrote $out"
