//! The deterministic string templates [`super::generate_c_calling_consumer`]
//! composes. Split from `c_calling.rs` itself only to keep that file's own
//! generator-contract logic short; every function here is a pure
//! byte-in/text-out renderer, exercised by [`super::tests`].
//!
//! Every function below states, in its own doc comment, which part of its
//! output is a **fixed template** restating `spx_pg_v1.h` (or this
//! generator's own closed status/API vocabulary) and which part is
//! **descriptor-derived** (scales with the shape's field count and field
//! identities).

use std::fmt::Write as _;

use super::{field_name, RecordShape};

/// Generate `spx_pg_calling_consumer.h`: the clean public surface.
///
/// **Fixed template:** the opaque handle, the closed
/// `spx_pg_consumer_status` vocabulary, `spx_pg_owned_bytes`, every function
/// declaration and its doc comment. **Descriptor-derived:** the
/// `spx_pg_input`/`spx_pg_output` struct field lists (one `spx_pg_owned_bytes`
/// member per leaf, in descriptor order, named from the leaf's identity
/// bytes).
pub(super) fn consumer_header(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(HEADER_PREAMBLE);
    out.push_str(&record_struct("spx_pg_input", input));
    out.push('\n');
    out.push_str(&record_struct("spx_pg_output", output));
    out.push('\n');
    out.push_str(HEADER_API);
    out
}

fn record_struct(name: &str, shape: &RecordShape) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "typedef struct {name} {{");
    for field in &shape.fields {
        let _ = writeln!(out, "    /* Field identity: {:?} */", field.identity);
        let _ = writeln!(out, "    spx_pg_owned_bytes {};", field_name(field));
    }
    let _ = writeln!(out, "}} {name};");
    out
}

const HEADER_PREAMBLE: &str = r#"/*
 * Generated by semaprax::public_generic_consumer::c_calling.
 * Compiler-generated deterministic output; do not edit.
 *
 * Descriptor-derived + fixed-template public API for one native
 * public-generic provider (issue #158), the C11 calling half of PG-5/PG-6.
 * Distinct from the metadata-only consumer generated by
 * semaprax::public_generic_consumer (never allocates, transfers, or calls
 * anything) and from this repository's Rust calling consumer (issue #156,
 * semaprax::public_generic_consumer::rust_calling): this is a standalone,
 * plain-C11 client of the SAME frozen native ABI header shipped alongside
 * this file byte-identical -- never a reimplementation of the native
 * provider.
 *
 * This header names no native ABI handle type: every such type stays
 * entirely inside spx_pg_calling_consumer.c, behind the opaque
 * spx_pg_calling_consumer handle below. Kept deliberately thin, and
 * dependent on nothing but <stddef.h>/<stdint.h>, so a later C++17 consumer
 * can `extern "C"`-include this exact header and link against the compiled
 * spx_pg_calling_consumer.c rather than inventing a second ABI.
 */
#ifndef SPX_PG_CALLING_CONSUMER_H
#define SPX_PG_CALLING_CONSUMER_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque, incomplete on purpose: no public field, no copy constructor. A
 * caller may only hold a pointer and pass it back to this API. */
typedef struct spx_pg_calling_consumer spx_pg_calling_consumer;

/* Closed calling-consumer status vocabulary. Every failure this API can
 * report maps to exactly one of these; a new reason requires a new constant
 * here, never an ad hoc negative number. */
typedef enum spx_pg_consumer_status {
    SPX_PG_CONSUMER_OK = 0,
    /* Submitted descriptor bytes did not replay this consumer's own
     * embedded trusted value, or the native provider's own independent
     * pairing check rejected them. */
    SPX_PG_CONSUMER_DESCRIPTOR_REJECTED = 1,
    /* Submitted provider-binding bytes did not replay this consumer's own
     * embedded trusted value, or the native provider's own independent
     * pairing check rejected them. */
    SPX_PG_CONSUMER_PROVIDER_MISMATCH = 2,
    /* The native provider reported a malformed carrier, an illegal
     * handle-lifecycle transition, or a foreign/stale/wrong-kind handle. */
    SPX_PG_CONSUMER_CARRIER_REJECTED = 3,
    /* A carrier bound (leaf count, or a per-leaf/total byte bound) was
     * reached. */
    SPX_PG_CONSUMER_CAPACITY_EXCEEDED = 4,
    /* The bound checked endpoint itself refused or failed, or a native
     * cleanup failure legally became the terminal status. See
     * `out_native_status` on spx_pg_consumer_transform for the raw native
     * status. */
    SPX_PG_CONSUMER_EXECUTION_FAILED = 5,
    /* The exported result carrier failed this consumer's OWN independent
     * validation (framing, leaf count, or trailing bytes) -- never trusted
     * merely because the native call itself reported success. */
    SPX_PG_CONSUMER_RESULT_REJECTED = 6,
    /* This consumer's OWN allocator (never the native provider's) could not
     * satisfy an allocation. */
    SPX_PG_CONSUMER_ALLOCATION_FAILURE = 7,
    /* A required pointer argument was null. */
    SPX_PG_CONSUMER_NULL_ARGUMENT = 8
} spx_pg_consumer_status;

/* One owned leaf: `data` is NULL if and only if `len == 0`. Otherwise a
 * malloc-family allocation the current owner must eventually release with
 * `spx_pg_owned_bytes_free` -- the caller for an input leaf before it is
 * transformed, this API for an output leaf after a successful transform. */
typedef struct spx_pg_owned_bytes {
    uint8_t *data;
    size_t len;
} spx_pg_owned_bytes;

/* This consumer's own embedded trusted descriptor/provider-binding bytes,
 * defined in spx_pg_calling_consumer.c. Exposed so an execution harness can
 * pass the exact trusted values (or a deliberately mutated copy) to
 * spx_pg_consumer_open without reaching into the implementation file. */
extern const uint8_t spx_pg_trusted_descriptor_bytes[];
extern const size_t spx_pg_trusted_descriptor_len;
extern const uint8_t spx_pg_trusted_binding_bytes[];
extern const size_t spx_pg_trusted_binding_len;

"#;

const HEADER_API: &str = r#"/* Verify the exact descriptor/provider pairing against this consumer's own
 * embedded trusted bytes BEFORE any native allocation, then open the native
 * provider. `*out_consumer` is non-null if and only if this returns
 * SPX_PG_CONSUMER_OK. */
spx_pg_consumer_status spx_pg_consumer_open(const uint8_t *descriptor_bytes,
                                             size_t descriptor_len,
                                             const uint8_t *provider_binding_bytes,
                                             size_t provider_binding_len,
                                             spx_pg_calling_consumer **out_consumer);

/* Consumes `*input` by value: every leaf's `data` in `*input` is freed and
 * the leaf zeroed before this call returns, success or failure alike -- the
 * caller must not read or free `*input` again afterward. Every leaf byte is
 * copied into an independent carrier buffer before any native transfer, so
 * the native adapter never sees the caller's own buffer. `*out_output` is
 * zeroed before this call does anything else and is populated only on
 * SPX_PG_CONSUMER_OK; on any failure every field stays exactly {NULL,0} --
 * a deterministic failure value, never a partially populated result. The
 * native result handle this call opens internally is always released, by
 * this call, before it returns, whichever way it returns -- the result this
 * API hands back is a plain value, never a handle the caller must release.
 * `out_native_status`, if non-null, receives the raw native
 * `spx_pg_status_v1` a SPX_PG_CONSUMER_EXECUTION_FAILED restates (0 on
 * success or on a failure this consumer's own checks caught locally). */
spx_pg_consumer_status spx_pg_consumer_transform(spx_pg_calling_consumer *consumer,
                                                  spx_pg_input *input,
                                                  spx_pg_output *out_output,
                                                  int *out_native_status);

/* Releases exactly one owned leaf and zeroes it. A null pointee (`data ==
 * NULL`) is a safe no-op, matching "release null" from the native ABI's own
 * lifecycle tests. Safe to call on `bytes == NULL`. */
void spx_pg_owned_bytes_free(spx_pg_owned_bytes *bytes);

/* Frees every leaf of `*output` and zeroes it. Safe to call on an
 * already-zeroed output, or on `output == NULL`. */
void spx_pg_output_free(spx_pg_output *output);

/* Closes the native provider exactly once. `*consumer` is NULL after this
 * returns; a null pointee is a safe no-op, matching the native ABI's own
 * "closing an already-null provider is a no-op success." */
void spx_pg_consumer_close(spx_pg_calling_consumer **consumer);

/* --- Test-only surface: restates the native provider's own test-only
 * diagnostics. Never part of any production or publication claim -- exists
 * so an execution harness can prove exact
 * settlement from the consumer side, using the native provider's OWN
 * counters. Single-threaded only, matching the native adapter itself. --- */

/* Arms deterministic failure injection at native trace ordinal `ordinal`
 * for the NEXT spx_pg_consumer_transform call only. */
void spx_pg_consumer_test_inject_failure(uint32_t ordinal);
void spx_pg_consumer_test_clear_failure_injection(void);
/* The native provider's own live-allocation counter -- zero after every
 * terminal case, success or failure, once every handle a caller minted has
 * been released. */
size_t spx_pg_consumer_test_live_allocations(void);
/* The native provider's own live-handle counter for `consumer`'s provider.
 * Returns 0 for a null `consumer`. */
size_t spx_pg_consumer_test_live_handles(spx_pg_calling_consumer *consumer);

#ifdef __cplusplus
}
#endif

#endif /* SPX_PG_CALLING_CONSUMER_H */
"#;

/// Generate `spx_pg_calling_consumer.c`.
///
/// **Fixed template:** the little-endian codec, `#include`s, the opaque
/// struct, `spx_pg_consumer_open`/`_transform`/`_close`, every status
/// mapping function, and the test-only diagnostics wrappers.
/// **Descriptor-derived:** the embedded trusted descriptor/binding byte
/// arrays, `FIELD_COUNT`, the per-field encode/free/assign statements (one
/// line per leaf, in descriptor order).
pub(super) fn consumer_source(
    descriptor_bytes: &[u8],
    binding_bytes: &[u8],
    input: &RecordShape,
    output: &RecordShape,
) -> String {
    let field_count = input.fields.len();
    let mut out = String::new();
    out.push_str(SOURCE_PREAMBLE);
    let _ = writeln!(out, "#define FIELD_COUNT {field_count}");
    out.push('\n');
    out.push_str(&c_byte_array(
        "spx_pg_trusted_descriptor_bytes",
        "spx_pg_trusted_descriptor_len",
        descriptor_bytes,
    ));
    out.push('\n');
    out.push_str(&c_byte_array(
        "spx_pg_trusted_binding_bytes",
        "spx_pg_trusted_binding_len",
        binding_bytes,
    ));
    out.push('\n');
    out.push_str(SOURCE_CODEC_AND_LIFECYCLE);
    out.push('\n');
    out.push_str(&encode_input_fn(input));
    out.push('\n');
    out.push_str(&free_input_leaves_fn(input));
    out.push('\n');
    out.push_str(&free_output_fn(output));
    out.push('\n');
    out.push_str(&decode_output_fn(output));
    out.push('\n');
    out.push_str(SOURCE_TRANSFORM_AND_DIAGNOSTICS);
    out
}

const SOURCE_PREAMBLE: &str = r#"/*
 * Generated by semaprax::public_generic_consumer::c_calling.
 * Compiler-generated deterministic output; do not edit.
 *
 * Implements spx_pg_calling_consumer.h against the real native provider
 * declared in spx_pg_v1.h (issue #154) -- never a reimplementation or
 * modification of it. `Provider::open`'s equivalent below independently
 * verifies the exact descriptor/provider pairing (byte-exact equality
 * against the embedded trusted values) BEFORE calling the native adapter at
 * all: a consumer that only trusted the native side's own answer would
 * defeat the point of an independently verified descriptor (issue #152).
 */
#include "spx_pg_calling_consumer.h"
#include "spx_pg_v1.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

"#;

/// One numeric byte literal per generated file, twelve bytes a line so a
/// diff of two generated consumers stays readable, matching
/// `public_generic_consumer::byte_literal`'s own convention. Mirrors
/// `native/template.rs::write_byte_array`'s `{0}`-for-empty convention so an
/// empty trusted value never renders `uint8_t name[] = {};`, which is not
/// valid C.
fn c_byte_array(bytes_name: &str, len_name: &str, bytes: &[u8]) -> String {
    let mut out = String::new();
    if bytes.is_empty() {
        let _ = writeln!(out, "const uint8_t {bytes_name}[] = {{0}};");
    } else {
        let _ = writeln!(out, "const uint8_t {bytes_name}[] = {{");
        for chunk in bytes.chunks(12) {
            out.push_str("    ");
            for byte in chunk {
                let _ = write!(out, "0x{byte:02x}, ");
            }
            out.push('\n');
        }
        out.push_str("};\n");
    }
    let _ = writeln!(out, "const size_t {len_name} = {};", bytes.len());
    out
}

const SOURCE_CODEC_AND_LIFECYCLE: &str = r#"/* Logical Carrier v1's wire framing, restated independently rather than
 * trusted from any other translation unit: `[u64 leaf_count][per leaf: u64
 * len][bytes]`, little-endian -- matching
 * src/public_generic_abi/native/provider_body.c's own codec and
 * semaprax::public_generic_consumer::rust_calling's carrier.rs. */
static uint64_t spx_pg_ccc_read_u64le(const uint8_t *bytes) {
    uint64_t value = 0;
    for (int index = 7; index >= 0; --index) {
        value = (value << 8) | (uint64_t)bytes[index];
    }
    return value;
}

static void spx_pg_ccc_write_u64le(uint8_t *out, uint64_t value) {
    for (int index = 0; index < 8; ++index) {
        out[index] = (uint8_t)(value & 0xffu);
        value >>= 8;
    }
}

static int spx_pg_ccc_bytes_equal(const uint8_t *a, size_t a_len, const uint8_t *b, size_t b_len) {
    if (a_len != b_len) {
        return 0;
    }
    return a_len == 0 || memcmp(a, b, a_len) == 0;
}

static const char SPX_PG_CCC_SECONDARY_RELEASE_NOTE[] =
    "spx-pg-c-calling-consumer: secondary release/close failure observed "
    "after the primary outcome was already settled; the primary outcome is "
    "unaffected\n";

/* The opaque handle: a native provider pointer, never exposed to a caller
 * of spx_pg_calling_consumer.h. */
struct spx_pg_calling_consumer {
    spx_pg_provider_v1 *provider;
};

static spx_pg_consumer_status spx_pg_ccc_verify_pairing(const uint8_t *descriptor_bytes,
                                                         size_t descriptor_len,
                                                         const uint8_t *binding_bytes,
                                                         size_t binding_len) {
    if (!spx_pg_ccc_bytes_equal(descriptor_bytes, descriptor_len, spx_pg_trusted_descriptor_bytes,
                                 spx_pg_trusted_descriptor_len)) {
        return SPX_PG_CONSUMER_DESCRIPTOR_REJECTED;
    }
    if (!spx_pg_ccc_bytes_equal(binding_bytes, binding_len, spx_pg_trusted_binding_bytes,
                                 spx_pg_trusted_binding_len)) {
        return SPX_PG_CONSUMER_PROVIDER_MISMATCH;
    }
    return SPX_PG_CONSUMER_OK;
}

static spx_pg_consumer_status spx_pg_ccc_map_open_failure(spx_pg_status_v1 status) {
    switch (status) {
    case SPX_PG_STATUS_MALFORMED_DESCRIPTOR:
    case SPX_PG_STATUS_DESCRIPTOR_REPLAY_MISMATCH:
        return SPX_PG_CONSUMER_DESCRIPTOR_REJECTED;
    case SPX_PG_STATUS_MALFORMED_BINDING:
    case SPX_PG_STATUS_BINDING_REPLAY_MISMATCH:
        return SPX_PG_CONSUMER_PROVIDER_MISMATCH;
    default:
        return SPX_PG_CONSUMER_EXECUTION_FAILED;
    }
}

static spx_pg_consumer_status spx_pg_ccc_map_prepare_failure(spx_pg_status_v1 status) {
    switch (status) {
    case SPX_PG_STATUS_MALFORMED_CARRIER:
        return SPX_PG_CONSUMER_CARRIER_REJECTED;
    case SPX_PG_STATUS_CARRIER_CAPACITY:
        return SPX_PG_CONSUMER_CAPACITY_EXCEEDED;
    default:
        return SPX_PG_CONSUMER_EXECUTION_FAILED;
    }
}

static spx_pg_consumer_status spx_pg_ccc_map_call_failure(spx_pg_status_v1 status) {
    switch (status) {
    case SPX_PG_STATUS_HANDLE_INVALID:
    case SPX_PG_STATUS_ILLEGAL_TRANSITION:
        return SPX_PG_CONSUMER_CARRIER_REJECTED;
    default:
        return SPX_PG_CONSUMER_EXECUTION_FAILED;
    }
}

static spx_pg_consumer_status spx_pg_ccc_map_export_failure(spx_pg_status_v1 status) {
    switch (status) {
    case SPX_PG_STATUS_HANDLE_INVALID:
        return SPX_PG_CONSUMER_CARRIER_REJECTED;
    default:
        return SPX_PG_CONSUMER_EXECUTION_FAILED;
    }
}
"#;

fn encode_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "/* Independently copies every leaf into one freshly allocated carrier\n\
         * buffer -- the native adapter never sees the caller's own buffer\n\
         * (\"input bytes are copied before native ownership transfer\"). Returns\n\
         * NULL on an arithmetic-bound or allocation failure; nothing is left\n\
         * allocated in that case. */\n",
    );
    out.push_str(
        "static uint8_t *spx_pg_ccc_encode_input(const spx_pg_input *input, size_t *out_len) {\n",
    );
    out.push_str("    const spx_pg_owned_bytes *leaves[FIELD_COUNT] = {\n");
    for field in &input.fields {
        let _ = writeln!(out, "        &input->{},", field_name(field));
    }
    out.push_str("    };\n");
    out.push_str(
        "    size_t total = 8;\n\
         \x20   for (size_t index = 0; index < FIELD_COUNT; ++index) {\n\
         \x20       if (leaves[index]->len > SIZE_MAX - 8u - total) {\n\
         \x20           return NULL;\n\
         \x20       }\n\
         \x20       total += 8 + leaves[index]->len;\n\
         \x20   }\n\
         \x20   uint8_t *buffer = (uint8_t *)malloc(total);\n\
         \x20   if (buffer == NULL) {\n\
         \x20       return NULL;\n\
         \x20   }\n\
         \x20   size_t offset = 0;\n\
         \x20   spx_pg_ccc_write_u64le(buffer + offset, (uint64_t)FIELD_COUNT);\n\
         \x20   offset += 8;\n\
         \x20   for (size_t index = 0; index < FIELD_COUNT; ++index) {\n\
         \x20       spx_pg_ccc_write_u64le(buffer + offset, (uint64_t)leaves[index]->len);\n\
         \x20       offset += 8;\n\
         \x20       if (leaves[index]->len != 0) {\n\
         \x20           memcpy(buffer + offset, leaves[index]->data, leaves[index]->len);\n\
         \x20       }\n\
         \x20       offset += leaves[index]->len;\n\
         \x20   }\n\
         \x20   *out_len = offset;\n\
         \x20   return buffer;\n\
         }\n",
    );
    out
}

fn free_input_leaves_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "/* Consumes `*input` by value: frees and zeroes every leaf, regardless of\n\
         * what happens next. */\n",
    );
    out.push_str("static void spx_pg_ccc_free_input_leaves(spx_pg_input *input) {\n");
    for field in &input.fields {
        let _ = writeln!(
            out,
            "    spx_pg_owned_bytes_free(&input->{});",
            field_name(field)
        );
    }
    out.push_str("}\n");
    out
}

fn free_output_fn(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("void spx_pg_owned_bytes_free(spx_pg_owned_bytes *bytes) {\n");
    out.push_str(
        "    if (bytes == NULL) {\n        return;\n    }\n    free(bytes->data);\n    bytes->data = NULL;\n    bytes->len = 0;\n}\n\n",
    );
    out.push_str("void spx_pg_output_free(spx_pg_output *output) {\n");
    out.push_str("    if (output == NULL) {\n        return;\n    }\n");
    for field in &output.fields {
        let _ = writeln!(
            out,
            "    spx_pg_owned_bytes_free(&output->{});",
            field_name(field)
        );
    }
    out.push_str("}\n");
    out
}

fn decode_output_fn(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "static void spx_pg_ccc_free_leaves(spx_pg_owned_bytes *leaves, size_t count) {\n\
         \x20   for (size_t index = 0; index < count; ++index) {\n\
         \x20       free(leaves[index].data);\n\
         \x20       leaves[index].data = NULL;\n\
         \x20       leaves[index].len = 0;\n\
         \x20   }\n\
         }\n\n",
    );
    out.push_str(
        "/* Independently validates framing, leaf count, and trailing bytes before\n\
         * ever trusting the exported carrier -- never trusted merely because the\n\
         * native call itself reported success. Frees every already-allocated\n\
         * leaf before returning a rejection, so a mid-decode failure leaks\n\
         * nothing. */\n",
    );
    out.push_str(
        "static spx_pg_consumer_status spx_pg_ccc_decode_output(const uint8_t *bytes, size_t len,\n\
         \x20                                                    spx_pg_output *out) {\n\
         \x20   if (len < 8) {\n\
         \x20       return SPX_PG_CONSUMER_RESULT_REJECTED;\n\
         \x20   }\n\
         \x20   size_t offset = 0;\n\
         \x20   uint64_t leaf_count = spx_pg_ccc_read_u64le(bytes + offset);\n\
         \x20   offset += 8;\n\
         \x20   if (leaf_count != (uint64_t)FIELD_COUNT) {\n\
         \x20       return SPX_PG_CONSUMER_RESULT_REJECTED;\n\
         \x20   }\n\
         \x20   spx_pg_owned_bytes leaves[FIELD_COUNT];\n\
         \x20   memset(leaves, 0, sizeof(leaves));\n\
         \x20   for (size_t index = 0; index < FIELD_COUNT; ++index) {\n\
         \x20       if (len < offset + 8) {\n\
         \x20           spx_pg_ccc_free_leaves(leaves, index);\n\
         \x20           return SPX_PG_CONSUMER_RESULT_REJECTED;\n\
         \x20       }\n\
         \x20       uint64_t leaf_len = spx_pg_ccc_read_u64le(bytes + offset);\n\
         \x20       offset += 8;\n\
         \x20       if (leaf_len > len - offset) {\n\
         \x20           spx_pg_ccc_free_leaves(leaves, index);\n\
         \x20           return SPX_PG_CONSUMER_RESULT_REJECTED;\n\
         \x20       }\n\
         \x20       uint8_t *data = NULL;\n\
         \x20       if (leaf_len != 0) {\n\
         \x20           data = (uint8_t *)malloc((size_t)leaf_len);\n\
         \x20           if (data == NULL) {\n\
         \x20               spx_pg_ccc_free_leaves(leaves, index);\n\
         \x20               return SPX_PG_CONSUMER_ALLOCATION_FAILURE;\n\
         \x20           }\n\
         \x20           memcpy(data, bytes + offset, (size_t)leaf_len);\n\
         \x20       }\n\
         \x20       leaves[index].data = data;\n\
         \x20       leaves[index].len = (size_t)leaf_len;\n\
         \x20       offset += (size_t)leaf_len;\n\
         \x20   }\n\
         \x20   if (offset != len) {\n\
         \x20       spx_pg_ccc_free_leaves(leaves, FIELD_COUNT);\n\
         \x20       return SPX_PG_CONSUMER_RESULT_REJECTED;\n\
         \x20   }\n",
    );
    for (index, field) in output.fields.iter().enumerate() {
        let _ = writeln!(out, "    out->{} = leaves[{index}];", field_name(field));
    }
    out.push_str("    return SPX_PG_CONSUMER_OK;\n}\n");
    out
}

const SOURCE_TRANSFORM_AND_DIAGNOSTICS: &str = r#"/* Process-global test-only injection state: the ordinal
 * spx_pg_consumer_test_inject_failure last armed, or SPX_PG_TEST_NO_INJECTION
 * once consumed or cleared. Native trace ordinals 0..=4 fire inside
 * spx_pg_input_prepare_v1; ordinals 5..=13 fire inside spx_pg_call_v1, so
 * this restates the same "inject again before the next native call if the
 * first one did not consume it" pattern
 * tests/public_generic_native_adapter_v1/probe.c's own C-hosted matrix uses,
 * hidden behind the single spx_pg_consumer_transform call below. */
static uint32_t spx_pg_ccc_pending_injection = SPX_PG_TEST_NO_INJECTION;

void spx_pg_consumer_test_inject_failure(uint32_t ordinal) {
    spx_pg_ccc_pending_injection = ordinal;
    spx_pg_test_inject_failure_v1(ordinal);
}

void spx_pg_consumer_test_clear_failure_injection(void) {
    spx_pg_ccc_pending_injection = SPX_PG_TEST_NO_INJECTION;
    spx_pg_test_clear_failure_injection_v1();
}

size_t spx_pg_consumer_test_live_allocations(void) {
    return spx_pg_test_live_allocations_v1();
}

size_t spx_pg_consumer_test_live_handles(spx_pg_calling_consumer *consumer) {
    if (consumer == NULL) {
        return 0;
    }
    return spx_pg_test_live_handles_v1(consumer->provider);
}

spx_pg_consumer_status spx_pg_consumer_open(const uint8_t *descriptor_bytes, size_t descriptor_len,
                                             const uint8_t *provider_binding_bytes,
                                             size_t provider_binding_len,
                                             spx_pg_calling_consumer **out_consumer) {
    if (out_consumer == NULL) {
        return SPX_PG_CONSUMER_NULL_ARGUMENT;
    }
    *out_consumer = NULL;
    if (descriptor_bytes == NULL || provider_binding_bytes == NULL) {
        return SPX_PG_CONSUMER_NULL_ARGUMENT;
    }

    /* This consumer's OWN independent replay, before any FFI call at all. */
    spx_pg_consumer_status verified = spx_pg_ccc_verify_pairing(
        descriptor_bytes, descriptor_len, provider_binding_bytes, provider_binding_len);
    if (verified != SPX_PG_CONSUMER_OK) {
        return verified;
    }

    spx_pg_provider_v1 *provider = NULL;
    spx_pg_status_v1 status = spx_pg_provider_open_v1(descriptor_bytes, descriptor_len,
                                                       provider_binding_bytes, provider_binding_len,
                                                       &provider);
    if (status != SPX_PG_STATUS_OK) {
        return spx_pg_ccc_map_open_failure(status);
    }

    spx_pg_calling_consumer *consumer =
        (spx_pg_calling_consumer *)malloc(sizeof(spx_pg_calling_consumer));
    if (consumer == NULL) {
        spx_pg_status_v1 close_status = spx_pg_provider_close_v1(&provider);
        if (close_status != SPX_PG_STATUS_OK) {
            fprintf(stderr, "%s", SPX_PG_CCC_SECONDARY_RELEASE_NOTE);
        }
        return SPX_PG_CONSUMER_ALLOCATION_FAILURE;
    }
    consumer->provider = provider;
    *out_consumer = consumer;
    return SPX_PG_CONSUMER_OK;
}

spx_pg_consumer_status spx_pg_consumer_transform(spx_pg_calling_consumer *consumer,
                                                  spx_pg_input *input,
                                                  spx_pg_output *out_output,
                                                  int *out_native_status) {
    if (out_native_status != NULL) {
        *out_native_status = 0;
    }
    if (out_output != NULL) {
        memset(out_output, 0, sizeof(*out_output));
    }
    if (consumer == NULL || input == NULL || out_output == NULL) {
        return SPX_PG_CONSUMER_NULL_ARGUMENT;
    }

    size_t carrier_len = 0;
    uint8_t *carrier = spx_pg_ccc_encode_input(input, &carrier_len);
    /* Input is consumed by value from here on, success or failure alike. */
    spx_pg_ccc_free_input_leaves(input);
    if (carrier == NULL) {
        return SPX_PG_CONSUMER_ALLOCATION_FAILURE;
    }

    if (spx_pg_ccc_pending_injection != SPX_PG_TEST_NO_INJECTION) {
        spx_pg_test_inject_failure_v1(spx_pg_ccc_pending_injection);
    }
    spx_pg_value_v1 *input_handle = NULL;
    spx_pg_status_v1 status =
        spx_pg_input_prepare_v1(consumer->provider, carrier, carrier_len, &input_handle);
    free(carrier);
    if (status != SPX_PG_STATUS_OK) {
        spx_pg_ccc_pending_injection = SPX_PG_TEST_NO_INJECTION;
        if (out_native_status != NULL) {
            *out_native_status = (int)status;
        }
        return spx_pg_ccc_map_prepare_failure(status);
    }

    /* Injection ordinals 5..=13 fire inside spx_pg_call_v1, not
     * spx_pg_input_prepare_v1; re-arm here exactly once, only when the first
     * arming did not already fire (status == SPX_PG_STATUS_OK), restating
     * probe.c's own pattern. */
    if (spx_pg_ccc_pending_injection != SPX_PG_TEST_NO_INJECTION) {
        spx_pg_test_inject_failure_v1(spx_pg_ccc_pending_injection);
    }
    spx_pg_ccc_pending_injection = SPX_PG_TEST_NO_INJECTION;

    /* `input_handle` must never be released by this consumer after this
     * call, succeeding or not: the native ABI documents ownership as already
     * transferred either way. */
    spx_pg_result_v1 *result_handle = NULL;
    status = spx_pg_call_v1(consumer->provider, input_handle, &result_handle);
    if (status != SPX_PG_STATUS_OK) {
        if (out_native_status != NULL) {
            *out_native_status = (int)status;
        }
        return spx_pg_ccc_map_call_failure(status);
    }

    size_t required = 0;
    status = spx_pg_result_export_v1(result_handle, NULL, 0, &required);
    if (status != SPX_PG_STATUS_OK && status != SPX_PG_STATUS_BUFFER_TOO_SMALL) {
        spx_pg_status_v1 release_status = spx_pg_result_release_v1(&result_handle);
        if (release_status != SPX_PG_STATUS_OK) {
            fprintf(stderr, "%s", SPX_PG_CCC_SECONDARY_RELEASE_NOTE);
        }
        if (out_native_status != NULL) {
            *out_native_status = (int)status;
        }
        return spx_pg_ccc_map_export_failure(status);
    }

    uint8_t *buffer = (uint8_t *)malloc(required != 0 ? required : 1);
    if (buffer == NULL) {
        spx_pg_status_v1 release_status = spx_pg_result_release_v1(&result_handle);
        if (release_status != SPX_PG_STATUS_OK) {
            fprintf(stderr, "%s", SPX_PG_CCC_SECONDARY_RELEASE_NOTE);
        }
        return SPX_PG_CONSUMER_ALLOCATION_FAILURE;
    }
    size_t reported = 0;
    status = spx_pg_result_export_v1(result_handle, buffer, required, &reported);
    /* The native result handle is released here, unconditionally, before
     * this function returns any way at all: "result remains opaque/owning
     * and is released explicitly," by this consumer, never by its caller. */
    spx_pg_status_v1 release_status = spx_pg_result_release_v1(&result_handle);
    if (release_status != SPX_PG_STATUS_OK) {
        fprintf(stderr, "%s", SPX_PG_CCC_SECONDARY_RELEASE_NOTE);
    }
    if (status != SPX_PG_STATUS_OK) {
        free(buffer);
        if (out_native_status != NULL) {
            *out_native_status = (int)status;
        }
        return spx_pg_ccc_map_export_failure(status);
    }
    if (reported != required) {
        free(buffer);
        return SPX_PG_CONSUMER_RESULT_REJECTED;
    }

    spx_pg_consumer_status decoded = spx_pg_ccc_decode_output(buffer, reported, out_output);
    free(buffer);
    return decoded;
}

void spx_pg_consumer_close(spx_pg_calling_consumer **consumer) {
    if (consumer == NULL || *consumer == NULL) {
        return;
    }
    spx_pg_calling_consumer *owned = *consumer;
    *consumer = NULL;
    spx_pg_provider_v1 *provider = owned->provider;
    spx_pg_status_v1 status = spx_pg_provider_close_v1(&provider);
    if (status != SPX_PG_STATUS_OK) {
        fprintf(stderr, "%s", SPX_PG_CCC_SECONDARY_RELEASE_NOTE);
    }
    free(owned);
}
"#;

/// Generate `round_trip.c`: a real, executable test driver -- not a mere
/// compile check.
///
/// **Fixed template:** the `REQUIRE` macro, byte-reversal and owned-bytes
/// helpers, the mutated-descriptor/binding/different-descriptor tests, the
/// per-leaf-bound tests' scaffolding, the full ordinal `0..=13`
/// failure-injection matrix, and `main`. **Descriptor-derived:** the sample
/// input/expected builders, the per-field `assert_reversed` comparisons, the
/// per-field zero-on-failure assertions, and which field the per-leaf-bound
/// tests target (the first one, matching
/// `rust_calling::render::round_trip_rs`'s own convention).
pub(super) fn round_trip_c(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(ROUND_TRIP_PREAMBLE);
    out.push_str(&sample_input_fn(input));
    out.push('\n');
    out.push_str(&free_input_fn(input));
    out.push('\n');
    out.push_str(&input_with_first_field_fn(input));
    out.push('\n');
    out.push_str(&assert_reversed_fn(input, output));
    out.push('\n');
    out.push_str(&assert_output_is_zeroed_fn(output));
    out.push('\n');
    out.push_str(ROUND_TRIP_BODY);
    out.push('\n');
    out.push_str(&per_leaf_bound_tests_fn(output));
    out.push('\n');
    out.push_str(&main_fn());
    out
}

const ROUND_TRIP_PREAMBLE: &str = r#"/*
 * Generated by semaprax::public_generic_consumer::c_calling.
 * Compiler-generated deterministic output; do not edit.
 *
 * Real, executed evidence for issue #158: opens the real native provider
 * through the generated C11 calling consumer, transfers one owned input
 * record exactly once, calls, decodes an independently validated result,
 * and proves zero live native allocations/handles after every terminal case
 * -- success, hostile pairing, the per-leaf byte bound, and the full
 * ordinal 0..=13 failure-injection matrix -- using the native provider's
 * OWN test-only counters (spx_pg_consumer_test_live_allocations/_handles),
 * exactly like tests/public_generic_native_adapter_v1/probe.c's own
 * C-hosted matrix for the same provider.
 */
#include "spx_pg_calling_consumer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_BYTES_PER_LEAF (64u * 1024u)

static void spx_pg_ccc_require(int condition, const char *message, unsigned line) {
    if (!condition) {
        fprintf(stderr, "round_trip.c line %u: %s\n", line, message);
        exit(1);
    }
}
#define REQUIRE(condition) spx_pg_ccc_require((condition), #condition, __LINE__)

static spx_pg_owned_bytes owned_from(const char *text) {
    size_t len = strlen(text);
    spx_pg_owned_bytes bytes;
    bytes.len = len;
    bytes.data = len == 0 ? NULL : (uint8_t *)malloc(len);
    REQUIRE(len == 0 || bytes.data != NULL);
    if (len != 0) {
        memcpy(bytes.data, text, len);
    }
    return bytes;
}

static void assert_reversed_field(const spx_pg_owned_bytes *actual, const spx_pg_owned_bytes *original) {
    REQUIRE(actual->len == original->len);
    if (actual->len == 0) {
        REQUIRE(actual->data == NULL);
        return;
    }
    uint8_t *expected = (uint8_t *)malloc(actual->len);
    REQUIRE(expected != NULL);
    for (size_t index = 0; index < actual->len; ++index) {
        expected[index] = original->data[original->len - 1 - index];
    }
    REQUIRE(memcmp(actual->data, expected, actual->len) == 0);
    free(expected);
}
"#;

fn sample_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("\nstatic spx_pg_input sample_input(void) {\n");
    out.push_str("    spx_pg_input input;\n");
    for (index, field) in input.fields.iter().enumerate() {
        let _ = writeln!(
            out,
            "    input.{} = owned_from(\"sample-{index}\");",
            field_name(field)
        );
    }
    out.push_str("    return input;\n");
    out.push_str("}\n");
    out
}

fn free_input_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("static void free_input(spx_pg_input *input) {\n");
    for field in &input.fields {
        let _ = writeln!(
            out,
            "    spx_pg_owned_bytes_free(&input->{});",
            field_name(field)
        );
    }
    out.push_str("}\n");
    out
}

fn input_with_first_field_fn(input: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("static spx_pg_input input_with_first_field(uint8_t *data, size_t len) {\n");
    out.push_str("    spx_pg_input input;\n");
    for (index, field) in input.fields.iter().enumerate() {
        if index == 0 {
            let _ = writeln!(out, "    input.{}.data = data;", field_name(field));
            let _ = writeln!(out, "    input.{}.len = len;", field_name(field));
        } else {
            let _ = writeln!(out, "    input.{}.data = NULL;", field_name(field));
            let _ = writeln!(out, "    input.{}.len = 0;", field_name(field));
        }
    }
    out.push_str("    return input;\n");
    out.push_str("}\n");
    out
}

fn assert_reversed_fn(input: &RecordShape, output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str("static void assert_reversed(const spx_pg_output *output, const spx_pg_input *original) {\n");
    for (in_field, out_field) in input.fields.iter().zip(output.fields.iter()) {
        let _ = writeln!(
            out,
            "    assert_reversed_field(&output->{}, &original->{});",
            field_name(out_field),
            field_name(in_field)
        );
    }
    out.push_str("}\n");
    out
}

fn assert_output_is_zeroed_fn(output: &RecordShape) -> String {
    let mut out = String::new();
    out.push_str(
        "/* \"Output parameters have deterministic failure values\": every leaf\n\
         * stays exactly {NULL,0} on any failure. */\n",
    );
    out.push_str("static void assert_output_is_zeroed(const spx_pg_output *output) {\n");
    for field in &output.fields {
        let name = field_name(field);
        let _ = writeln!(out, "    REQUIRE(output->{name}.data == NULL);");
        let _ = writeln!(out, "    REQUIRE(output->{name}.len == 0);");
    }
    out.push_str("}\n");
    out
}

const ROUND_TRIP_BODY: &str = r#"static void test_success_round_trip(void) {
    spx_pg_calling_consumer *consumer = NULL;
    REQUIRE(spx_pg_consumer_open(spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len,
                                  spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len,
                                  &consumer) == SPX_PG_CONSUMER_OK);
    REQUIRE(consumer != NULL);

    spx_pg_input input = sample_input();
    spx_pg_input expected = sample_input();
    spx_pg_output output;
    int native_status = -1;
    REQUIRE(spx_pg_consumer_transform(consumer, &input, &output, &native_status) == SPX_PG_CONSUMER_OK);
    REQUIRE(native_status == 0);
    assert_reversed(&output, &expected);

    spx_pg_output_free(&output);
    free_input(&expected);
    spx_pg_consumer_close(&consumer);
    REQUIRE(consumer == NULL);
    REQUIRE(spx_pg_consumer_test_live_allocations() == 0);
}

static void test_open_rejects_a_mutated_descriptor_before_any_native_allocation(void) {
    size_t len = spx_pg_trusted_descriptor_len;
    uint8_t *mutated = (uint8_t *)malloc(len == 0 ? 1 : len);
    REQUIRE(mutated != NULL);
    if (len != 0) {
        memcpy(mutated, spx_pg_trusted_descriptor_bytes, len);
        mutated[0] ^= 0xffu;
    }
    size_t allocations_before = spx_pg_consumer_test_live_allocations();
    spx_pg_calling_consumer *consumer = (spx_pg_calling_consumer *)(void *)0x1;
    spx_pg_consumer_status status =
        spx_pg_consumer_open(mutated, len, spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len,
                              &consumer);
    REQUIRE(status == SPX_PG_CONSUMER_DESCRIPTOR_REJECTED);
    REQUIRE(consumer == NULL);
    REQUIRE(spx_pg_consumer_test_live_allocations() == allocations_before);
    free(mutated);
}

static void test_open_rejects_a_mutated_binding_before_any_native_allocation(void) {
    size_t len = spx_pg_trusted_binding_len;
    REQUIRE(len > 0);
    uint8_t *mutated = (uint8_t *)malloc(len);
    REQUIRE(mutated != NULL);
    memcpy(mutated, spx_pg_trusted_binding_bytes, len);
    mutated[len - 1] ^= 0xffu;
    size_t allocations_before = spx_pg_consumer_test_live_allocations();
    spx_pg_calling_consumer *consumer = (spx_pg_calling_consumer *)(void *)0x1;
    spx_pg_consumer_status status =
        spx_pg_consumer_open(spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len, mutated,
                              len, &consumer);
    REQUIRE(status == SPX_PG_CONSUMER_PROVIDER_MISMATCH);
    REQUIRE(consumer == NULL);
    REQUIRE(spx_pg_consumer_test_live_allocations() == allocations_before);
    free(mutated);
}

static void test_open_rejects_a_valid_binding_that_names_a_different_descriptor(void) {
    /* The trusted binding is well-formed on its own, but paired against a
     * descriptor it was never generated for; this consumer's own replay (a
     * byte-exact pairing, not a semantic re-derivation) rejects it exactly
     * like a genuinely corrupted descriptor would. */
    static const char suffix[] = "-a-different-but-well-formed-descriptor";
    size_t len = spx_pg_trusted_descriptor_len + (sizeof(suffix) - 1);
    uint8_t *different = (uint8_t *)malloc(len);
    REQUIRE(different != NULL);
    if (spx_pg_trusted_descriptor_len != 0) {
        memcpy(different, spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len);
    }
    memcpy(different + spx_pg_trusted_descriptor_len, suffix, sizeof(suffix) - 1);
    spx_pg_calling_consumer *consumer = NULL;
    spx_pg_consumer_status status = spx_pg_consumer_open(
        different, len, spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len, &consumer);
    REQUIRE(status == SPX_PG_CONSUMER_DESCRIPTOR_REJECTED);
    REQUIRE(consumer == NULL);
    free(different);
}

/* Every logical trace ordinal 0..=13 (SPX_PG_TRACE_FRAME_VALIDATED through
 * SPX_PG_TRACE_CARRIER_RELEASE; ordinal 14, the settlement call itself, has
 * nothing left to abort -- see spx_pg_v1.h) settles as a failure with zero
 * live native allocations/handles afterward and a deterministic
 * all-zeroed output, exactly like probe.c's own C-hosted matrix for the
 * same provider. */
static void test_failure_injection_matrix_settles_every_ordinal_with_zero_live_resources(void) {
    for (uint32_t ordinal = 0; ordinal <= 13; ++ordinal) {
        spx_pg_calling_consumer *consumer = NULL;
        REQUIRE(spx_pg_consumer_open(spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len,
                                      spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len,
                                      &consumer) == SPX_PG_CONSUMER_OK);
        spx_pg_consumer_test_inject_failure(ordinal);
        spx_pg_input input = sample_input();
        spx_pg_output output;
        spx_pg_consumer_status status = spx_pg_consumer_transform(consumer, &input, &output, NULL);
        REQUIRE(status != SPX_PG_CONSUMER_OK);
        assert_output_is_zeroed(&output);
        spx_pg_consumer_test_clear_failure_injection();
        REQUIRE(spx_pg_consumer_test_live_handles(consumer) == 0);
        spx_pg_consumer_close(&consumer);
        REQUIRE(consumer == NULL);
        REQUIRE(spx_pg_consumer_test_live_allocations() == 0);
    }
}
"#;

fn per_leaf_bound_tests_fn(output: &RecordShape) -> String {
    let first_output_field = field_name(&output.fields[0]);
    let mut out = String::new();
    out.push_str("static void test_exactly_the_per_leaf_byte_bound_is_accepted(void) {\n");
    out.push_str(
        "    spx_pg_calling_consumer *consumer = NULL;\n\
         \x20   REQUIRE(spx_pg_consumer_open(spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len,\n\
         \x20                                 spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len,\n\
         \x20                                 &consumer) == SPX_PG_CONSUMER_OK);\n\
         \x20   uint8_t *data = (uint8_t *)malloc(MAX_BYTES_PER_LEAF);\n\
         \x20   REQUIRE(data != NULL);\n\
         \x20   memset(data, 0x5a, MAX_BYTES_PER_LEAF);\n\
         \x20   spx_pg_input input = input_with_first_field(data, MAX_BYTES_PER_LEAF);\n\
         \x20   spx_pg_output output;\n\
         \x20   REQUIRE(spx_pg_consumer_transform(consumer, &input, &output, NULL) == SPX_PG_CONSUMER_OK);\n",
    );
    let _ = writeln!(
        out,
        "    REQUIRE(output.{first_output_field}.len == MAX_BYTES_PER_LEAF);"
    );
    out.push_str(
        "    spx_pg_output_free(&output);\n\
         \x20   spx_pg_consumer_close(&consumer);\n\
         \x20   REQUIRE(spx_pg_consumer_test_live_allocations() == 0);\n\
         }\n\n",
    );

    out.push_str("static void test_one_byte_over_the_per_leaf_bound_is_rejected_locally(void) {\n");
    out.push_str(
        "    spx_pg_calling_consumer *consumer = NULL;\n\
         \x20   REQUIRE(spx_pg_consumer_open(spx_pg_trusted_descriptor_bytes, spx_pg_trusted_descriptor_len,\n\
         \x20                                 spx_pg_trusted_binding_bytes, spx_pg_trusted_binding_len,\n\
         \x20                                 &consumer) == SPX_PG_CONSUMER_OK);\n\
         \x20   uint8_t *data = (uint8_t *)malloc(MAX_BYTES_PER_LEAF + 1);\n\
         \x20   REQUIRE(data != NULL);\n\
         \x20   memset(data, 0x5a, MAX_BYTES_PER_LEAF + 1);\n\
         \x20   spx_pg_input input = input_with_first_field(data, MAX_BYTES_PER_LEAF + 1);\n\
         \x20   spx_pg_output output;\n\
         \x20   REQUIRE(spx_pg_consumer_transform(consumer, &input, &output, NULL) ==\n\
         \x20           SPX_PG_CONSUMER_CAPACITY_EXCEEDED);\n\
         \x20   assert_output_is_zeroed(&output);\n\
         \x20   spx_pg_consumer_close(&consumer);\n\
         \x20   REQUIRE(spx_pg_consumer_test_live_allocations() == 0);\n\
         }\n",
    );
    out
}

fn main_fn() -> String {
    r#"int main(void) {
    test_success_round_trip();
    test_open_rejects_a_mutated_descriptor_before_any_native_allocation();
    test_open_rejects_a_mutated_binding_before_any_native_allocation();
    test_open_rejects_a_valid_binding_that_names_a_different_descriptor();
    test_exactly_the_per_leaf_byte_bound_is_accepted();
    test_one_byte_over_the_per_leaf_bound_is_rejected_locally();
    test_failure_injection_matrix_settles_every_ordinal_with_zero_live_resources();
    (void)puts("c-calling-consumer-settled");
    return 0;
}
"#
    .to_owned()
}
