//! Web Application Projection v1: `semaprax webapp <file>`.
//!
//! Projects one verified module's records, payload-free variants, and pure
//! convention-named functions into a complete, dependency-free full-stack web
//! application: a JSON REST API with file persistence, client and server
//! validation, computed fields, and a browser UI. The compiler emits only
//! `schema.js`; the runtime files are fixed bytes embedded below.
//!
//! The projection executes nothing and grants nothing. The generated server
//! is an ordinary Node program whose authority is whatever its operator
//! gives it. Every admitted expression is translated with SEMAPRAX semantics
//! (checked `i64` arithmetic over BigInt, IEEE `f64`, UTF-8 byte lengths);
//! anything outside the admitted subset fails closed with `SPX-WA103`.
//! [docs/WEBAPP-PROJECTION-V1.md](../docs/WEBAPP-PROJECTION-V1.md) owns the
//! contract.

use std::path::{Path, PathBuf};

use sha2::{Digest as _, Sha256};

use crate::ast::Span;
use crate::diagnostic::Diagnostic;
use crate::{graph, parse, patch, verify};

mod emit;
mod model;
mod translate;

#[cfg(test)]
mod tests;

/// The runtime files every generated application carries verbatim.
pub const RUNTIME_FILES: [(&str, &str); 7] = [
    ("runtime.js", include_str!("webapp/runtime/runtime.js")),
    ("server.mjs", include_str!("webapp/runtime/server.mjs")),
    ("security.mjs", include_str!("webapp/runtime/security.mjs")),
    ("state.mjs", include_str!("webapp/runtime/state.mjs")),
    ("index.html", include_str!("webapp/runtime/index.html")),
    ("app.js", include_str!("webapp/runtime/app.js")),
    ("style.css", include_str!("webapp/runtime/style.css")),
];

/// The first line of every generated `schema.js`; an existing output
/// directory is replaced only when its `schema.js` starts with it.
pub const SCHEMA_HEADER: &str = "// Generated by `semaprax webapp`. Do not edit.\n";

/// Maximum UTF-8 size of explicit application-title metadata.
pub const MAX_APP_TITLE_BYTES: usize = 256;

/// Explicit metadata that affects a generated web application without
/// changing the verified SEMAPRAX module.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ProjectionOptions {
    title: Option<String>,
}

impl ProjectionOptions {
    /// Set the browser, sign-in, and server-log title. The exact text is
    /// emitted deterministically into `schema.js`.
    pub fn with_title(mut self, title: impl Into<String>) -> Result<Self, Diagnostic> {
        let title = title.into();
        if title.is_empty()
            || title.len() > MAX_APP_TITLE_BYTES
            || title.chars().any(char::is_control)
        {
            return Err(Diagnostic::error(
                "SPX-WA106",
                format!(
                    "webapp title must be nonempty, at most {MAX_APP_TITLE_BYTES} UTF-8 bytes, and contain no control characters"
                ),
                Span::default(),
            ));
        }
        self.title = Some(title);
        Ok(self)
    }

    fn title(&self, module: &str) -> String {
        self.title.clone().unwrap_or_else(|| default_title(module))
    }
}

/// A scalar type the projection admits for fields and expressions.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum Ty {
    Int,
    Float,
    Bool,
    Str,
    Char,
    Enum(String),
}

impl Ty {
    pub(crate) fn js_name(&self) -> &str {
        match self {
            Ty::Int => "int",
            Ty::Float => "float",
            Ty::Bool => "bool",
            Ty::Str => "string",
            Ty::Char => "char",
            Ty::Enum(_) => "enum",
        }
    }
}

/// How much of each feature one projection contains.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct Counts {
    pub entities: usize,
    pub enums: usize,
    pub rules: usize,
    pub computed: usize,
    pub keys: usize,
    pub workflows: usize,
    pub rollups: usize,
    pub permissions: usize,
    pub accounts: bool,
}

impl Counts {
    /// `10 entities, 7 enums, 25 rules, 10 computed`, plus every v2 feature
    /// present.
    pub fn summary(&self) -> String {
        let mut text = format!(
            "{} entities, {} enums, {} rules, {} computed",
            self.entities, self.enums, self.rules, self.computed
        );
        for (count, name) in [
            (self.keys, "keys"),
            (self.workflows, "workflows"),
            (self.rollups, "rollups"),
            (self.permissions, "permissions"),
        ] {
            if count > 0 {
                text.push_str(&format!(", {count} {name}"));
            }
        }
        if self.accounts {
            text.push_str(", accounts");
        }
        text
    }
}

/// What one successful projection produced.
#[derive(Debug)]
pub struct Projection {
    pub files: Vec<(String, String)>,
    pub counts: Counts,
    /// The plain-text API listing printed by `semaprax webapp --api`.
    pub api: String,
}

/// Snake-case a record name: `TimeEntry` becomes `time_entry`.
pub(crate) fn snake(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn shape_error(message: impl Into<String>, span: Span, help: &str) -> Diagnostic {
    Diagnostic::error("SPX-WA102", message, span).with_help(help)
}

const FIELD_TYPE_HELP: &str = "webapp fields are i64, f64, bool, char, string, a payload-free variant, or `<entity>_id: i64` referencing another record";

/// Project one source file into the generated application files.
pub fn generate(source_path: &Path) -> Result<Projection, Vec<Diagnostic>> {
    generate_with_options(source_path, &ProjectionOptions::default())
}

/// Project one source file with explicit presentation metadata.
pub fn generate_with_options(
    source_path: &Path,
    options: &ProjectionOptions,
) -> Result<Projection, Vec<Diagnostic>> {
    let canonical_source_path = patch::canonical_source_path(source_path)?;
    let snapshot = patch::read_source_snapshot(&canonical_source_path)?;
    let source = snapshot.source();
    let program = parse(source, source_path).map_err(|error| vec![error])?;
    // A web application has no `main`; every other verifier rule applies.
    let errors: Vec<Diagnostic> = verify::verify(&program)
        .into_iter()
        .filter(|item| item.severity.is_error() && item.code != "SPX-T105")
        .collect();
    if !errors.is_empty() {
        return Err(errors);
    }
    let model = model::build(&program, source)?;
    let title = options.title(&program.module);
    let (body, counts) = emit::schema(&model, &program.module, &title);
    let api = emit::api(&model);
    let digest = Sha256::digest(source.as_bytes());
    let file_name = source_path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut schema = String::from(SCHEMA_HEADER);
    schema.push_str("// Source: ");
    schema.push_str(&file_name);
    schema.push_str(" sha256:");
    for byte in digest.iter() {
        schema.push_str(&format!("{byte:02x}"));
    }
    schema.push('\n');
    schema.push_str(&body);
    let mut files = vec![("schema.js".to_owned(), schema)];
    files.extend(
        RUNTIME_FILES
            .iter()
            .map(|(name, text)| ((*name).to_owned(), (*text).to_owned())),
    );
    let revision = graph::revision(&program);
    patch::validate_source_unchanged(&canonical_source_path, source_path, &snapshot, &revision)?;
    Ok(Projection { files, counts, api })
}

/// Write a projection into `output`, which must be absent, empty, or a
/// directory this command generated before.
pub fn write(output: &Path, projection: &Projection) -> Result<(), Diagnostic> {
    let conflict = |detail: String| {
        Diagnostic::io("SPX-WA104", detail)
            .with_help("choose an empty or previously generated `-o` directory")
    };
    if output.exists() {
        let mut entries = std::fs::read_dir(output)
            .map_err(|error| conflict(format!("cannot read `{}`: {error}", output.display())))?;
        if entries.next().is_some() {
            let schema = std::fs::read_to_string(output.join("schema.js")).unwrap_or_default();
            if !schema.starts_with(SCHEMA_HEADER) {
                return Err(conflict(format!(
                    "refusing to overwrite `{}`: it is not a generated webapp directory",
                    output.display()
                )));
            }
        }
    }
    std::fs::create_dir_all(output)
        .map_err(|error| conflict(format!("cannot create `{}`: {error}", output.display())))?;
    for (name, text) in &projection.files {
        let path: PathBuf = output.join(name);
        std::fs::write(&path, text)
            .map_err(|error| conflict(format!("cannot write `{}`: {error}", path.display())))?;
    }
    Ok(())
}

/// `team.desk` becomes `Desk`: the last module segment, capitalised.
fn default_title(module: &str) -> String {
    let last = module.rsplit('.').next().unwrap_or(module);
    let mut chars = last.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}
