//! Web Application Projection v1: `semaprax webapp <file>`.
//!
//! Projects one verified module's records, payload-free variants, and pure
//! convention-named functions into a complete, dependency-free full-stack web
//! application: a JSON REST API with file persistence, client and server
//! validation, computed fields, and a browser UI. The compiler emits only
//! `schema.js`; the runtime files are fixed bytes embedded below.
//!
//! The projection executes nothing and grants nothing. The generated server
//! is an ordinary Node program whose authority is whatever its operator
//! gives it. Every admitted expression is translated with SEMAPRAX semantics
//! (checked `i64` arithmetic over BigInt, IEEE `f64`, UTF-8 byte lengths);
//! anything outside the admitted subset fails closed with `SPX-WA103`.
//! [docs/WEBAPP-PROJECTION-V1.md](../docs/WEBAPP-PROJECTION-V1.md) owns the
//! contract.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use sha2::{Digest as _, Sha256};

use crate::ast::{Function, ParamMode, Program, Span, Type, TypeDeclarationKind};
use crate::diagnostic::Diagnostic;
use crate::{graph, parse, patch, verify};

mod translate;

#[cfg(test)]
mod tests;

/// The runtime files every generated application carries verbatim.
pub const RUNTIME_FILES: [(&str, &str); 5] = [
    ("runtime.js", include_str!("webapp/runtime/runtime.js")),
    ("server.mjs", include_str!("webapp/runtime/server.mjs")),
    ("index.html", include_str!("webapp/runtime/index.html")),
    ("app.js", include_str!("webapp/runtime/app.js")),
    ("style.css", include_str!("webapp/runtime/style.css")),
];

/// The first line of every generated `schema.js`; an existing output
/// directory is replaced only when its `schema.js` starts with it.
pub const SCHEMA_HEADER: &str = "// Generated by `semaprax webapp`. Do not edit.\n";

/// A scalar type the projection admits for fields and expressions.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum Ty {
    Int,
    Float,
    Bool,
    Str,
    Char,
    Enum(String),
}

impl Ty {
    fn js_name(&self) -> &str {
        match self {
            Ty::Int => "int",
            Ty::Float => "float",
            Ty::Bool => "bool",
            Ty::Str => "string",
            Ty::Char => "char",
            Ty::Enum(_) => "enum",
        }
    }
}

#[derive(Debug)]
struct Field {
    name: String,
    ty: Ty,
    /// The referenced entity path for an `x_id: i64` reference field.
    reference: Option<String>,
}

#[derive(Debug)]
struct Entity {
    name: String,
    path: String,
    fields: Vec<Field>,
    rules: Vec<String>,
    computed: Vec<String>,
}

/// What one successful projection produced.
#[derive(Debug)]
pub struct Projection {
    pub files: Vec<(String, String)>,
    pub entities: usize,
    pub enums: usize,
    pub rules: usize,
    pub computed: usize,
}

/// Snake-case a record name: `TimeEntry` becomes `time_entry`.
pub(crate) fn snake(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn shape_error(message: impl Into<String>, span: Span, help: &str) -> Diagnostic {
    Diagnostic::error("SPX-WA102", message, span).with_help(help)
}

const FIELD_TYPE_HELP: &str = "webapp fields are i64, f64, bool, char, string, a payload-free variant, or `<entity>_id: i64` referencing another record";

/// Project one source file into the generated application files.
pub fn generate(source_path: &Path) -> Result<Projection, Vec<Diagnostic>> {
    let canonical_source_path = patch::canonical_source_path(source_path)?;
    let snapshot = patch::read_source_snapshot(&canonical_source_path)?;
    let source = snapshot.source();
    let program = parse(source, source_path).map_err(|error| vec![error])?;
    // A web application has no `main`; every other verifier rule applies.
    let errors: Vec<Diagnostic> = verify::verify(&program)
        .into_iter()
        .filter(|item| item.severity.is_error() && item.code != "SPX-T105")
        .collect();
    if !errors.is_empty() {
        return Err(errors);
    }
    let projection = project(&program, source)?;
    let digest = Sha256::digest(source.as_bytes());
    let file_name = source_path
        .file_name()
        .map(|name| name.to_string_lossy().into_owned())
        .unwrap_or_default();
    let mut schema = String::from(SCHEMA_HEADER);
    schema.push_str("// Source: ");
    schema.push_str(&file_name);
    schema.push_str(" sha256:");
    for byte in digest.iter() {
        schema.push_str(&format!("{byte:02x}"));
    }
    schema.push('\n');
    schema.push_str(&projection.0);
    let mut files = vec![("schema.js".to_owned(), schema)];
    files.extend(
        RUNTIME_FILES
            .iter()
            .map(|(name, text)| ((*name).to_owned(), (*text).to_owned())),
    );
    let revision = graph::revision(&program);
    patch::validate_source_unchanged(&canonical_source_path, source_path, &snapshot, &revision)?;
    let counts = projection.1;
    Ok(Projection {
        files,
        entities: counts[0],
        enums: counts[1],
        rules: counts[2],
        computed: counts[3],
    })
}

/// Write a projection into `output`, which must be absent, empty, or a
/// directory this command generated before.
pub fn write(output: &Path, projection: &Projection) -> Result<(), Diagnostic> {
    let conflict = |detail: String| {
        Diagnostic::io("SPX-WA104", detail)
            .with_help("choose an empty or previously generated `-o` directory")
    };
    if output.exists() {
        let mut entries = std::fs::read_dir(output)
            .map_err(|error| conflict(format!("cannot read `{}`: {error}", output.display())))?;
        if entries.next().is_some() {
            let schema = std::fs::read_to_string(output.join("schema.js")).unwrap_or_default();
            if !schema.starts_with(SCHEMA_HEADER) {
                return Err(conflict(format!(
                    "refusing to overwrite `{}`: it is not a generated webapp directory",
                    output.display()
                )));
            }
        }
    }
    std::fs::create_dir_all(output)
        .map_err(|error| conflict(format!("cannot create `{}`: {error}", output.display())))?;
    for (name, text) in &projection.files {
        let path: PathBuf = output.join(name);
        std::fs::write(&path, text)
            .map_err(|error| conflict(format!("cannot write `{}`: {error}", path.display())))?;
    }
    Ok(())
}

fn field_type(
    ty: &Type,
    name: &str,
    enums: &BTreeMap<String, Vec<String>>,
    paths: &BTreeMap<String, String>,
) -> Option<(Ty, Option<String>)> {
    Some(match ty {
        Type::I64 => {
            let reference = name
                .strip_suffix("_id")
                .filter(|prefix| paths.contains_key(*prefix))
                .map(str::to_owned);
            (Ty::Int, reference)
        }
        Type::F64 => (Ty::Float, None),
        Type::Bool => (Ty::Bool, None),
        Type::String => (Ty::Str, None),
        Type::Char => (Ty::Char, None),
        Type::Named { name, arguments } if arguments.is_empty() && enums.contains_key(name) => {
            (Ty::Enum(name.clone()), None)
        }
        _ => return None,
    })
}

/// Build the `schema.js` body and the entity/enum/rule/computed counts.
fn project(program: &Program, source: &str) -> Result<(String, [usize; 4]), Vec<Diagnostic>> {
    let mut errors = Vec::new();
    let mut enums: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for declaration in &program.types {
        if let TypeDeclarationKind::Variant { cases } = &declaration.kind {
            if declaration.type_parameters.is_empty() && cases.iter().all(|c| c.fields.is_empty()) {
                enums.insert(
                    declaration.name.clone(),
                    cases.iter().map(|case| case.name.clone()).collect(),
                );
            }
        }
    }
    let mut paths = BTreeMap::new();
    for declaration in &program.types {
        if let TypeDeclarationKind::Record { .. } = declaration.kind {
            paths.insert(snake(&declaration.name), declaration.name.clone());
        }
    }
    let mut entities = Vec::new();
    for declaration in &program.types {
        let TypeDeclarationKind::Record { fields } = &declaration.kind else {
            continue;
        };
        if !declaration.type_parameters.is_empty() {
            errors.push(shape_error(
                format!(
                    "generic record `{}` cannot be a webapp entity",
                    declaration.name
                ),
                declaration.name_span,
                "declare a concrete record",
            ));
            continue;
        }
        let mut projected = Vec::new();
        for field in fields {
            if field.name == "id" {
                errors.push(shape_error(
                    format!("field `{}.id` is reserved", declaration.name),
                    field.name_span,
                    "the webapp assigns every row an `id`; remove this field",
                ));
                continue;
            }
            match field_type(&field.ty, &field.name, &enums, &paths) {
                Some((ty, reference)) => projected.push(Field {
                    name: field.name.clone(),
                    ty,
                    reference,
                }),
                None => errors.push(shape_error(
                    format!(
                        "field `{}.{}` has a type the webapp projection does not admit",
                        declaration.name, field.name
                    ),
                    field.name_span,
                    FIELD_TYPE_HELP,
                )),
            }
        }
        entities.push(Entity {
            name: declaration.name.clone(),
            path: snake(&declaration.name),
            fields: projected,
            rules: Vec::new(),
            computed: Vec::new(),
        });
    }
    if entities.is_empty() {
        errors.push(shape_error(
            "the module declares no record to serve",
            Span::default(),
            "declare at least one `record`; each record becomes a webapp entity",
        ));
    }
    if !errors.is_empty() {
        return Err(errors);
    }

    let functions: BTreeMap<&str, &Function> = program
        .functions
        .iter()
        .map(|function| (function.name.as_str(), function))
        .collect();
    let mut translator = translate::Translator::new(source, &enums, &functions);
    for function in &program.functions {
        let Some((index, prefix)) = owning_entity(&entities, &function.name) else {
            continue;
        };
        let entity = &entities[index];
        let suffix = &function.name[prefix + 1..];
        let mut params = Vec::new();
        for param in &function.params {
            let field = entity.fields.iter().find(|field| field.name == param.name);
            let admitted = field.and_then(|field| {
                let (ty, _) = field_type(&param.ty, &param.name, &enums, &BTreeMap::new())?;
                (ty == field.ty && param.mode == ParamMode::Value).then_some(ty)
            });
            match admitted {
                Some(ty) => params.push((param.name.clone(), ty)),
                None => errors.push(shape_error(
                    format!(
                        "parameter `{}` of `{}` is not a field of `{}` with the same type",
                        param.name, function.name, entity.name
                    ),
                    param.span,
                    "an entity function takes some of its record's fields by name and type",
                )),
            }
        }
        if !function.effects.is_empty() || !function.type_parameters.is_empty() {
            errors.push(shape_error(
                format!(
                    "entity function `{}` must be pure and monomorphic",
                    function.name
                ),
                function.name_span,
                "remove `uses { … }` and type parameters",
            ));
        }
        if params.len() != function.params.len() || !errors.is_empty() {
            continue;
        }
        let result = if suffix == "valid" {
            translator.rules(function, &params).map(|rules| {
                entities[index].rules.extend(rules);
            })
        } else if entities[index]
            .fields
            .iter()
            .any(|field| field.name == suffix)
        {
            Err(vec![shape_error(
                format!(
                    "computed field `{suffix}` repeats a field of `{}`",
                    entities[index].name
                ),
                function.name_span,
                "rename the function",
            )])
        } else {
            translator
                .computed(function, suffix, &params)
                .map(|computed| {
                    entities[index].computed.push(computed);
                })
        };
        if let Err(mut more) = result {
            errors.append(&mut more);
        }
    }
    // A function that is neither an entity function nor reached from one
    // would be silently ignored, which usually means a misspelled prefix.
    for function in &program.functions {
        if function.name != "main"
            && owning_entity(&entities, &function.name).is_none()
            && !translator.reached(&function.name)
        {
            let prefixes: Vec<String> = entities
                .iter()
                .map(|entity| format!("{}_", entity.path))
                .collect();
            errors.push(
                Diagnostic::error(
                    "SPX-WA105",
                    format!(
                        "function `{}` is not an entity function and no entity function calls it",
                        function.name
                    ),
                    function.name_span,
                )
                .with_help(format!(
                    "start its name with an entity prefix ({}) or call it from one",
                    prefixes.join(", ")
                )),
            );
        }
    }
    if !errors.is_empty() {
        return Err(errors);
    }

    let mut out = String::from("import * as rt from \"./runtime.js\";\n");
    out.push_str(&translator.helpers());
    out.push_str("export const app = { module: ");
    out.push_str(&translate::js_string(&program.module));
    out.push_str(", title: ");
    out.push_str(&translate::js_string(&title(&program.module)));
    out.push_str(" };\nexport const enums = {");
    for (index, (name, cases)) in enums.iter().enumerate() {
        out.push_str(if index == 0 { "\n  " } else { ",\n  " });
        out.push_str(name);
        out.push_str(": [");
        let quoted: Vec<String> = cases
            .iter()
            .map(|case| translate::js_string(case))
            .collect();
        out.push_str(&quoted.join(", "));
        out.push(']');
    }
    out.push_str("\n};\nexport const entities = [");
    let mut counts = [entities.len(), enums.len(), 0, 0];
    for entity in &entities {
        counts[2] += entity.rules.len();
        counts[3] += entity.computed.len();
        let label = entity
            .fields
            .iter()
            .find(|field| field.ty == Ty::Str)
            .map_or("id", |field| field.name.as_str());
        out.push_str("\n  {\n    name: ");
        out.push_str(&translate::js_string(&entity.name));
        out.push_str(", path: ");
        out.push_str(&translate::js_string(&entity.path));
        out.push_str(", label: ");
        out.push_str(&translate::js_string(label));
        out.push_str(",\n    fields: [");
        for field in &entity.fields {
            out.push_str("\n      { name: ");
            out.push_str(&translate::js_string(&field.name));
            match (&field.reference, &field.ty) {
                (Some(target), _) => {
                    out.push_str(", type: \"ref\", ref: ");
                    out.push_str(&translate::js_string(target));
                }
                (None, Ty::Enum(name)) => {
                    out.push_str(", type: \"enum\", enum: ");
                    out.push_str(&translate::js_string(name));
                }
                (None, ty) => {
                    out.push_str(", type: \"");
                    out.push_str(ty.js_name());
                    out.push('"');
                }
            }
            out.push_str(" },");
        }
        out.push_str("\n    ],\n    rules: [");
        for rule in &entity.rules {
            out.push_str("\n      ");
            out.push_str(rule);
            out.push(',');
        }
        out.push_str("\n    ],\n    computed: [");
        for computed in &entity.computed {
            out.push_str("\n      ");
            out.push_str(computed);
            out.push(',');
        }
        out.push_str("\n    ],\n  },");
    }
    out.push_str("\n];\n");
    Ok((out, counts))
}

/// The entity whose `<path>_` or run-together `<lowercase name>_` prefix is
/// the longest prefix of `name`, with that prefix's length.
fn owning_entity(entities: &[Entity], name: &str) -> Option<(usize, usize)> {
    entities
        .iter()
        .enumerate()
        .flat_map(|(index, entity)| {
            [entity.path.clone(), entity.name.to_ascii_lowercase()]
                .into_iter()
                .map(move |prefix| (index, prefix))
        })
        .filter(|(_, prefix)| {
            name.len() > prefix.len() + 1
                && name.starts_with(prefix.as_str())
                && name.as_bytes()[prefix.len()] == b'_'
        })
        .map(|(index, prefix)| (index, prefix.len()))
        .max_by_key(|(_, length)| *length)
}

/// `team.desk` becomes `Desk`: the last module segment, capitalised.
fn title(module: &str) -> String {
    let last = module.rsplit('.').next().unwrap_or(module);
    let mut chars = last.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}
