//! Executable Project-v11 native provider and generated safe-Rust conformance.
#![cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]

use crate::{full_toolchain, native_rust_cargo};

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

use semaprax::project::{with_authenticated_project, PublicApiSubject};
use sha2::{Digest, Sha256};

static SERIAL: AtomicU64 = AtomicU64::new(0);

const MANIFEST: &str = "schema = \"semaprax.project.v11\"\nname = \"nested-native\"\nversion = \"1.0.0\"\nprofile = \"nested-owned-record-api.v1\"\nentry = \"nested.app\"\nsources = [\"src/app.spx\", \"src/tests.spx\"]\nweb_exports = [\"nested.build\"]\ntests = [\"nested.tests\"]\n";
const SOURCE: &str = r#"module nested.app;
@id("nested.payload") record Payload {
    @id("nested.payload.bytes") bytes: Bytes,
    @id("nested.payload.size") size: usize,
}
@id("nested.envelope") record Envelope {
    @id("nested.envelope.left") left: Payload,
    @id("nested.envelope.enabled") enabled: bool,
    @id("nested.envelope.right") right: Payload,
}
@id("nested.marker") fn marker() -> Bytes { let value = [120u8]; bytes_copy(array_as_slice(value)) }
@id("nested.build") fn build(input: borrow Slice<u8>) -> Envelope {
    Envelope {
        left: Payload { bytes: bytes_copy(input), size: byte_len(input) },
        enabled: true,
        right: Payload { bytes: marker(), size: 1usize },
    }
}
@id("nested.main") fn main() -> i64 { 0 }
"#;
const TEST_SOURCE: &str =
    "module nested.tests;\n@id(\"nested.tests.main\") fn main() -> i64 { 0 }\n";
const CONSUMER_MANIFEST: &str = r#"[package]
name = "nested-record-consumer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
semaprax-generated-native-rust-owned-data-sdk = { path = "../sdk", version = "=0.1.0" }

[workspace]
"#;
const LOCK: &str = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "nested-record-consumer"
version = "0.1.0"
dependencies = [
 "semaprax-generated-native-rust-owned-data-sdk",
]

[[package]]
name = "semaprax-generated-native-rust-owned-data-sdk"
version = "0.1.0"
"#;

struct Fixture(PathBuf);
impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

struct CargoTarget(PathBuf);
impl Drop for CargoTarget {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn unique(label: &str) -> PathBuf {
    std::env::temp_dir().join(format!(
        "semaprax-v11-{label}-{}-{}",
        std::process::id(),
        SERIAL.fetch_add(1, Ordering::Relaxed)
    ))
}

/// Resolve a held tool exactly as the Project v8 evidence beside it does.
///
/// The publication authority holds a prepared tool image, so a configured
/// `/usr/bin/clang` that is a symlink to the versioned binary is refused. Both
/// the configured value and the fallbacks are canonicalized before use.
fn configured_tool(variable: &str, candidates: &[&str]) -> PathBuf {
    if let Some(configured) = std::env::var_os(variable)
        .map(PathBuf::from)
        .filter(|path| path.is_absolute() && path.is_file())
    {
        if let Ok(canonical) = configured.canonicalize() {
            return canonical;
        }
    }
    candidates
        .iter()
        .map(PathBuf::from)
        .filter_map(|path| path.canonicalize().ok())
        .find(|path| path.is_absolute() && path.is_file())
        .unwrap_or_else(|| panic!("{variable} must name an installed absolute tool"))
}

fn write_project() -> Fixture {
    let root = unique("native");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(root.join("semaprax.toml"), MANIFEST).unwrap();
    fs::write(
        root.join("src/app.spx"),
        semaprax::format::canonical(&semaprax::parse(SOURCE, Path::new("src/app.spx")).unwrap()),
    )
    .unwrap();
    fs::write(
        root.join("src/tests.spx"),
        semaprax::format::canonical(
            &semaprax::parse(TEST_SOURCE, Path::new("src/tests.spx")).unwrap(),
        ),
    )
    .unwrap();
    Fixture(root.canonicalize().unwrap())
}

fn files(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fs::read_dir(root)
        .unwrap()
        .map(|row| {
            let row = row.unwrap();
            assert!(row.file_type().unwrap().is_file());
            (
                row.file_name().into_string().unwrap(),
                fs::read(row.path()).unwrap(),
            )
        })
        .collect()
}

fn host_name(prefix: &str, id: &str) -> String {
    use std::fmt::Write as _;
    let mut result = prefix.to_owned();
    for byte in id.bytes() {
        write!(result, "{byte:02x}").unwrap();
    }
    result
}

fn consumer_source() -> String {
    let envelope = host_name("SpxRecordId", "nested.envelope");
    let left = host_name("spx_field_id_", "nested.envelope.left");
    let enabled = host_name("spx_field_id_", "nested.envelope.enabled");
    let right = host_name("spx_field_id_", "nested.envelope.right");
    let bytes = host_name("spx_field_id_", "nested.payload.bytes");
    let size = host_name("spx_field_id_", "nested.payload.size");
    format!(
        r#"use semaprax_generated_native_rust_owned_data_sdk::{{CallError,NativeRustOwnedDataSdk,{envelope}}};
fn check(value:{envelope},expected:&[u8]){{assert!(value.{enabled});assert_eq!(value.{left}.{bytes},expected);assert_eq!(value.{right}.{bytes},b"x");assert_eq!(value.{left}.{size},expected.len());assert_eq!(value.{right}.{size},1);}}
fn main(){{let mut sdk=NativeRustOwnedDataSdk::new().unwrap();let exact=vec![3u8;65535];check(sdk.spx_nested_dot_build(&exact).unwrap(),&exact);let plus_one=vec![7u8;65536];assert_eq!(sdk.spx_nested_dot_build(&plus_one),Err(CallError::AdapterRejected));for expected in [b"left".as_slice(),b"again".as_slice()]{{check(sdk.spx_nested_dot_build(expected).unwrap(),expected);}}println!("project-v11-native-ok");}}
"#
    )
}

#[test]
fn project_v11_native_provider_and_safe_rust_are_atomic_and_repeatable() {
    let fixture = write_project();
    let manifest = fixture.0.join("semaprax.toml");
    let source_before = [
        fs::read(&manifest).unwrap(),
        fs::read(fixture.0.join("src/app.spx")).unwrap(),
        fs::read(fixture.0.join("src/tests.spx")).unwrap(),
    ];
    let (descriptor_bytes, descriptor_digest, provider_bytes) =
        with_authenticated_project(&manifest, |snapshot| {
            snapshot.check()?;
            let revision = snapshot.retain_revision();
            let descriptor = revision.nested_owned_record_api_descriptor()?;
            let subject = PublicApiSubject {
                project_schema: revision.manifest().schema(),
                project_revision: revision.project_revision(),
                workspace_revision: revision.workspace_revision(),
                project_graph_digest: revision.semantic_graph_digest(),
            };
            let provider = semaprax::codegen::emit_project_v11_native_nested_owned_record_provider(
                revision.entry_program(),
                revision.manifest().web_exports(),
                subject,
                &descriptor.canonical_bytes(),
                &descriptor.digest(),
            )
            .map_err(|error| vec![error])?;
            Ok((
                descriptor.canonical_bytes(),
                descriptor.digest(),
                provider.source().as_bytes().to_vec(),
            ))
        })
        .unwrap();
    assert!(String::from_utf8_lossy(&provider_bytes).contains("spx_owned_data_attach_batch_v1"));

    let clang = configured_tool("CLANG", &["/usr/bin/clang"]);
    let archiver = if cfg!(target_os = "macos") {
        configured_tool("SEMAPRAX_ARCHIVER", &["/usr/bin/libtool"])
    } else {
        configured_tool("SEMAPRAX_ARCHIVER", &["/usr/bin/ar", "/bin/ar"])
    };
    let output = Command::new(full_toolchain::binary())
        .args([
            "build",
            "--manifest-path",
            "semaprax.toml",
            "--target",
            "rust",
            "-o",
            "sdk",
        ])
        .current_dir(&fixture.0)
        .env("CLANG", clang)
        .env("SEMAPRAX_ARCHIVER", archiver)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let sdk = fixture.0.join("sdk");
    let package = files(&sdk);
    let archive = if cfg!(windows) {
        "semaprax_native_rust_owned_data_sdk.lib"
    } else {
        "libsemaprax_native_rust_owned_data_sdk.a"
    };
    assert_eq!(
        package.keys().map(String::as_str).collect::<Vec<_>>(),
        [
            "Cargo.toml",
            "build.rs",
            "descriptor.json",
            "lib.rs",
            archive,
            "owned_data_ffi.rs",
            "semaprax.native-rust-nested-owned-record-sdk.json",
        ]
        .into_iter()
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect::<Vec<_>>()
    );
    assert_eq!(package["descriptor.json"], descriptor_bytes);
    let manifest_json: serde_json::Value =
        serde_json::from_slice(&package["semaprax.native-rust-nested-owned-record-sdk.json"])
            .unwrap();
    assert_eq!(manifest_json["descriptor"]["digest"], descriptor_digest);
    assert_eq!(
        manifest_json["provider"]["abi"],
        "opaque-multi-handle-plus-scalars.v1"
    );
    assert_eq!(
        manifest_json["provider"]["source_sha256"],
        format!(
            "sha256:{:x}",
            semaprax::digest_hex::LowerHex(Sha256::digest(&provider_bytes))
        )
    );
    assert_eq!(manifest_json["files"].as_array().unwrap().len(), 6);

    let consumer = fixture.0.join("consumer");
    fs::create_dir_all(consumer.join("src")).unwrap();
    fs::write(consumer.join("Cargo.toml"), CONSUMER_MANIFEST).unwrap();
    fs::write(consumer.join("Cargo.lock"), LOCK).unwrap();
    fs::write(consumer.join("src/main.rs"), consumer_source()).unwrap();
    let target = CargoTarget(unique("cargo-target"));
    fs::create_dir(&target.0).unwrap();
    let ran = native_rust_cargo::cargo_command()
        .args(["run", "--quiet", "--locked", "--offline", "--manifest-path"])
        .arg(consumer.join("Cargo.toml"))
        .current_dir(&consumer)
        .env("CARGO_TARGET_DIR", &target.0)
        .output()
        .unwrap();
    assert!(
        ran.status.success(),
        "stdout={} stderr={}",
        String::from_utf8_lossy(&ran.stdout),
        String::from_utf8_lossy(&ran.stderr)
    );
    assert_eq!(ran.stdout, b"project-v11-native-ok\n");
    assert_eq!(
        fs::read(consumer.join("Cargo.lock")).unwrap(),
        LOCK.as_bytes()
    );
    assert_eq!(
        source_before,
        [
            fs::read(&manifest).unwrap(),
            fs::read(fixture.0.join("src/app.spx")).unwrap(),
            fs::read(fixture.0.join("src/tests.spx")).unwrap(),
        ]
    );
}
