//! Reachability-gated unsigned UTF-8 comparison, preserving old generated bytes.
use crate::ast::BinaryOp;
use crate::hir::{ResolvedExprKind, ResolvedProgram, ResolvedType};
pub(super) fn emit_runtime(
    output: &mut impl super::COutput,
    program: &ResolvedProgram,
    strings: super::output_profile::StringRuntimeSelection,
) {
    let mut pending = Vec::new();
    for function in super::string_runtime_functions(program, strings.include_instances) {
        pending.push(&function.body);
        pending.extend(function.requires.iter().chain(&function.ensures));
    }
    while let Some(expression) = pending.pop() {
        if matches!(&expression.kind, ResolvedExprKind::Binary { op: BinaryOp::Lt | BinaryOp::Le | BinaryOp::Gt | BinaryOp::Ge, left, .. } if left.ty == ResolvedType::String)
        {
            output.push_str(if strings.length_delimited {
                LENGTH_DELIMITED
            } else {
                LEGACY
            });
            return;
        }
        pending.extend(super::function_value::resolved_expr_children(expression));
    }
}
const LEGACY: &str = r#"static __attribute__((unused)) int spx_string_compare_ordered(const char *a,const char *b) { return strcmp(a,b); }
"#;
const LENGTH_DELIMITED: &str = r#"static __attribute__((unused)) int spx_string_compare_ordered(const char *a,const char *b) {
    uint64_t al=spx_string_length_v10(a),bl=spx_string_length_v10(b),n=al<bl?al:bl;
    int order=n==UINT64_C(0)?0:memcmp(a,b,(size_t)n);
    return order!=0?order:(al<bl?-1:(al>bl?1:0));
}
"#;
